import type { PayrollEntry, PayrollPeriod, PayrollRun, WorkEntry } from "../types.ts";
import type { PayrollImportBatch } from "./payrollImportPersistence.ts";
import type { PayrollSchedule } from "./payrollSchedule.ts";

export type PayrollIntegrityIssueCode =
  | "MULTIPLE_ACTIVE_SCHEDULES"
  | "OVERLAPPING_OPEN_PERIODS"
  | "DUPLICATE_PERIOD_BOUNDARY"
  | "MULTIPLE_RUNS_FOR_PERIOD"
  | "ORPHAN_RUN"
  | "PERIOD_VERSION_MISSING"
  | "SCHEDULE_VERSION_CONFLICT"
  | "STALE_AUTO_GENERATED_PERIOD"
  | "ORPHAN_ENTRY"
  | "ORPHAN_ALLOCATION";

export interface PayrollIntegrityIssue {
  code: PayrollIntegrityIssueCode;
  message: string;
  periodIds?: string[];
  scheduleIds?: string[];
}

export interface PayrollPeriodSourceContext {
  runs?: readonly PayrollRun[];
  entries?: readonly PayrollEntry[];
  workEntries?: readonly WorkEntry[];
  importBatches?: readonly PayrollImportBatch[];
}

export interface PayrollPeriodOverlap {
  periodIds: string[];
  overlapStart: string;
  overlapEnd: string;
  locked: boolean;
}

export interface PayrollIntegrityReport {
  activeScheduleCount: number;
  overlappingPeriods: PayrollPeriodOverlap[];
  duplicateBoundaries: string[][];
  multipleRuns: string[][];
  orphanRuns: string[];
  staleGeneratedPeriods: string[];
  missingVersions: string[];
  orphanEntries: string[];
  orphanAllocations: string[];
  issues: PayrollIntegrityIssue[];
}

export interface PayrollPeriodReconciliationResult {
  periods: PayrollPeriod[];
  retiredPeriodIds: string[];
  issues: PayrollIntegrityIssue[];
}

function boundaryKey(period: Pick<PayrollPeriod, "scheduleId" | "periodStart" | "periodEnd">) {
  return `${period.scheduleId || "manual"}:${period.periodStart}:${period.periodEnd}`;
}

function dateBoundaryKey(period: Pick<PayrollPeriod, "periodStart" | "periodEnd">) {
  return `${period.periodStart}:${period.periodEnd}`;
}

function overlaps(left: Pick<PayrollPeriod, "periodStart" | "periodEnd">, right: Pick<PayrollPeriod, "periodStart" | "periodEnd">) {
  return left.periodStart <= right.periodEnd && right.periodStart <= left.periodEnd;
}

export function isPayrollPeriodLocked(period: Pick<PayrollPeriod, "status" | "lockedAt">) {
  return Boolean(period.lockedAt) || ["APPROVED", "PAID", "VOID"].includes(period.status);
}

function periodRunIds(period: PayrollPeriod, runs: readonly PayrollRun[]) {
  return runs.filter((run) => run.periodId === period.id).map((run) => run.id);
}

function hasCommittedImport(period: PayrollPeriod, importBatches: readonly PayrollImportBatch[]) {
  return importBatches.some((batch) => batch.status !== "VOIDED" && batch.committedPayrollPeriodId === period.id);
}

export function isPayrollPeriodDataBearing(period: PayrollPeriod, context: PayrollPeriodSourceContext = {}) {
  const runs = context.runs || [];
  const runIds = new Set(periodRunIds(period, runs));
  if ((context.entries || []).some((entry) => runIds.has(entry.payrollRunId))) return true;
  if ((context.workEntries || []).some((entry) => entry.periodId === period.id && entry.status !== "VOID")) return true;
  if (hasCommittedImport(period, context.importBatches || [])) return true;
  if (period.notes?.trim()) return true;
  if (runs.some((run) => runIds.has(run.id) && ["CALCULATED", "APPROVED", "PAID"].includes(run.status))) return true;
  return false;
}

export function isSafeToRetirePayrollPeriod(period: PayrollPeriod, context: PayrollPeriodSourceContext = {}) {
  return period.autoGenerated === true
    && (period.status === "DRAFT" || period.status === "OPEN")
    && !isPayrollPeriodLocked(period)
    && !isPayrollPeriodDataBearing(period, context);
}

export function findExactDuplicatePayrollPeriods(periods: readonly PayrollPeriod[]) {
  const groups = new Map<string, string[]>();
  for (const period of periods) {
    const key = dateBoundaryKey(period);
    const ids = groups.get(key) || [];
    ids.push(period.id);
    groups.set(key, ids);
  }
  return [...groups.values()].filter((ids) => ids.length > 1);
}

export function findOverlappingPayrollPeriods(periods: readonly PayrollPeriod[], includeLocked = true): PayrollPeriodOverlap[] {
  const active = periods
    .filter((period) => period.status !== "VOID" && (includeLocked || !isPayrollPeriodLocked(period)))
    .slice()
    .sort((left, right) => left.periodStart.localeCompare(right.periodStart) || left.periodEnd.localeCompare(right.periodEnd) || left.id.localeCompare(right.id));
  const result: PayrollPeriodOverlap[] = [];
  for (let leftIndex = 0; leftIndex < active.length; leftIndex += 1) {
    for (let rightIndex = leftIndex + 1; rightIndex < active.length; rightIndex += 1) {
      const left = active[leftIndex]!;
      const right = active[rightIndex]!;
      if (right.periodStart > left.periodEnd) break;
      if (!overlaps(left, right) || boundaryKey(left) === boundaryKey(right)) continue;
      const overlapStart = left.periodStart > right.periodStart ? left.periodStart : right.periodStart;
      const overlapEnd = left.periodEnd < right.periodEnd ? left.periodEnd : right.periodEnd;
      result.push({ periodIds: [left.id, right.id], overlapStart, overlapEnd, locked: isPayrollPeriodLocked(left) || isPayrollPeriodLocked(right) });
    }
  }
  return result;
}

function primaryScheduleSort(left: PayrollSchedule, right: PayrollSchedule) {
  return (right.updatedAt || "").localeCompare(left.updatedAt || "")
    || (right.createdAt || "").localeCompare(left.createdAt || "")
    || right.effectiveFrom.localeCompare(left.effectiveFrom)
    || right.id.localeCompare(left.id);
}

export function selectPrimaryPayrollSchedule(schedules: readonly PayrollSchedule[]) {
  return schedules.filter((schedule) => schedule.active).slice().sort(primaryScheduleSort)[0]
    || schedules.slice().sort(primaryScheduleSort)[0];
}

export function reconcileObsoleteGeneratedPayrollPeriods(
  periods: readonly PayrollPeriod[],
  desiredPeriods: readonly PayrollPeriod[],
  options: PayrollPeriodSourceContext & { referenceDate: string; horizonEnd?: string } ,
): PayrollPeriodReconciliationResult {
  const desiredBoundaries = new Set(desiredPeriods.map(boundaryKey));
  const retiredPeriodIds: string[] = [];
  const issues: PayrollIntegrityIssue[] = [];
  const byBoundary = new Map<string, PayrollPeriod[]>();
  for (const period of periods) {
    const rows = byBoundary.get(boundaryKey(period)) || [];
    rows.push(period);
    byBoundary.set(boundaryKey(period), rows);
  }
  for (const rows of byBoundary.values()) {
    if (rows.length < 2) continue;
    const keeper = rows.find((period) => !isSafeToRetirePayrollPeriod(period, options)) || rows[0]!;
    for (const duplicate of rows) {
      if (duplicate.id === keeper.id || !isSafeToRetirePayrollPeriod(duplicate, options)) continue;
      retiredPeriodIds.push(duplicate.id);
      issues.push({ code: "DUPLICATE_PERIOD_BOUNDARY", message: "An empty duplicate payroll period was retired.", periodIds: [keeper.id, duplicate.id] });
    }
  }

  const nextPeriods = periods.map((period) => {
    if (retiredPeriodIds.includes(period.id)) return period;
    const withinHorizon = !options.horizonEnd || period.periodStart <= options.horizonEnd;
    const prospective = period.periodEnd >= options.referenceDate && withinHorizon;
    const obsolete = prospective && period.autoGenerated === true && !desiredBoundaries.has(boundaryKey(period));
    if (!obsolete || !isSafeToRetirePayrollPeriod(period, options)) return period;
    retiredPeriodIds.push(period.id);
    issues.push({ code: "STALE_AUTO_GENERATED_PERIOD", message: "An empty generated payroll period no longer matches the active schedule and was retired.", periodIds: [period.id] });
    return {
      ...period,
      status: "VOID" as const,
      notes: [period.notes, "Retired during prospective payroll schedule reconciliation."].filter(Boolean).join(" "),
      updatedAt: new Date().toISOString(),
    };
  });
  return { periods: nextPeriods, retiredPeriodIds: [...new Set(retiredPeriodIds)], issues };
}

export function retireEmptyGeneratedPayrollRuns(
  runs: readonly PayrollRun[],
  retiredPeriodIds: readonly string[],
  entries: readonly PayrollEntry[] = [],
) {
  const retired = new Set(retiredPeriodIds);
  const entryRunIds = new Set(entries.map((entry) => entry.payrollRunId));
  return runs.map((run) => {
    if (!retired.has(run.periodId) || run.status !== "DRAFT" || entryRunIds.has(run.id)) return run;
    return { ...run, status: "VOID" as const, notes: [run.notes, "Retired with an empty obsolete generated payroll period."].filter(Boolean).join(" ") };
  });
}

export function inspectPayrollIntegrity(
  schedules: readonly PayrollSchedule[],
  periods: readonly PayrollPeriod[],
  runs: readonly PayrollRun[],
  entries: readonly PayrollEntry[] = [],
  allocations: readonly { id: string; payrollEntryId: string }[] = [],
  context: PayrollPeriodSourceContext = {},
): PayrollIntegrityReport {
  const activeSchedules = schedules.filter((schedule) => schedule.active);
  const duplicateBoundaries = findExactDuplicatePayrollPeriods(periods);
  const overlappingPeriods = findOverlappingPayrollPeriods(periods, true);
  const runsByPeriod = new Map<string, PayrollRun[]>();
  for (const run of runs) runsByPeriod.set(run.periodId, [...(runsByPeriod.get(run.periodId) || []), run]);
  const periodIds = new Set(periods.map((period) => period.id));
  const runIds = new Set(runs.map((run) => run.id));
  const entryIds = new Set(entries.map((entry) => entry.id));
  const scheduleVersions = new Set(schedules.flatMap((schedule) => (schedule.versions || []).map((version) => version.id)));
  const missingVersions = periods.filter((period) => period.scheduleId && period.scheduleVersionId && !scheduleVersions.has(period.scheduleVersionId)).map((period) => period.id);
  const orphanRuns = runs.filter((run) => !periodIds.has(run.periodId)).map((run) => run.id);
  const orphanEntries = entries.filter((entry) => !runIds.has(entry.payrollRunId)).map((entry) => entry.id);
  const orphanAllocations = allocations.filter((allocation) => !entryIds.has(allocation.payrollEntryId)).map((allocation) => allocation.id);
  const staleGeneratedPeriods = periods.filter((period) => period.autoGenerated && period.status !== "VOID" && !isPayrollPeriodDataBearing(period, context)).map((period) => period.id);
  const multipleRuns = [...runsByPeriod.entries()].filter(([, rows]) => rows.length > 1).map(([periodId]) => [periodId]);
  const issues: PayrollIntegrityIssue[] = [];
  if (activeSchedules.length > 1) issues.push({ code: "MULTIPLE_ACTIVE_SCHEDULES", message: "More than one active payroll schedule is configured.", scheduleIds: activeSchedules.map((schedule) => schedule.id) });
  for (const overlap of overlappingPeriods) {
    issues.push({ code: "OVERLAPPING_OPEN_PERIODS", message: "Payroll periods overlap.", periodIds: overlap.periodIds });
  }
  for (const duplicate of duplicateBoundaries) issues.push({ code: "DUPLICATE_PERIOD_BOUNDARY", message: "Payroll periods share the same date boundary.", periodIds: duplicate });
  for (const periodIdsForRuns of multipleRuns) issues.push({ code: "MULTIPLE_RUNS_FOR_PERIOD", message: "A payroll period has more than one run.", periodIds: periodIdsForRuns });
  for (const periodId of orphanRuns) issues.push({ code: "ORPHAN_RUN", message: "A payroll run is not linked to a payroll period.", periodIds: [periodId] });
  for (const periodId of missingVersions) issues.push({ code: "PERIOD_VERSION_MISSING", message: "A generated period references a missing schedule version.", periodIds: [periodId] });
  for (const entryId of orphanEntries) issues.push({ code: "ORPHAN_ENTRY", message: "A payroll entry is not linked to a payroll run.", periodIds: [entryId] });
  for (const allocationId of orphanAllocations) issues.push({ code: "ORPHAN_ALLOCATION", message: "A payroll allocation is not linked to a payroll entry.", periodIds: [allocationId] });
  return { activeScheduleCount: activeSchedules.length, overlappingPeriods, duplicateBoundaries, multipleRuns, orphanRuns, staleGeneratedPeriods, missingVersions, orphanEntries, orphanAllocations, issues };
}
