import type {
  PayrollEntry,
  PayrollPeriod,
  PayrollProjectAllocation,
  PayrollRun,
  Project,
  ProjectWorkerAssignment,
  Worker,
  WorkEntry,
} from "../types.ts";
import {
  generatePayrollPeriodsAroundReference,
  mergeGeneratedPayrollPeriods,
  selectCurrentPayrollPeriod,
  type PayrollSchedule,
  type PayrollScheduleVersion,
  type ScheduledPayrollPeriod,
} from "./payrollSchedule.ts";
import {
  buildPayrollDraft,
  type ApprovedWorkEntry,
  type AutomationMode,
  type PayrollAssignment,
  type PayrollDraft,
  type RecurringPayrollComponent,
  type WorkerCompensationProfile,
} from "./payrollAutomation.ts";

export interface PayrollScheduleDefaults {
  id: string;
  name: string;
  effectiveFrom: string;
  frequency: "SEMI_MONTHLY";
  firstCutoffDay: number;
  secondCutoffDay: number;
  payDateRule: { type: "BUSINESS_DAYS"; offsetDays: number };
  autoGeneratePeriods: boolean;
  autoCalculate: boolean;
  autoCreateRuns: boolean;
  autoSelectCurrentPeriod: boolean;
  active: boolean;
  automationMode: "MANUAL" | "ASSISTED" | "AUTOMATED";
  versions?: PayrollScheduleVersion[];
}

export interface EnsurePayrollWorkflowInput {
  schedules: PayrollSchedule[];
  periods: PayrollPeriod[];
  runs: PayrollRun[];
  referenceDate: string;
  previous?: number;
  next?: number;
}

export interface EnsurePayrollWorkflowResult {
  periods: PayrollPeriod[];
  runs: PayrollRun[];
  createdPeriods: PayrollPeriod[];
  createdRuns: PayrollRun[];
}

export interface PayrollAutomationRecordInput {
  period: PayrollPeriod;
  run: PayrollRun;
  workers: Worker[];
  assignments: ProjectWorkerAssignment[];
  profiles?: WorkerCompensationProfile[];
  recurringComponents?: RecurringPayrollComponent[];
  workEntries: WorkEntry[];
  projects?: Project[];
  mode?: AutomationMode;
  existingAllocations?: PayrollProjectAllocation[];
  existingEntries?: PayrollEntry[];
}

function id(prefix: string) {
  return globalThis.crypto?.randomUUID?.() || `local-${prefix}-${Date.now()}-${Math.random().toString(36).slice(2)}`;
}

export function dateOnly(value = new Date()): string {
  return value.toISOString().slice(0, 10);
}

export function createDefaultPayrollSchedule(referenceDate = dateOnly()): PayrollScheduleDefaults {
  const scheduleId = id("schedule");
  const versionId = id("schedule-version");
  return {
    id: scheduleId,
    name: "Standard semi-monthly payroll",
    effectiveFrom: referenceDate,
    frequency: "SEMI_MONTHLY",
    firstCutoffDay: 15,
    secondCutoffDay: 0,
    payDateRule: { type: "BUSINESS_DAYS", offsetDays: 2 },
    autoGeneratePeriods: true,
    autoCalculate: false,
    autoCreateRuns: true,
    autoSelectCurrentPeriod: true,
    automationMode: "ASSISTED",
    active: true,
    versions: [{ id: versionId, scheduleId, version: 1, effectiveFrom: referenceDate, frequency: "SEMI_MONTHLY", customCutoffDay: 15, payDateRule: { type: "BUSINESS_DAYS", offsetDays: 2 }, autoGeneratePeriods: true, autoCalculate: false, autoCreateRuns: true, autoSelectCurrentPeriod: true, automationMode: "ASSISTED", active: true }],
  };
}

function toScheduledPeriod(period: PayrollPeriod): ScheduledPayrollPeriod {
  return {
    id: period.id,
    periodKey: `${period.scheduleId || "legacy"}:${period.periodStart}:${period.periodEnd}`,
    scheduleId: period.scheduleId || "legacy",
    scheduleVersionId: period.scheduleVersionId || "legacy",
    periodStart: period.periodStart,
    periodEnd: period.periodEnd,
    payDate: period.payDate,
    status: period.status as PayrollPeriod["status"],
    active: period.status !== "VOID",
    locked: Boolean(period.lockedAt) || ["APPROVED", "PAID", "VOID"].includes(period.status),
    notes: period.notes,
    createdAt: period.createdAt,
    updatedAt: period.updatedAt,
  };
}

function fromScheduledPeriod(period: ScheduledPayrollPeriod, previous?: PayrollPeriod): PayrollPeriod {
  return {
    id: period.id || previous?.id || id("period"),
    userId: previous?.userId,
    periodStart: period.periodStart,
    periodEnd: period.periodEnd,
    payDate: period.payDate,
    scheduleId: period.scheduleId === "legacy" ? previous?.scheduleId : period.scheduleId,
    scheduleVersionId: period.scheduleVersionId === "legacy" ? previous?.scheduleVersionId : period.scheduleVersionId,
    autoGenerated: period.scheduleId !== "legacy" || previous?.autoGenerated,
    lockedAt: previous?.lockedAt,
    status: period.status as PayrollPeriod["status"],
    notes: period.notes,
    createdAt: previous?.createdAt || period.createdAt || new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}

function boundary(period: Pick<PayrollPeriod, "scheduleId" | "periodStart" | "periodEnd">) {
  return `${period.scheduleId || "legacy"}:${period.periodStart}:${period.periodEnd}`;
}

/** Ensures only a bounded period horizon and one draft run per generated period. */
export function ensurePayrollPeriodsAndRuns(input: EnsurePayrollWorkflowInput): EnsurePayrollWorkflowResult {
  const previous = input.previous ?? 2;
  const next = input.next ?? 2;
  let periods = [...input.periods];
  const createdPeriods: PayrollPeriod[] = [];
  const createdRuns: PayrollRun[] = [];

  for (const schedule of input.schedules.filter((item) => item.active && item.autoGeneratePeriods)) {
    const generated = generatePayrollPeriodsAroundReference(schedule, input.referenceDate, { previous, next });
    const currentSchedulePeriods = periods.filter((period) => period.scheduleId === schedule.id);
    const merged = mergeGeneratedPayrollPeriods(currentSchedulePeriods.map(toScheduledPeriod), generated);
    const byId = new Map(currentSchedulePeriods.map((period) => [period.id, period]));
    const mergedPeriods = merged.map((period) => fromScheduledPeriod(period, period.id ? byId.get(period.id) : undefined));
    const mergedIds = new Set(mergedPeriods.map((period) => period.id));
    const nextPeriods = periods.filter((period) => period.scheduleId !== schedule.id || !mergedIds.has(period.id));
    periods = [...nextPeriods, ...mergedPeriods];
  }

  const current = selectCurrentPayrollPeriod(periods.filter((period) => period.scheduleId).map(toScheduledPeriod), input.referenceDate);
  if (current) {
    const currentPeriod = periods.find((period) => period.id === current.id);
    if (currentPeriod && currentPeriod.status === "DRAFT") {
      const opened = { ...currentPeriod, status: "OPEN" as const, updatedAt: new Date().toISOString() };
      periods = periods.map((period) => period.id === opened.id ? opened : period);
    }
  }

  const scheduleById = new Map(input.schedules.map((schedule) => [schedule.id, schedule]));
  for (const period of periods) {
    const schedule = period.scheduleId ? scheduleById.get(period.scheduleId) : undefined;
    const autoCreateRuns = Boolean(schedule && (schedule.autoCreateRuns ?? schedule.autoCalculate));
    if (!autoCreateRuns || period.status === "VOID") continue;
    if (!input.runs.some((run) => run.periodId === period.id) && !createdRuns.some((run) => run.periodId === period.id)) {
      const run: PayrollRun = { id: id("run"), periodId: period.id, status: "DRAFT", createdAt: new Date().toISOString(), notes: "Auto-created draft run from payroll schedule." };
      createdRuns.push(run);
    }
  }
  const knownPeriods = new Set(input.periods.map((period) => boundary(period)));
  for (const period of periods) if (!knownPeriods.has(boundary(period))) createdPeriods.push(period);
  const sortedPeriods = periods.sort((left, right) => right.periodEnd.localeCompare(left.periodEnd) || left.periodStart.localeCompare(right.periodStart));
  return { periods: sortedPeriods, runs: [...createdRuns, ...input.runs], createdPeriods, createdRuns };
}

function rosterWorker(worker: Worker) {
  return { id: worker.id, name: worker.displayName, archived: !worker.active, rate: worker.defaultRate, frequency: worker.defaultPayType, defaultLaborContext: "UNALLOCATED_REVIEW" as const };
}

function profileInput(profile: WorkerCompensationProfile) { return { ...profile, effectiveFrom: profile.effectiveFrom instanceof Date ? profile.effectiveFrom.toISOString() : profile.effectiveFrom, effectiveTo: profile.effectiveTo instanceof Date ? profile.effectiveTo.toISOString() : profile.effectiveTo }; }
function assignmentInput(assignment: ProjectWorkerAssignment): PayrollAssignment { return { id: assignment.id, workerId: assignment.workerId, effectiveFrom: assignment.startDate, effectiveTo: assignment.endDate, rate: assignment.rate, frequency: assignment.payType, laborContext: "PROJECT", projectId: assignment.projectId }; }
function workInput(entry: WorkEntry, projects: Project[]): ApprovedWorkEntry {
  const project = projects.find((item) => item.id === entry.projectId);
  return { id: entry.id, workerId: entry.workerId, periodId: entry.periodId, workDate: entry.workDate, approved: entry.status === "APPROVED", hours: entry.regularHours, days: entry.daysWorked, overtimeHours: entry.overtimeHours, overtimeRate: entry.overtimeRate, projectId: entry.projectId, project: project ? { id: project.id, archived: project.status === "ARCHIVED", active: project.status !== "ARCHIVED" } : undefined, projectArchived: project?.status === "ARCHIVED" };
}

export function buildAutomaticPayrollDraft(input: PayrollAutomationRecordInput): PayrollDraft {
  return buildPayrollDraft({
    period: { id: input.period.id, startDate: input.period.periodStart, endDate: input.period.periodEnd },
    mode: input.mode || "ASSISTED",
    workers: input.workers.map(rosterWorker),
    profiles: (input.profiles || []).map(profileInput),
    assignments: input.assignments.map(assignmentInput),
    recurringComponents: input.recurringComponents || [],
    workEntries: input.workEntries.map((entry) => workInput(entry, input.projects || [])),
    existingPayrollAllocations: input.existingAllocations?.map((allocation) => ({ id: allocation.id, amount: allocation.allocationAmount, projectId: allocation.projectId })) || [],
  });
}

export interface PayrollDraftRecords {
  entries: PayrollEntry[];
  allocations: PayrollProjectAllocation[];
}

export function payrollDraftToRecords(draft: PayrollDraft, runId: string, now = new Date().toISOString()): PayrollDraftRecords {
  const entries: PayrollEntry[] = draft.entries.map((entry) => {
    const earnings = entry.components.filter((component) => component.type === "EARNING").reduce((sum, component) => sum + component.amount, 0);
    const projectAllocatedCost = draft.allocations.filter((allocation) => allocation.workerId === entry.workerId && allocation.laborContext === "PROJECT").reduce((sum, allocation) => sum + allocation.amount, 0);
    const context = draft.allocations.find((allocation) => allocation.workerId === entry.workerId && allocation.laborContext !== "PROJECT")?.laborContext;
    return {
      id: id("entry"),
      payrollRunId: runId,
      workerId: entry.workerId,
      basePay: Math.max(0, entry.grossEarnings - earnings),
      regularPay: Math.max(0, entry.grossEarnings - earnings),
      overtimePay: 0,
      allowances: earnings,
      otherEarnings: earnings,
      grossPay: entry.grossEarnings,
      deductions: entry.deductions,
      otherDeductions: entry.deductions,
      employerCosts: entry.employerCosts,
      netPay: Math.max(0, entry.netPay),
      costContext: context ? { type: context, needsReview: context === "UNALLOCATED_REVIEW", label: context } : undefined,
      projectAllocatedCost,
      calculationSnapshot: { ...entry.source, automationMode: draft.mode, workEntryIds: entry.workEntryIds, components: entry.components, exceptions: draft.exceptions },
      createdAt: now,
    };
  });
  const entryIdByWorker = new Map(entries.map((entry) => [entry.workerId, entry.id]));
  const allocations: PayrollProjectAllocation[] = draft.allocations.filter((allocation) => allocation.laborContext === "PROJECT" && allocation.projectId).map((allocation) => ({ id: id("allocation"), payrollEntryId: entryIdByWorker.get(allocation.workerId) || "", projectId: allocation.projectId!, allocationAmount: allocation.amount, allocationPercentage: 0, source: "TIME_ENTRY" as const })).filter((allocation) => allocation.payrollEntryId);
  return { entries, allocations };
}
