/**
 * Pure payroll schedule/period domain helpers.
 *
 * Dates in this module are ISO calendar dates (YYYY-MM-DD), never timestamps.
 * All arithmetic is performed against UTC midnight so the host timezone cannot
 * change a generated period boundary.
 */

export type DateOnly = string;
export type Weekday = 0 | 1 | 2 | 3 | 4 | 5 | 6;
export type PayrollFrequency = "DAILY" | "WEEKLY" | "BIWEEKLY" | "SEMI_MONTHLY" | "MONTHLY" | "CUSTOM";

export const PAYROLL_FREQUENCIES = Object.freeze({
  DAILY: "DAILY",
  WEEKLY: "WEEKLY",
  BIWEEKLY: "BIWEEKLY",
  SEMI_MONTHLY: "SEMI_MONTHLY",
  MONTHLY: "MONTHLY",
  CUSTOM: "CUSTOM",
} as const);

export type PayrollPayDateRuleType = "SAME_PERIOD_END" | "CALENDAR_DAYS" | "BUSINESS_DAYS" | "FIXED_FOLLOWING_MONTH" | "MANUAL";

export const PAYROLL_PAY_DATE_RULES = Object.freeze({
  SAME_PERIOD_END: "SAME_PERIOD_END",
  CALENDAR_DAYS: "CALENDAR_DAYS",
  BUSINESS_DAYS: "BUSINESS_DAYS",
  FIXED_FOLLOWING_MONTH: "FIXED_FOLLOWING_MONTH",
  MANUAL: "MANUAL",
} as const);

export interface PayrollPayDateRule {
  type: PayrollPayDateRuleType;
  /** Used by CALENDAR_DAYS and BUSINESS_DAYS. Negative values are supported. */
  offsetDays?: number;
  /** Used by FIXED_FOLLOWING_MONTH. Values above the month length clamp to month-end. */
  dayOfMonth?: number;
}

export interface PayrollScheduleConfiguration {
  frequency: PayrollFrequency;
  /** Weekly period end weekday. Sunday is 0 and Saturday is 6. */
  weekEndDay?: Weekday;
  /** Anchor period end for WEEKLY, BIWEEKLY, or length-based CUSTOM schedules. */
  anchorPeriodEnd?: DateOnly;
  /** A monthly cutoff, e.g. 15 creates periods ending on the 15th and the next cutoff. */
  customCutoffDay?: number;
  /** Alternative practical custom rule: fixed length periods from anchorPeriodEnd. */
  customPeriodLengthDays?: number;
  /** Alternative monthly custom rule; endDay is treated as the cutoff. */
  customPeriodStartDay?: number;
  customPeriodEndDay?: number;
  /** Creates exactly one DRAFT run for each generated period. */
  autoCreateRuns?: boolean;
  /** Selects the current generated period when Payroll opens. */
  autoSelectCurrentPeriod?: boolean;
  automationMode?: "MANUAL" | "ASSISTED" | "AUTOMATED";
}

export interface PayrollScheduleVersion extends PayrollScheduleConfiguration {
  id: string;
  scheduleId: string;
  version: number;
  effectiveFrom: DateOnly;
  effectiveTo?: DateOnly;
  payDateRule: PayrollPayDateRule;
  autoGeneratePeriods: boolean;
  autoCalculate: boolean;
  active: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface PayrollSchedule extends PayrollScheduleConfiguration {
  id: string;
  userId?: string;
  name?: string;
  effectiveFrom: DateOnly;
  payDateRule: PayrollPayDateRule;
  autoGeneratePeriods: boolean;
  autoCalculate: boolean;
  active: boolean;
  versions?: PayrollScheduleVersion[];
  createdAt?: string;
  updatedAt?: string;
}

export type PayrollPeriodStatus = "DRAFT" | "OPEN" | "CALCULATED" | "APPROVED" | "PAID" | "VOID" | string;

export interface GeneratedPayrollPeriod {
  periodKey: string;
  scheduleId: string;
  scheduleVersionId: string;
  periodStart: DateOnly;
  periodEnd: DateOnly;
  payDate?: DateOnly;
  status: PayrollPeriodStatus;
  active: boolean;
}

/** The canonical date shape produced by a schedule version. */
export interface PayrollPeriodShape {
  periodStart: DateOnly;
  periodEnd: DateOnly;
  payDate?: DateOnly;
}

export type PayrollPeriodShapeInput = {
  periodStart: string;
  periodEnd: string;
  payDate?: string;
  scheduleId?: string;
  scheduleVersionId?: string;
};

export interface PayrollPeriodShapeValidationResult {
  valid: boolean;
  issues: string[];
  actual?: PayrollPeriodShape;
  expected?: PayrollPeriodShape;
}

export interface ScheduledPayrollPeriod extends GeneratedPayrollPeriod {
  id?: string;
  locked?: boolean;
  /** Finalized history (APPROVED/PAID/VOID/lockedAt) that must never be rewritten. */
  hardLocked?: boolean;
  autoGenerated?: boolean;
  notes?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface PayrollPeriodSelectionCandidate {
  id?: string;
  periodStart: DateOnly;
  periodEnd: DateOnly;
  status: string;
  active?: boolean;
  scheduleVersionId?: string;
}

export interface PayrollScheduleValidationResult {
  valid: boolean;
  issues: string[];
}

export interface GeneratePeriodsOptions {
  previous?: number;
  next?: number;
}

export const PAYROLL_SCHEDULES_STORAGE_KEY = "engineering_payroll_schedules";
export const PAYROLL_SCHEDULE_PERIODS_STORAGE_KEY = "engineering_payroll_schedule_periods";
export const LOCKED_PAYROLL_PERIOD_STATUSES = Object.freeze(["APPROVED", "PAID", "VOID"] as const);

const FREQUENCIES = new Set<string>(Object.values(PAYROLL_FREQUENCIES));
const PAY_DATE_RULE_TYPES = new Set<string>(Object.values(PAYROLL_PAY_DATE_RULES));
const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;
const MS_PER_DAY = 86_400_000;

function utcDate(date: DateOnly): Date {
  const [year, month, day] = date.split("-").map(Number);
  return new Date(Date.UTC(year, month - 1, day));
}

function formatDate(date: Date): DateOnly {
  return date.toISOString().slice(0, 10);
}

function isValidDateOnly(value: unknown): value is DateOnly {
  if (typeof value !== "string" || !ISO_DATE.test(value)) return false;
  const date = utcDate(value);
  return Number.isFinite(date.getTime()) && formatDate(date) === value;
}

function compareDates(left: DateOnly, right: DateOnly) { return left < right ? -1 : left > right ? 1 : 0; }

export function addDateDays(date: DateOnly, days: number): DateOnly {
  if (!isValidDateOnly(date) || !Number.isInteger(days)) throw new Error("addDateDays requires a valid date-only value and an integer day count.");
  const result = utcDate(date);
  result.setUTCDate(result.getUTCDate() + days);
  return formatDate(result);
}

export function daysBetweenDates(start: DateOnly, end: DateOnly): number {
  if (!isValidDateOnly(start) || !isValidDateOnly(end)) throw new Error("daysBetweenDates requires valid date-only values.");
  return Math.round((utcDate(end).getTime() - utcDate(start).getTime()) / MS_PER_DAY);
}

function daysInMonth(year: number, month: number) { return new Date(Date.UTC(year, month, 0)).getUTCDate(); }

function monthDate(year: number, month: number, day: number): DateOnly {
  const clampedMonth = month < 1 ? 1 : month > 12 ? 12 : month;
  return formatDate(new Date(Date.UTC(year, clampedMonth - 1, Math.min(day, daysInMonth(year, clampedMonth)) )));
}

function monthAfter(date: DateOnly, months: number): { year: number; month: number } {
  const source = utcDate(date);
  const value = source.getUTCFullYear() * 12 + source.getUTCMonth() + months;
  return { year: Math.floor(value / 12), month: (value % 12) + 1 };
}

function isWeekend(date: DateOnly) {
  const weekday = utcDate(date).getUTCDay();
  return weekday === 0 || weekday === 6;
}

function nextOrSameWeekday(date: DateOnly, weekday: Weekday): DateOnly {
  return addDateDays(date, (weekday - utcDate(date).getUTCDay() + 7) % 7);
}

function normalizeAnchor(version: PayrollScheduleVersion): DateOnly {
  if (version.anchorPeriodEnd) return version.anchorPeriodEnd;
  const endDay = version.weekEndDay ?? 6;
  return nextOrSameWeekday(version.effectiveFrom, endDay);
}

function periodKey(scheduleId: string, versionId: string, start: DateOnly, end: DateOnly) {
  return `${scheduleId}:${versionId}:${start}:${end}`;
}

function versionFromSchedule(schedule: PayrollSchedule): PayrollScheduleVersion {
  return {
    id: `${schedule.id}:v1`,
    scheduleId: schedule.id,
    version: 1,
    effectiveFrom: schedule.effectiveFrom,
    frequency: schedule.frequency,
    weekEndDay: schedule.weekEndDay,
    anchorPeriodEnd: schedule.anchorPeriodEnd,
    customCutoffDay: schedule.customCutoffDay,
    customPeriodLengthDays: schedule.customPeriodLengthDays,
    customPeriodStartDay: schedule.customPeriodStartDay,
    customPeriodEndDay: schedule.customPeriodEndDay,
    payDateRule: schedule.payDateRule,
    autoGeneratePeriods: schedule.autoGeneratePeriods,
    autoCalculate: schedule.autoCalculate,
    active: schedule.active,
  };
}

/** Returns persisted versions, with the legacy schedule-level configuration represented as v1. */
export function getPayrollScheduleVersions(schedule: PayrollSchedule): PayrollScheduleVersion[] {
  return schedule.versions?.length ? schedule.versions.slice() : [versionFromSchedule(schedule)];
}

function activeScheduleVersions(schedule: PayrollSchedule): PayrollScheduleVersion[] {
  return getPayrollScheduleVersions(schedule)
    .filter((version) => version.active && version.scheduleId === schedule.id && isValidDateOnly(version.effectiveFrom) && (!version.effectiveTo || isValidDateOnly(version.effectiveTo)))
    .sort((left, right) => compareDates(left.effectiveFrom, right.effectiveFrom) || left.version - right.version || left.id.localeCompare(right.id));
}

function nextActiveScheduleVersion(schedule: PayrollSchedule, referenceDate: DateOnly): PayrollScheduleVersion | undefined {
  return activeScheduleVersions(schedule).find((version) => compareDates(version.effectiveFrom, referenceDate) > 0);
}

export function resolvePayrollScheduleVersion(schedule: PayrollSchedule, referenceDate: DateOnly): PayrollScheduleVersion | undefined {
  assertValidDateOnly(referenceDate, "referenceDate");
  return activeScheduleVersions(schedule)
    .filter((version) => compareDates(version.effectiveFrom, referenceDate) <= 0 && (!version.effectiveTo || compareDates(referenceDate, version.effectiveTo) <= 0))
    .at(-1);
}

function assertValidDateOnly(value: unknown, label: string): asserts value is DateOnly {
  if (!isValidDateOnly(value)) throw new Error(`${label} must be a valid YYYY-MM-DD date.`);
}

function validatePayDateRule(rule: PayrollPayDateRule, issues: string[]) {
  if (!rule || !PAY_DATE_RULE_TYPES.has(rule.type)) {
    issues.push("Pay-date rule type is invalid.");
    return;
  }
  if (rule.type === "CALENDAR_DAYS" || rule.type === "BUSINESS_DAYS") {
    if (!Number.isInteger(rule.offsetDays)) issues.push(`${rule.type} requires an integer offsetDays.`);
  }
  if (rule.type === "FIXED_FOLLOWING_MONTH" && (!Number.isInteger(rule.dayOfMonth) || (rule.dayOfMonth as number) < 1 || (rule.dayOfMonth as number) > 31)) {
    issues.push("FIXED_FOLLOWING_MONTH requires dayOfMonth between 1 and 31.");
  }
}

function validateVersion(version: PayrollScheduleVersion, schedule: PayrollSchedule | undefined, issues: string[]) {
  if (!version.id || !version.scheduleId) issues.push("Schedule versions require id and scheduleId.");
  if (!Number.isInteger(version.version) || version.version < 1) issues.push("Schedule version must be a positive integer.");
  if (!isValidDateOnly(version.effectiveFrom)) issues.push(`Schedule version ${version.id || "(unknown)"} has an invalid effectiveFrom.`);
  if (version.effectiveTo && !isValidDateOnly(version.effectiveTo)) issues.push(`Schedule version ${version.id || "(unknown)"} has an invalid effectiveTo.`);
  if (version.effectiveTo && compareDates(version.effectiveTo, version.effectiveFrom) < 0) issues.push(`Schedule version ${version.id || "(unknown)"} ends before it starts.`);
  if (schedule && version.scheduleId !== schedule.id) issues.push(`Schedule version ${version.id || "(unknown)"} belongs to a different schedule.`);
  if (schedule && compareDates(version.effectiveFrom, schedule.effectiveFrom) < 0) issues.push(`Schedule version ${version.id || "(unknown)"} predates its schedule.`);
  validateConfiguration(version, issues);
  validatePayDateRule(version.payDateRule, issues);
}

function validateConfiguration(configuration: PayrollScheduleConfiguration, issues: string[]) {
  if (!FREQUENCIES.has(configuration.frequency)) issues.push("Payroll frequency is invalid.");
  if (configuration.weekEndDay !== undefined && (!Number.isInteger(configuration.weekEndDay) || configuration.weekEndDay < 0 || configuration.weekEndDay > 6)) issues.push("weekEndDay must be a weekday from 0 through 6.");
  if (configuration.anchorPeriodEnd && !isValidDateOnly(configuration.anchorPeriodEnd)) issues.push("anchorPeriodEnd must be a valid date-only value.");
  if (configuration.customCutoffDay !== undefined && (!Number.isInteger(configuration.customCutoffDay) || configuration.customCutoffDay < 1 || configuration.customCutoffDay > 31)) issues.push("customCutoffDay must be between 1 and 31.");
  if (configuration.customPeriodLengthDays !== undefined && (!Number.isInteger(configuration.customPeriodLengthDays) || configuration.customPeriodLengthDays < 1)) issues.push("customPeriodLengthDays must be a positive integer.");
  if (configuration.customPeriodStartDay !== undefined && (!Number.isInteger(configuration.customPeriodStartDay) || configuration.customPeriodStartDay < 1 || configuration.customPeriodStartDay > 31)) issues.push("customPeriodStartDay must be between 1 and 31.");
  if (configuration.customPeriodEndDay !== undefined && (!Number.isInteger(configuration.customPeriodEndDay) || configuration.customPeriodEndDay < 1 || configuration.customPeriodEndDay > 31)) issues.push("customPeriodEndDay must be between 1 and 31.");
  if (configuration.frequency === "BIWEEKLY" && !configuration.anchorPeriodEnd) issues.push("BIWEEKLY schedules require anchorPeriodEnd.");
  if (configuration.frequency === "CUSTOM" && !configuration.customCutoffDay && !configuration.customPeriodLengthDays && !configuration.customPeriodStartDay && !configuration.customPeriodEndDay) issues.push("CUSTOM schedules require a cutoff day, period length, or custom period boundary.");
  if (configuration.frequency === "CUSTOM" && (configuration.customPeriodStartDay !== undefined) !== (configuration.customPeriodEndDay !== undefined)) issues.push("CUSTOM schedules require both customPeriodStartDay and customPeriodEndDay when using explicit monthly boundaries.");
  if (configuration.customPeriodLengthDays && !configuration.anchorPeriodEnd) issues.push("Length-based CUSTOM schedules require anchorPeriodEnd.");
}

export function validatePayrollSchedule(schedule: PayrollSchedule): PayrollScheduleValidationResult {
  const issues: string[] = [];
  if (!schedule || typeof schedule !== "object") return { valid: false, issues: ["Payroll schedule is required."] };
  if (!schedule.id) issues.push("Payroll schedule requires an id.");
  if (!isValidDateOnly(schedule.effectiveFrom)) issues.push("Payroll schedule effectiveFrom must be a valid date-only value.");
  if (typeof schedule.active !== "boolean") issues.push("Payroll schedule active must be boolean.");
  if (typeof schedule.autoGeneratePeriods !== "boolean") issues.push("autoGeneratePeriods must be boolean.");
  if (typeof schedule.autoCalculate !== "boolean") issues.push("autoCalculate must be boolean.");
  validateConfiguration(schedule, issues);
  validatePayDateRule(schedule.payDateRule, issues);
  const versions = schedule.versions || [];
  const ordered = [...versions].sort((left, right) => compareDates(left.effectiveFrom, right.effectiveFrom) || left.version - right.version);
  ordered.forEach((version, index) => {
    validateVersion(version, schedule, issues);
    const next = ordered[index + 1];
    if (next && version.effectiveTo && compareDates(version.effectiveTo, next.effectiveFrom) >= 0) issues.push(`Schedule versions ${version.version} and ${next.version} overlap.`);
  });
  const activeOrdered = ordered.filter((version) => version.active && isValidDateOnly(version.effectiveFrom));
  if (activeOrdered[0] && isValidDateOnly(schedule.effectiveFrom) && compareDates(activeOrdered[0].effectiveFrom, schedule.effectiveFrom) > 0) {
    issues.push(`Active schedule versions do not cover the period from ${schedule.effectiveFrom} through ${addDateDays(activeOrdered[0].effectiveFrom, -1)}.`);
  }
  for (let index = 0; index < activeOrdered.length - 1; index += 1) {
    const version = activeOrdered[index]!;
    const next = activeOrdered[index + 1]!;
    if (!version.effectiveTo) {
      issues.push(`Schedule version ${version.version} has no effectiveTo before version ${next.version}; their active ranges overlap.`);
      continue;
    }
    if (!isValidDateOnly(version.effectiveTo)) continue;
    if (compareDates(addDateDays(version.effectiveTo, 1), next.effectiveFrom) < 0) {
      issues.push(`Schedule versions ${version.version} and ${next.version} leave an uncovered date gap.`);
    }
  }
  return { valid: issues.length === 0, issues };
}

export function assertValidPayrollSchedule(schedule: PayrollSchedule): asserts schedule is PayrollSchedule {
  const result = validatePayrollSchedule(schedule);
  if (!result.valid) throw new Error(`Invalid payroll schedule: ${result.issues.join(" ")}`);
}

function anchoredPeriod(version: PayrollScheduleVersion, referenceDate: DateOnly, length: number): [DateOnly, DateOnly] {
  const anchor = normalizeAnchor(version);
  const distance = daysBetweenDates(anchor, referenceDate);
  // The anchor is the end of its cycle: dates after it belong to the next
  // cycle, while dates before it remain in the anchored cycle until its start.
  const cycle = Math.ceil(distance / length);
  const end = addDateDays(anchor, cycle * length);
  return [addDateDays(end, -(length - 1)), end];
}

function monthlyCutoffPeriod(referenceDate: DateOnly, cutoffDay: number): [DateOnly, DateOnly] {
  const source = utcDate(referenceDate);
  const thisMonthEnd = monthDate(source.getUTCFullYear(), source.getUTCMonth() + 1, cutoffDay);
  if (compareDates(referenceDate, thisMonthEnd) <= 0) {
    const previous = monthAfter(referenceDate, -1);
    return [addDateDays(monthDate(previous.year, previous.month, cutoffDay), 1), thisMonthEnd];
  }
  const next = monthAfter(referenceDate, 1);
  return [addDateDays(thisMonthEnd, 1), monthDate(next.year, next.month, cutoffDay)];
}

function monthlyCustomBoundaryPeriod(referenceDate: DateOnly, startDay: number, endDay: number): [DateOnly, DateOnly] {
  const source = utcDate(referenceDate);
  const year = source.getUTCFullYear();
  const month = source.getUTCMonth() + 1;
  const next = monthAfter(referenceDate, 1);
  const currentStart = monthDate(year, month, startDay);
  const currentEnd = startDay <= endDay ? monthDate(year, month, endDay) : monthDate(next.year, next.month, endDay);
  if (compareDates(referenceDate, currentStart) < 0) {
    const previous = monthAfter(referenceDate, -1);
    const previousStart = monthDate(previous.year, previous.month, startDay);
    const previousEnd = startDay <= endDay ? monthDate(previous.year, previous.month, endDay) : monthDate(year, month, endDay);
    return [previousStart, previousEnd];
  }
  if (compareDates(referenceDate, currentEnd) <= 0) return [currentStart, currentEnd];
  const nextStart = monthDate(next.year, next.month, startDay);
  const following = monthAfter(nextStart, 1);
  const nextEnd = startDay <= endDay ? monthDate(next.year, next.month, endDay) : monthDate(following.year, following.month, endDay);
  return [nextStart, nextEnd];
}

function basePeriodFor(version: PayrollScheduleVersion, referenceDate: DateOnly): [DateOnly, DateOnly] {
  const source = utcDate(referenceDate);
  switch (version.frequency) {
    case "DAILY": return [referenceDate, referenceDate];
    case "WEEKLY": return anchoredPeriod({ ...version, anchorPeriodEnd: normalizeAnchor(version) }, referenceDate, 7);
    case "BIWEEKLY": return anchoredPeriod(version, referenceDate, 14);
    case "SEMI_MONTHLY": {
      const year = source.getUTCFullYear();
      const month = source.getUTCMonth() + 1;
      const firstEnd = monthDate(year, month, 15);
      return compareDates(referenceDate, firstEnd) <= 0 ? [monthDate(year, month, 1), firstEnd] : [monthDate(year, month, 16), monthDate(year, month, daysInMonth(year, month))];
    }
    case "MONTHLY": return [monthDate(source.getUTCFullYear(), source.getUTCMonth() + 1, 1), monthDate(source.getUTCFullYear(), source.getUTCMonth() + 1, daysInMonth(source.getUTCFullYear(), source.getUTCMonth() + 1))];
    case "CUSTOM": {
      if (version.customPeriodLengthDays) return anchoredPeriod(version, referenceDate, version.customPeriodLengthDays);
      if (version.customPeriodStartDay !== undefined && version.customPeriodEndDay !== undefined) return monthlyCustomBoundaryPeriod(referenceDate, version.customPeriodStartDay, version.customPeriodEndDay);
      return monthlyCutoffPeriod(referenceDate, version.customCutoffDay || version.customPeriodEndDay || 15);
    }
  }
}

function periodForDate(version: PayrollScheduleVersion, referenceDate: DateOnly): [DateOnly, DateOnly] | undefined {
  const [rawStart, rawEnd] = basePeriodFor(version, referenceDate);
  if (compareDates(referenceDate, version.effectiveFrom) < 0) return undefined;
  // Never persist a clipped transitional period for a fixed-frequency version.
  if (compareDates(rawStart, version.effectiveFrom) < 0) return undefined;
  if (version.effectiveTo && compareDates(rawStart, version.effectiveTo) > 0) return undefined;
  if (version.effectiveTo && compareDates(rawEnd, version.effectiveTo) > 0) return undefined;
  return [rawStart, rawEnd];
}

export function calculatePayrollPayDate(periodEnd: DateOnly, rule: PayrollPayDateRule): DateOnly | undefined {
  assertValidDateOnly(periodEnd, "periodEnd");
  if (!rule || !PAY_DATE_RULE_TYPES.has(rule.type)) throw new Error("Invalid pay-date rule.");
  if (rule.type === "MANUAL") return undefined;
  if (rule.type === "SAME_PERIOD_END") return periodEnd;
  if ((rule.type === "CALENDAR_DAYS" || rule.type === "BUSINESS_DAYS") && !Number.isInteger(rule.offsetDays)) throw new Error(`${rule.type} requires an integer offsetDays.`);
  if (rule.type === "CALENDAR_DAYS") return addDateDays(periodEnd, rule.offsetDays as number);
  if (rule.type === "BUSINESS_DAYS") {
    const direction = (rule.offsetDays as number) < 0 ? -1 : 1;
    let remaining = Math.abs(rule.offsetDays as number);
    let result = periodEnd;
    while (remaining > 0) {
      result = addDateDays(result, direction);
      if (!isWeekend(result)) remaining -= 1;
    }
    return result;
  }
  if (!Number.isInteger(rule.dayOfMonth) || (rule.dayOfMonth as number) < 1 || (rule.dayOfMonth as number) > 31) throw new Error("FIXED_FOLLOWING_MONTH requires dayOfMonth between 1 and 31.");
  const following = monthAfter(periodEnd, 1);
  return monthDate(following.year, following.month, rule.dayOfMonth as number);
}

export function generatePayrollPeriod(versionOrSchedule: PayrollScheduleVersion | PayrollSchedule, referenceDate: DateOnly): GeneratedPayrollPeriod | undefined {
  assertValidDateOnly(referenceDate, "referenceDate");
  const version = "scheduleId" in versionOrSchedule ? versionOrSchedule : resolvePayrollScheduleVersion(versionOrSchedule, referenceDate);
  if (!version) return undefined;
  const period = periodForDate(version, referenceDate);
  if (!period) return undefined;
  const [periodStart, periodEnd] = period;
  return {
    periodKey: periodKey(version.scheduleId, version.id, periodStart, periodEnd),
    scheduleId: version.scheduleId,
    scheduleVersionId: version.id,
    periodStart,
    periodEnd,
    payDate: calculatePayrollPayDate(periodEnd, version.payDateRule),
    status: "DRAFT",
    active: version.active,
  };
}

/** Each forward-search step advances the cursor by at least one canonical period. */
const FORWARD_SEARCH_MAX_STEPS = 800;

/**
 * Finds the first COMPLETE canonical period that can be generated at or after
 * referenceDate. A schedule version whose effectiveFrom falls inside the
 * current canonical cycle (e.g. "next payroll period" chosen mid-cycle)
 * deliberately rejects the clipped cycle, but the calendar must continue with
 * the next complete period instead of staying empty forever. Bounded: the
 * search advances at least one day per step and stops after
 * FORWARD_SEARCH_MAX_STEPS canonical boundaries.
 */
export function findFirstGeneratablePayrollPeriod(versionOrSchedule: PayrollScheduleVersion | PayrollSchedule, referenceDate: DateOnly): GeneratedPayrollPeriod | undefined {
  assertValidDateOnly(referenceDate, "referenceDate");
  const direct = generatePayrollPeriod(versionOrSchedule, referenceDate);
  if (direct) return direct;
  const schedule = "scheduleId" in versionOrSchedule ? undefined : versionOrSchedule;
  let cursor = referenceDate;
  for (let step = 0; step < FORWARD_SEARCH_MAX_STEPS; step += 1) {
    const version = schedule ? resolvePayrollScheduleVersion(schedule, cursor) : versionOrSchedule as PayrollScheduleVersion;
    if (!version) {
      // A date before the first active version can advance to that version's
      // effective boundary. A gap after an already-ended version is different:
      // stop instead of using an out-of-range fallback or silently jumping over
      // canonical periods that have no governing version.
      const nextVersion = nextActiveScheduleVersion(schedule!, cursor);
      const priorVersion = activeScheduleVersions(schedule!).filter((candidate) => compareDates(candidate.effectiveFrom, cursor) < 0).at(-1);
      if (!nextVersion || (priorVersion?.effectiveTo && compareDates(priorVersion.effectiveTo, cursor) < 0)) return undefined;
      cursor = nextVersion.effectiveFrom;
      continue;
    }
    let rawStart: DateOnly;
    let rawEnd: DateOnly;
    try {
      [rawStart, rawEnd] = basePeriodFor(version, cursor);
    } catch {
      return undefined;
    }
    // A canonical period that starts before the version's effectiveFrom can
    // never be generated: skip whole cycles, never clip them.
    const candidate = compareDates(rawStart, version.effectiveFrom) < 0 ? addDateDays(rawEnd, 1) : rawStart;
    const generated = generatePayrollPeriod(version, candidate);
    if (generated) return generated;
    const nextCursor = compareDates(candidate, cursor) > 0 ? candidate : addDateDays(rawEnd, 1);
    // A schedule can chain versions: crossing the resolved version's effectiveTo
    // must continue with whichever version applies at the next boundary instead
    // of abandoning the search.
    const nextVersion = schedule ? resolvePayrollScheduleVersion(schedule, nextCursor) : version;
    if (!nextVersion) return undefined;
    if (nextVersion.effectiveTo && compareDates(nextCursor, nextVersion.effectiveTo) > 0) return undefined;
    cursor = nextCursor;
  }
  return undefined;
}

export function getCanonicalPayrollPeriodShape(version: PayrollScheduleVersion, referenceDate: DateOnly): PayrollPeriodShape | undefined {
  const generated = generatePayrollPeriod(version, referenceDate);
  if (!generated) return undefined;
  return {
    periodStart: generated.periodStart,
    periodEnd: generated.periodEnd,
    ...(generated.payDate === undefined ? {} : { payDate: generated.payDate }),
  };
}

export function validatePayrollPeriodShape(period: PayrollPeriodShapeInput, version: PayrollScheduleVersion): PayrollPeriodShapeValidationResult {
  const issues: string[] = [];
  if (!period || typeof period !== "object") return { valid: false, issues: ["Payroll period is required."] };
  if (!version || typeof version !== "object") return { valid: false, issues: ["Payroll schedule version is required."] };
  if (period.scheduleId !== undefined && period.scheduleId !== version.scheduleId) issues.push("Payroll period scheduleId does not match its schedule version.");
  if (period.scheduleVersionId !== undefined && period.scheduleVersionId !== version.id) issues.push("Payroll period scheduleVersionId does not match its schedule version.");
  if (!isValidDateOnly(period.periodStart)) issues.push("Payroll period periodStart must be a valid date-only value.");
  if (!isValidDateOnly(period.periodEnd)) issues.push("Payroll period periodEnd must be a valid date-only value.");
  if (period.payDate !== undefined && !isValidDateOnly(period.payDate)) issues.push("Payroll period payDate must be a valid date-only value.");

  const actual: PayrollPeriodShape | undefined = isValidDateOnly(period.periodStart) && isValidDateOnly(period.periodEnd)
    ? { periodStart: period.periodStart, periodEnd: period.periodEnd, ...(period.payDate === undefined || !isValidDateOnly(period.payDate) ? {} : { payDate: period.payDate }) }
    : undefined;
  let expected: PayrollPeriodShape | undefined;
  if (actual) {
    try {
      expected = getCanonicalPayrollPeriodShape(version, actual.periodStart);
    } catch (error) {
      issues.push(error instanceof Error ? error.message : "Payroll period shape could not be generated.");
    }
    if (!expected) issues.push("Payroll period is outside its schedule version's effective range.");
    else {
      if (actual.periodStart !== expected.periodStart || actual.periodEnd !== expected.periodEnd) issues.push("Payroll period boundaries do not match the schedule version.");
      if (actual.payDate !== undefined && actual.payDate !== expected.payDate) issues.push("Payroll period payDate does not match its schedule version.");
    }
  }
  return { valid: issues.length === 0, issues, actual, expected };
}

export function generatePayrollPeriodsAroundReference(versionOrSchedule: PayrollScheduleVersion | PayrollSchedule, referenceDate: DateOnly, options: GeneratePeriodsOptions = {}): GeneratedPayrollPeriod[] {
  assertValidDateOnly(referenceDate, "referenceDate");
  const previousCount = options.previous ?? 1;
  const nextCount = options.next ?? 1;
  if (!Number.isInteger(previousCount) || previousCount < 0 || !Number.isInteger(nextCount) || nextCount < 0) throw new Error("previous and next period counts must be non-negative integers.");
  const schedule = "scheduleId" in versionOrSchedule ? undefined : versionOrSchedule;
  // The reference date can sit inside a canonical cycle that predates the
  // version's effectiveFrom (a schedule change applied mid-cycle). The clipped
  // cycle stays rejected, but the horizon continues from the first COMPLETE
  // future period instead of collapsing to an empty calendar.
  let current = generatePayrollPeriod(versionOrSchedule, referenceDate) ?? findFirstGeneratablePayrollPeriod(versionOrSchedule, referenceDate);
  if (!current) return [];
  const result: GeneratedPayrollPeriod[] = [current];
  const version = "scheduleId" in versionOrSchedule ? versionOrSchedule : resolvePayrollScheduleVersion(versionOrSchedule, referenceDate);
  let previousDate = addDateDays(current.periodStart, -1);
  for (let index = 0; index < previousCount; index += 1) {
    const previousVersion = schedule ? resolvePayrollScheduleVersion(schedule, previousDate) : version;
    if (!previousVersion) break;
    const previous = generatePayrollPeriod(previousVersion, previousDate);
    if (!previous || (schedule && previous.periodEnd < schedule.effectiveFrom)) break;
    result.unshift(previous);
    previousDate = addDateDays(previous.periodStart, -1);
  }
  let nextDate = addDateDays(current.periodEnd, 1);
  for (let index = 0; index < nextCount; index += 1) {
    const nextVersion = schedule ? resolvePayrollScheduleVersion(schedule, nextDate) : version;
    if (!nextVersion) break;
    const next = generatePayrollPeriod(nextVersion, nextDate);
    if (!next || (nextVersion.effectiveTo && compareDates(next.periodStart, nextVersion.effectiveTo) > 0)) break;
    result.push(next);
    nextDate = addDateDays(next.periodEnd, 1);
  }
  return result;
}

export const generatePayrollPeriods = generatePayrollPeriodsAroundReference;

function isLockedPeriod(period: ScheduledPayrollPeriod) {
  return period.locked === true || LOCKED_PAYROLL_PERIOD_STATUSES.includes(period.status as typeof LOCKED_PAYROLL_PERIOD_STATUSES[number]);
}

function isHardLockedPeriod(period: ScheduledPayrollPeriod) {
  return period.hardLocked === true || LOCKED_PAYROLL_PERIOD_STATUSES.includes(period.status as typeof LOCKED_PAYROLL_PERIOD_STATUSES[number]);
}

/** A generated empty tombstone is disposable infrastructure, not history. */
function isEmptyGeneratedTombstone(period: ScheduledPayrollPeriod) {
  return period.status === "VOID" && period.autoGenerated === true && !period.notes?.trim();
}

function boundaryKey(period: Pick<ScheduledPayrollPeriod, "scheduleId" | "periodStart" | "periodEnd">) {
  return `${period.scheduleId}:${period.periodStart}:${period.periodEnd}`;
}

/**
 * Merge generated periods without changing an existing locked period. Exact
 * schedule/version/boundary matches are idempotent; an unlocked old-version
 * row can be superseded by a prospective version at the same boundary.
 */
export function mergeGeneratedPayrollPeriods(existing: ScheduledPayrollPeriod[], generated: GeneratedPayrollPeriod[]): ScheduledPayrollPeriod[] {
  const byBoundary = new Map<string, ScheduledPayrollPeriod[]>();
  for (const period of existing) {
    if (isEmptyGeneratedTombstone(period)) continue;
    const key = boundaryKey(period);
    const rows = byBoundary.get(key) || [];
    rows.push({ ...period, periodKey: period.periodKey || periodKey(period.scheduleId, period.scheduleVersionId, period.periodStart, period.periodEnd) });
    byBoundary.set(key, rows);
  }
  for (const candidate of generated) {
    const key = boundaryKey(candidate);
    const rows = byBoundary.get(key) || [];
    const exactIndex = rows.findIndex((row) => row.scheduleVersionId === candidate.scheduleVersionId && row.periodStart === candidate.periodStart && row.periodEnd === candidate.periodEnd);
    if (exactIndex >= 0) {
      const current = rows[exactIndex];
      if (isLockedPeriod(current)) {
        rows[exactIndex] = current;
      } else {
        const merged = { ...current, ...candidate, status: current.status || candidate.status };
        if (current.id !== undefined) merged.id = current.id;
        rows[exactIndex] = merged;
      }
    } else if (rows.some(isHardLockedPeriod) && rows.every((row) => row.status === "VOID") && rows.some((row) => row.scheduleVersionId !== candidate.scheduleVersionId)) {
      // A locked VOID row is an immutable tombstone, not an active calendar
      // boundary. If a later schedule version governs the same recurrence
      // boundary, preserve the tombstone and add the new version's generated
      // period beside it. This is how a reset-era VOID row can no longer block
      // recovery of a valid future period without rewriting history.
      rows.push({ ...candidate });
    } else if (rows.some(isHardLockedPeriod)) {
      // Finalized history wins: the candidate is dropped entirely.
    } else if (rows.some(isLockedPeriod)) {
      // A data-bearing OPEN period at an identical boundary keeps every piece
      // of its identity and data; only the version linkage is corrected to the
      // schedule version that actually governs these dates.
      const current = rows.find((row) => isLockedPeriod(row))!;
      const relinked: ScheduledPayrollPeriod = {
        ...current,
        scheduleVersionId: candidate.scheduleVersionId,
        payDate: candidate.payDate ?? current.payDate,
        periodKey: periodKey(current.scheduleId, candidate.scheduleVersionId, current.periodStart, current.periodEnd),
      };
      rows.splice(0, rows.length, relinked);
    } else {
      // Boundary-equal replacement across schedule versions keeps the existing
      // period identity so runs and entries stay linked to the re-linked period.
      const preservedId = rows.find((row) => row.id)?.id;
      rows.splice(0, rows.length, preservedId ? { ...candidate, id: preservedId } : { ...candidate });
    }
    byBoundary.set(key, rows);
  }
  return [...byBoundary.values()].flat().sort((left, right) => compareDates(left.periodStart, right.periodStart) || compareDates(left.periodEnd, right.periodEnd) || left.scheduleVersionId.localeCompare(right.scheduleVersionId));
}

export const mergePayrollPeriods = mergeGeneratedPayrollPeriods;

function eligiblePeriods<T extends PayrollPeriodSelectionCandidate>(periods: readonly T[]) {
  return periods.filter((period) => period.active !== false && period.status !== "VOID");
}

function currentPeriodOrder(left: PayrollPeriodSelectionCandidate, right: PayrollPeriodSelectionCandidate) {
  return compareDates(right.periodEnd, left.periodEnd)
    || compareDates(right.periodStart, left.periodStart)
    || (right.scheduleVersionId || "").localeCompare(left.scheduleVersionId || "")
    || (left.id || "").localeCompare(right.id || "");
}

function upcomingPeriodOrder(left: PayrollPeriodSelectionCandidate, right: PayrollPeriodSelectionCandidate) {
  return compareDates(left.periodStart, right.periodStart)
    || compareDates(left.periodEnd, right.periodEnd)
    || (left.scheduleVersionId || "").localeCompare(right.scheduleVersionId || "")
    || (left.id || "").localeCompare(right.id || "");
}

function previousPeriodOrder(left: PayrollPeriodSelectionCandidate, right: PayrollPeriodSelectionCandidate) {
  return compareDates(right.periodEnd, left.periodEnd)
    || compareDates(right.periodStart, left.periodStart)
    || (right.scheduleVersionId || "").localeCompare(left.scheduleVersionId || "")
    || (left.id || "").localeCompare(right.id || "");
}

/** Returns the eligible period whose boundaries contain referenceDate, if any. */
export function selectActualPayrollPeriod<T extends PayrollPeriodSelectionCandidate>(periods: readonly T[], referenceDate: DateOnly): T | undefined {
  assertValidDateOnly(referenceDate, "referenceDate");
  return eligiblePeriods(periods)
    .filter((period) => period.periodStart <= referenceDate && period.periodEnd >= referenceDate)
    .sort(currentPeriodOrder)[0];
}

/** Returns the eligible future period with the earliest periodStart. */
export function selectNearestUpcomingPayrollPeriod<T extends PayrollPeriodSelectionCandidate>(periods: readonly T[], referenceDate: DateOnly): T | undefined {
  assertValidDateOnly(referenceDate, "referenceDate");
  return eligiblePeriods(periods)
    .filter((period) => period.periodStart > referenceDate)
    .sort(upcomingPeriodOrder)[0];
}

/** Returns the most recent eligible period that ended before referenceDate. */
export function selectPreviousPayrollPeriod<T extends PayrollPeriodSelectionCandidate>(periods: readonly T[], referenceDate: DateOnly): T | undefined {
  assertValidDateOnly(referenceDate, "referenceDate");
  return eligiblePeriods(periods)
    .filter((period) => period.periodEnd < referenceDate)
    .sort(previousPeriodOrder)[0];
}

/** Selects actual current, then nearest upcoming, then most recent previous. */
export function selectCurrentPayrollPeriod<T extends PayrollPeriodSelectionCandidate>(periods: readonly T[], referenceDate: DateOnly): T | undefined {
  assertValidDateOnly(referenceDate, "referenceDate");
  return selectActualPayrollPeriod(periods, referenceDate)
    || selectNearestUpcomingPayrollPeriod(periods, referenceDate)
    || selectPreviousPayrollPeriod(periods, referenceDate);
}

export const selectCurrentPeriod = selectCurrentPayrollPeriod;

function readJson<T>(key: string, storage: Storage | undefined): T[] {
  if (!storage) return [];
  try {
    const parsed = JSON.parse(storage.getItem(key) || "[]");
    return Array.isArray(parsed) ? parsed as T[] : [];
  } catch {
    return [];
  }
}

function writeJson<T>(key: string, value: T[], storage: Storage | undefined) {
  try { storage?.setItem(key, JSON.stringify(value)); } catch { /* local demo storage can be unavailable or full */ }
}

export function readPayrollSchedulesFromLocal(storage: Storage | undefined = typeof localStorage === "undefined" ? undefined : localStorage) {
  return readJson<PayrollSchedule>(PAYROLL_SCHEDULES_STORAGE_KEY, storage);
}

export function writePayrollSchedulesToLocal(schedules: PayrollSchedule[], storage: Storage | undefined = typeof localStorage === "undefined" ? undefined : localStorage) {
  writeJson(PAYROLL_SCHEDULES_STORAGE_KEY, schedules, storage);
}

export function readPayrollSchedulePeriodsFromLocal(storage: Storage | undefined = typeof localStorage === "undefined" ? undefined : localStorage) {
  return readJson<ScheduledPayrollPeriod>(PAYROLL_SCHEDULE_PERIODS_STORAGE_KEY, storage);
}

export function writePayrollSchedulePeriodsToLocal(periods: ScheduledPayrollPeriod[], storage: Storage | undefined = typeof localStorage === "undefined" ? undefined : localStorage) {
  writeJson(PAYROLL_SCHEDULE_PERIODS_STORAGE_KEY, periods, storage);
}
