import type { AttendanceRecord, LeaveRequest, OvertimeRequest, PayrollAdjustment, PayrollEntry, PayrollPeriod, PayrollProjectAllocation, PayrollRun, WorkEntry } from "../types.ts";
import { generatePayrollPeriodsAroundReference, type PayrollSchedule } from "./payrollSchedule.ts";
import { ensurePayrollPeriodsAndRuns, dateOnly } from "./payrollWorkflow.ts";
import { inspectPayrollIntegrity, isPayrollPeriodDataBearing, isSafeToDeletePayrollPeriod, isSafeToDeletePayrollRun, selectPrimaryPayrollSchedule } from "./payrollIntegrity.ts";
import type { PayrollImportBatch, PayrollImportRow, PayrollImportWorkspaceData } from "./payrollImportPersistence.ts";
import { requireActiveCompanyId } from "./companyContext.ts";
import { supabase } from "./supabase.ts";

export const PAYROLL_MAINTENANCE_ACTIONS = ["REPAIR", "REBUILD_CALENDAR", "RESET_UNAPPROVED"] as const;
export type PayrollMaintenanceAction = (typeof PAYROLL_MAINTENANCE_ACTIONS)[number];
export const RESET_UNAPPROVED_CONFIRMATION = "RESET UNAPPROVED PAYROLL";

export interface PayrollMaintenancePreview {
  action: PayrollMaintenanceAction;
  scheduleFrequency?: string;
  scheduleName?: string;
  referenceDate: string;
  rebuildStart?: string;
  rebuildEnd?: string;
  periodsToDelete: number;
  runsToDelete: number;
  entriesToDelete: number;
  allocationsToDelete: number;
  adjustmentsToDelete: number;
  importBatchesToReopen: number;
  importRowsToReopen: number;
  periodsToCreate: number;
  runsToCreate: number;
  protectedApprovedRuns: number;
  protectedPaidRuns: number;
  protectedLockedPeriods: number;
  protectedDataBearingPeriods: number;
  manualReviewIssues: number;
  eligible: boolean;
  noChanges: boolean;
}

export interface PayrollMaintenanceLocalInput {
  schedules: readonly PayrollSchedule[];
  periods: readonly PayrollPeriod[];
  runs: readonly PayrollRun[];
  entries: readonly PayrollEntry[];
  allocations: readonly PayrollProjectAllocation[];
  adjustments: readonly PayrollAdjustment[];
  workEntries: readonly WorkEntry[];
  importData: PayrollImportWorkspaceData;
  attendanceRecords?: readonly AttendanceRecord[];
  leaveRequests?: readonly LeaveRequest[];
  overtimeRequests?: readonly OvertimeRequest[];
  referenceDate?: string;
}

export interface PayrollMaintenanceLocalPlan {
  preview: PayrollMaintenancePreview;
  periods: PayrollPeriod[];
  runs: PayrollRun[];
  entries: PayrollEntry[];
  allocations: PayrollProjectAllocation[];
  adjustments: PayrollAdjustment[];
  workEntries: WorkEntry[];
  attendanceRecords?: AttendanceRecord[];
  leaveRequests?: LeaveRequest[];
  overtimeRequests?: OvertimeRequest[];
  importData: PayrollImportWorkspaceData;
}

export interface PayrollMaintenanceResult extends PayrollMaintenancePreview {
  applied: boolean;
}

function maintenanceId(prefix: string) {
  return globalThis.crypto?.randomUUID?.() || `local-${prefix}-${Date.now()}-${Math.random().toString(36).slice(2)}`;
}

function numberValue(value: unknown) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
}

function actionLabel(action: PayrollMaintenanceAction) {
  switch (action) {
    case "REPAIR": return "Repair payroll data";
    case "REBUILD_CALENDAR": return "Rebuild payroll calendar";
    case "RESET_UNAPPROVED": return "Reset unapproved payroll";
  }
}

function plannedPeriods(schedule: PayrollSchedule | undefined, referenceDate: string) {
  if (!schedule?.autoGeneratePeriods) return [] as PayrollPeriod[];
  return generatePayrollPeriodsAroundReference(schedule, referenceDate, { previous: 2, next: 2 }).map((period) => ({
    id: `planned:${period.periodKey}`,
    periodStart: period.periodStart,
    periodEnd: period.periodEnd,
    payDate: period.payDate,
    scheduleId: period.scheduleId,
    scheduleVersionId: period.scheduleVersionId,
    autoGenerated: true,
    status: "DRAFT" as const,
    createdAt: "",
    updatedAt: "",
  }));
}

function periodIsResettable(period: PayrollPeriod, runs: readonly PayrollRun[]) {
  return period.status !== "VOID"
    && !period.lockedAt
    && !["APPROVED", "PAID"].includes(period.status)
    && runs.filter((run) => run.periodId === period.id).every((run) => run.status === "DRAFT" || run.status === "CALCULATED");
}

function countProtectedPeriods(periods: readonly PayrollPeriod[], context: { runs: readonly PayrollRun[]; entries: readonly PayrollEntry[]; workEntries: readonly WorkEntry[]; importBatches: readonly PayrollImportBatch[]; adjustments: readonly PayrollAdjustment[] }) {
  return periods.filter((period) => !isSafeToDeletePayrollPeriod(period, context) && (Boolean(period.lockedAt) || ["APPROVED", "PAID", "VOID"].includes(period.status) || isPayrollPeriodDataBearing(period, context))).length;
}

function batchIdsToReopen(
  batches: readonly PayrollImportBatch[],
  rows: readonly PayrollImportRow[],
  targetRunIds: ReadonlySet<string>,
  targetPeriodIds: ReadonlySet<string>,
  targetEntryIds: ReadonlySet<string>,
) {
  return new Set(batches.filter((batch) => batch.status === "COMMITTED" && (
    (batch.committedPayrollRunId && targetRunIds.has(batch.committedPayrollRunId))
    || (batch.committedPayrollPeriodId && targetPeriodIds.has(batch.committedPayrollPeriodId))
    || rows.some((row) => row.batchId === batch.id && row.committedPayrollEntryId && targetEntryIds.has(row.committedPayrollEntryId))
  )).map((batch) => batch.id));
}

function periodBoundary(period: Pick<PayrollPeriod, "scheduleId" | "scheduleVersionId" | "periodStart" | "periodEnd">) {
  return `${period.scheduleId || "legacy"}:${period.scheduleVersionId || "legacy"}:${period.periodStart}:${period.periodEnd}`;
}

function safeRebuildPeriodIds(periods: readonly PayrollPeriod[], desired: readonly PayrollPeriod[], context: Parameters<typeof isSafeToDeletePayrollPeriod>[1]) {
  const desiredKeys = new Set(desired.map(periodBoundary));
  const groups = new Map<string, PayrollPeriod[]>();
  for (const period of periods) groups.set(periodBoundary(period), [...(groups.get(periodBoundary(period)) || []), period]);
  const removable = new Set<string>();
  for (const period of periods) {
    if (!isSafeToDeletePayrollPeriod(period, context)) continue;
    if (period.status === "VOID" || !desiredKeys.has(periodBoundary(period))) removable.add(period.id);
  }
  for (const rows of groups.values()) {
    if (rows.length < 2) continue;
    const keeper = rows.slice().sort((left, right) => Number(!isSafeToDeletePayrollPeriod(left, context)) - Number(!isSafeToDeletePayrollPeriod(right, context)) || (left.createdAt || "").localeCompare(right.createdAt || "") || left.id.localeCompare(right.id))[0]!;
    for (const row of rows) if (row.id !== keeper.id && isSafeToDeletePayrollPeriod(row, context)) removable.add(row.id);
  }
  return removable;
}

function safeRebuildRunIds(runs: readonly PayrollRun[], context: Parameters<typeof isSafeToDeletePayrollRun>[1], removablePeriodIds: ReadonlySet<string>) {
  const groups = new Map<string, PayrollRun[]>();
  for (const run of runs) groups.set(run.periodId, [...(groups.get(run.periodId) || []), run]);
  const removable = new Set<string>();
  for (const rows of groups.values()) {
    const candidates = rows.filter((run) => isSafeToDeletePayrollRun(run, context)).sort((left, right) => (left.status === "DRAFT" ? 0 : 1) - (right.status === "DRAFT" ? 0 : 1) || (left.createdAt || "").localeCompare(right.createdAt || "") || left.id.localeCompare(right.id));
    if (removablePeriodIds.has(rows[0]?.periodId || "")) candidates.forEach((run) => removable.add(run.id));
    else if (candidates.length > 1) candidates.slice(1).forEach((run) => removable.add(run.id));
  }
  return removable;
}export function planLocalPayrollMaintenance(input: PayrollMaintenanceLocalInput, action: PayrollMaintenanceAction): PayrollMaintenanceLocalPlan {
  const referenceDate = input.referenceDate || dateOnly();
  const schedule = selectPrimaryPayrollSchedule(input.schedules);
  const baseContext = { runs: input.runs, entries: input.entries, workEntries: input.workEntries, attendanceRecords: input.attendanceRecords, leaveRequests: input.leaveRequests, overtimeRequests: input.overtimeRequests, importBatches: input.importData.batches, adjustments: input.adjustments };
  const report = inspectPayrollIntegrity(input.schedules, input.periods, input.runs, input.entries, input.allocations, baseContext);
  const desired = plannedPeriods(schedule, referenceDate);
  const desiredStart = desired[0]?.periodStart;
  const desiredEnd = desired.at(-1)?.periodEnd;

  const resettableRunIds = new Set(action === "RESET_UNAPPROVED"
    ? input.runs.filter((run) => (run.status === "DRAFT" || run.status === "CALCULATED") && input.periods.find((period) => period.id === run.periodId) && periodIsResettable(input.periods.find((period) => period.id === run.periodId)!, input.runs)).map((run) => run.id)
    : []);
  const targetEntryIds = new Set(input.entries.filter((entry) => resettableRunIds.has(entry.payrollRunId)).map((entry) => entry.id));
  const targetAllocationIds = new Set(input.allocations.filter((allocation) => targetEntryIds.has(allocation.payrollEntryId)).map((allocation) => allocation.id));
  const targetAdjustmentIds = new Set(input.adjustments.filter((adjustment) => targetEntryIds.has(adjustment.payrollEntryId)).map((adjustment) => adjustment.id));
  const targetPeriodIds = new Set(input.periods.filter((period) => input.runs.some((run) => resettableRunIds.has(run.id) && run.periodId === period.id)).map((period) => period.id));
  const batchesToReopen = action === "RESET_UNAPPROVED" ? batchIdsToReopen(input.importData.batches, input.importData.rows, resettableRunIds, targetPeriodIds, targetEntryIds) : new Set<string>();
  const rowsToReopen = new Set(input.importData.rows.filter((row) => action === "RESET_UNAPPROVED" && (
    batchesToReopen.has(row.batchId) || (row.committedPayrollEntryId && targetEntryIds.has(row.committedPayrollEntryId))
  ) && row.status === "COMMITTED").map((row) => row.id));

  let periods = input.periods.slice();
  let runs = input.runs.slice();
  let entries = input.entries.slice();
  let allocations = input.allocations.slice();
  let adjustments = input.adjustments.slice();
  let workEntries = input.workEntries.slice();
  let importData: PayrollImportWorkspaceData = {
    ...input.importData,
    batches: input.importData.batches.slice(),
    rows: input.importData.rows.slice(),
  };

  if (action === "RESET_UNAPPROVED") {
    allocations = allocations.filter((allocation) => !targetAllocationIds.has(allocation.id));
    adjustments = adjustments.filter((adjustment) => !targetAdjustmentIds.has(adjustment.id));
    entries = entries.filter((entry) => !targetEntryIds.has(entry.id));
    runs = runs.filter((run) => !resettableRunIds.has(run.id));
    importData = {
      ...importData,
      batches: importData.batches.map((batch) => batchesToReopen.has(batch.id) ? { ...batch, status: "VALIDATED", committedPayrollPeriodId: undefined, committedPayrollRunId: undefined, committedAt: undefined, updatedAt: new Date().toISOString() } : batch),
      rows: importData.rows.map((row) => rowsToReopen.has(row.id) ? { ...row, status: "READY", committedPayrollEntryId: undefined, updatedAt: new Date().toISOString() } : row),
    };
  }

  const cleanupContext = { runs, entries, workEntries, attendanceRecords: input.attendanceRecords, leaveRequests: input.leaveRequests, overtimeRequests: input.overtimeRequests, importBatches: importData.batches, adjustments };
  const disposablePeriodIds = action === "RESET_UNAPPROVED"
    ? new Set(periods.filter((period) => isSafeToDeletePayrollPeriod(period, cleanupContext) || (periodIsResettable(period, input.runs) && isSafeToDeletePayrollPeriod({ ...period, status: period.status === "CALCULATED" ? "OPEN" : period.status }, cleanupContext))).map((period) => period.id))
    : safeRebuildPeriodIds(periods, desired, baseContext);
  const disposableRunIds = action === "RESET_UNAPPROVED"
    ? new Set(runs.filter((run) => disposablePeriodIds.has(run.periodId) && isSafeToDeletePayrollRun(run, cleanupContext)).map((run) => run.id))
    : safeRebuildRunIds(runs, cleanupContext, disposablePeriodIds);
  runs = runs.filter((run) => !disposableRunIds.has(run.id));
  periods = periods.filter((period) => !disposablePeriodIds.has(period.id));
  const removedPeriodIds = new Set(disposablePeriodIds);
  workEntries = workEntries.map((entry) => removedPeriodIds.has(entry.periodId || "") ? { ...entry, periodId: undefined } : entry);

  const ensured = ensurePayrollPeriodsAndRuns({
    schedules: schedule ? [schedule] : [],
    periods,
    runs,
    entries,
    workEntries,
    importBatches: importData.batches,
    adjustments,
    attendanceRecords: input.attendanceRecords,
    leaveRequests: input.leaveRequests,
    overtimeRequests: input.overtimeRequests,
    referenceDate,
    previous: 2,
    next: 2,
  });
  periods = ensured.periods;
  runs = ensured.runs;

  const protectedContext = { runs: input.runs, entries: input.entries, workEntries: input.workEntries, attendanceRecords: input.attendanceRecords, leaveRequests: input.leaveRequests, overtimeRequests: input.overtimeRequests, importBatches: input.importData.batches, adjustments: input.adjustments };
  const periodsToDelete = disposablePeriodIds.size;
  const runsToDelete = resettableRunIds.size + [...disposableRunIds].filter((id) => !resettableRunIds.has(id)).length;
  const entriesToDelete = targetEntryIds.size;
  const allocationsToDelete = targetAllocationIds.size;
  const adjustmentsToDelete = targetAdjustmentIds.size;
  const noChanges = periodsToDelete + runsToDelete + entriesToDelete + allocationsToDelete + adjustmentsToDelete + batchesToReopen.size + rowsToReopen.size + ensured.createdPeriods.length + ensured.createdRuns.length === 0;
  const manualReviewIssues = report.issues.filter((issue) => !issue.safeToRepair).length;
  const preview: PayrollMaintenancePreview = {
    action,
    scheduleFrequency: schedule?.frequency,
    scheduleName: schedule?.name || (schedule ? "Payroll schedule" : undefined),
    referenceDate,
    rebuildStart: desiredStart,
    rebuildEnd: desiredEnd,
    periodsToDelete,
    runsToDelete,
    entriesToDelete,
    allocationsToDelete,
    adjustmentsToDelete,
    importBatchesToReopen: batchesToReopen.size,
    importRowsToReopen: rowsToReopen.size,
    periodsToCreate: ensured.createdPeriods.length,
    runsToCreate: ensured.createdRuns.length,
    protectedApprovedRuns: input.runs.filter((run) => run.status === "APPROVED").length,
    protectedPaidRuns: input.runs.filter((run) => run.status === "PAID").length,
    protectedLockedPeriods: countProtectedPeriods(input.periods.filter((period) => Boolean(period.lockedAt) || ["APPROVED", "PAID", "VOID"].includes(period.status)), protectedContext),
    protectedDataBearingPeriods: input.periods.filter((period) => isPayrollPeriodDataBearing(period, protectedContext)).length,
    manualReviewIssues,
    eligible: Boolean(schedule) && !noChanges,
    noChanges,
  };
  return { preview, periods, runs, entries, allocations, adjustments, workEntries, attendanceRecords: input.attendanceRecords ? [...input.attendanceRecords] : undefined, leaveRequests: input.leaveRequests ? [...input.leaveRequests] : undefined, overtimeRequests: input.overtimeRequests ? [...input.overtimeRequests] : undefined, importData };
}

export function localMaintenanceResult(plan: PayrollMaintenanceLocalPlan): PayrollMaintenanceResult {
  return { ...plan.preview, applied: true };
}

function objectResult(value: unknown): Record<string, unknown> {
  if (value && typeof value === "object" && !Array.isArray(value)) return value as Record<string, unknown>;
  if (Array.isArray(value) && value[0] && typeof value[0] === "object") return value[0] as Record<string, unknown>;
  return {};
}

function actionValue(value: unknown): PayrollMaintenanceAction {
  return PAYROLL_MAINTENANCE_ACTIONS.includes(value as PayrollMaintenanceAction) ? value as PayrollMaintenanceAction : "REPAIR";
}

export function payrollMaintenancePreviewFromResult(value: unknown): PayrollMaintenancePreview {
  const result = objectResult(value);
  const action = actionValue(result.action);
  return {
    action,
    scheduleFrequency: typeof result.scheduleFrequency === "string" ? result.scheduleFrequency : undefined,
    scheduleName: typeof result.scheduleName === "string" ? result.scheduleName : undefined,
    referenceDate: typeof result.referenceDate === "string" ? result.referenceDate : dateOnly(),
    rebuildStart: typeof result.rebuildStart === "string" ? result.rebuildStart : undefined,
    rebuildEnd: typeof result.rebuildEnd === "string" ? result.rebuildEnd : undefined,
    periodsToDelete: numberValue(result.periodsToDelete),
    runsToDelete: numberValue(result.runsToDelete),
    entriesToDelete: numberValue(result.entriesToDelete),
    allocationsToDelete: numberValue(result.allocationsToDelete),
    adjustmentsToDelete: numberValue(result.adjustmentsToDelete),
    importBatchesToReopen: numberValue(result.importBatchesToReopen),
    importRowsToReopen: numberValue(result.importRowsToReopen),
    periodsToCreate: numberValue(result.periodsToCreate),
    runsToCreate: numberValue(result.runsToCreate),
    protectedApprovedRuns: numberValue(result.protectedApprovedRuns),
    protectedPaidRuns: numberValue(result.protectedPaidRuns),
    protectedLockedPeriods: numberValue(result.protectedLockedPeriods),
    protectedDataBearingPeriods: numberValue(result.protectedDataBearingPeriods),
    manualReviewIssues: numberValue(result.manualReviewIssues),
    eligible: result.eligible !== false,
    noChanges: result.noChanges === true,
  };
}

export async function previewPayrollMaintenance(action: PayrollMaintenanceAction, referenceDate = dateOnly(), companyId = requireActiveCompanyId()): Promise<PayrollMaintenancePreview> {
  if (!supabase) throw new Error("Payroll maintenance requires a connected company workspace.");
  const { data, error } = await supabase.rpc("preview_payroll_maintenance", {
    p_company_id: companyId,
    p_action: action,
    p_reference_date: referenceDate,
  });
  if (error) throw error;
  return payrollMaintenancePreviewFromResult(data);
}

export async function applyPayrollMaintenance(action: PayrollMaintenanceAction, referenceDate = dateOnly(), confirmation?: string, companyId = requireActiveCompanyId()): Promise<PayrollMaintenanceResult> {
  if (!supabase) throw new Error("Payroll maintenance requires a connected company workspace.");
  const { data, error } = await supabase.rpc("apply_payroll_maintenance", {
    p_company_id: companyId,
    p_action: action,
    p_reference_date: referenceDate,
    p_confirmation: confirmation || null,
  });
  if (error) throw error;
  return { ...payrollMaintenancePreviewFromResult(data), applied: true };
}

export { actionLabel };
