import type {
  PayrollAdjustment,
  Department,
  PayrollEntry,
  PayrollPeriod,
  PayrollProjectAllocation,
  PayrollRun,
  PayrollRunStatus,
  PayrollValidationResult,
  ProjectWorkerAssignment,
  Worker,
  WorkEntry,
} from "../types.ts";
import type { PayrollSchedule, PayrollScheduleVersion } from "./payrollSchedule.ts";
import { readPayrollSchedulesFromLocal, writePayrollSchedulesToLocal } from "./payrollSchedule.ts";
import type { RecurringPayrollComponent, WorkerCompensationProfile } from "./payrollAutomation.ts";
import { supabase } from "./supabase.ts";

const WORKERS_STORAGE_KEY = "engineering_workers";
const ASSIGNMENTS_STORAGE_KEY = "engineering_project_worker_assignments";
const PERIODS_STORAGE_KEY = "engineering_payroll_periods";
const RUNS_STORAGE_KEY = "engineering_payroll_runs";
const ALLOCATIONS_STORAGE_KEY = "engineering_payroll_allocations";
const WORK_ENTRIES_STORAGE_KEY = "engineering_work_entries";
const ENTRIES_STORAGE_KEY = "engineering_payroll_entries";
const ADJUSTMENTS_STORAGE_KEY = "engineering_payroll_adjustments";
const DEPARTMENTS_STORAGE_KEY = "engineering_departments";
const COMPENSATION_PROFILES_STORAGE_KEY = "engineering_worker_compensation_profiles";
const RECURRING_COMPONENTS_STORAGE_KEY = "engineering_recurring_payroll_components";

function id(prefix: string) {
  return globalThis.crypto?.randomUUID?.() || `local-${prefix}-${Date.now()}-${Math.random().toString(36).slice(2)}`;
}
function persistedId(value: string | undefined, prefix: string) { return value && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value) ? value : id(prefix); }

function text(value: unknown) { return value === null || value === undefined ? undefined : String(value); }
function numberValue(value: unknown) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; }
function bool(value: unknown, fallback = true) { return value === null || value === undefined ? fallback : Boolean(value); }
function round(value: number) { return Math.round((Number(value) || 0) * 100) / 100; }

function workerFromRow(row: Record<string, unknown>): Worker {
  return {
    id: String(row.id), userId: text(row.user_id), authUserId: text(row.auth_user_id), employeeCode: String(row.employee_code || ""),
    firstName: String(row.first_name || ""), middleName: text(row.middle_name), lastName: String(row.last_name || ""),
    displayName: String(row.display_name || [row.first_name, row.last_name].filter(Boolean).join(" ")),
    employmentType: String(row.employment_type || "OTHER") as Worker["employmentType"], employmentStatus: text(row.employment_status) as Worker["employmentStatus"], jobTitle: text(row.job_title), department: text(row.department), departmentId: text(row.department_id), managerWorkerId: text(row.manager_worker_id),
    defaultPayType: String(row.default_pay_type || "MONTHLY") as Worker["defaultPayType"], defaultRate: numberValue(row.default_rate),
    active: bool(row.active), hireDate: text(row.hire_date), endDate: text(row.end_date), workingDays: Array.isArray(row.working_days) ? row.working_days.map(String) : undefined, workingHoursStart: text(row.working_hours_start), workingHoursEnd: text(row.working_hours_end), notes: text(row.notes),
    createdAt: String(row.created_at || new Date().toISOString()), updatedAt: String(row.updated_at || new Date().toISOString()), archivedAt: text(row.archived_at),
  };
}

function assignmentFromRow(row: Record<string, unknown>): ProjectWorkerAssignment {
  return {
    id: String(row.id), workerId: String(row.worker_id), projectId: String(row.project_id), startDate: String(row.start_date || ""), endDate: text(row.end_date),
    payType: text(row.pay_type) as ProjectWorkerAssignment["payType"], rate: row.rate === null ? undefined : numberValue(row.rate), roleOnProject: text(row.role_on_project), active: bool(row.active), notes: text(row.notes),
  };
}

function periodFromRow(row: Record<string, unknown>): PayrollPeriod {
  return {
    id: String(row.id), userId: text(row.user_id), periodStart: String(row.period_start || ""), periodEnd: String(row.period_end || ""), payDate: text(row.pay_date),
    scheduleId: text(row.schedule_id), scheduleVersionId: text(row.schedule_version_id), autoGenerated: row.auto_generated === undefined ? undefined : bool(row.auto_generated, false), lockedAt: text(row.locked_at),
    status: String(row.status || "DRAFT") as PayrollPeriod["status"], notes: text(row.notes), createdAt: String(row.created_at || new Date().toISOString()), updatedAt: String(row.updated_at || new Date().toISOString()),
  };
}

function runFromRow(row: Record<string, unknown>): PayrollRun {
  return {
    id: String(row.id), userId: text(row.user_id), periodId: String(row.period_id), importBatchId: text(row.import_batch_id), status: String(row.status || "DRAFT") as PayrollRun["status"],
    createdAt: String(row.created_at || new Date().toISOString()), calculatedAt: text(row.calculated_at), approvedAt: text(row.approved_at), paidAt: text(row.paid_at), notes: text(row.notes),
  };
}

function entryFromRow(row: Record<string, unknown>): PayrollEntry {
  return {
    id: String(row.id), payrollRunId: String(row.payroll_run_id), workerId: String(row.worker_id), basePay: numberValue(row.base_pay), regularPay: numberValue(row.regular_pay),
    overtimePay: numberValue(row.overtime_pay), allowances: numberValue(row.allowances), otherEarnings: numberValue(row.other_earnings), grossPay: numberValue(row.gross_pay), deductions: numberValue(row.deductions), otherDeductions: numberValue(row.other_deductions), employerCosts: numberValue(row.employer_costs), netPay: numberValue(row.net_pay),
    projectAllocatedCost: numberValue(row.project_allocated_cost), costContext: row.cost_context && typeof row.cost_context === "object" ? row.cost_context as PayrollEntry["costContext"] : undefined, importRowId: text(row.import_row_id), calculationSnapshot: (row.calculation_snapshot || {}) as Record<string, unknown>, createdAt: text(row.created_at),
  };
}

function allocationFromRow(row: Record<string, unknown>): PayrollProjectAllocation {
  return { id: String(row.id), payrollEntryId: String(row.payroll_entry_id), projectId: String(row.project_id), allocationAmount: numberValue(row.allocation_amount), allocationPercentage: row.allocation_percentage === null ? undefined : numberValue(row.allocation_percentage), source: String(row.source || "MANUAL") as PayrollProjectAllocation["source"] };
}

function workEntryFromRow(row: Record<string, unknown>): WorkEntry {
  return { id: String(row.id), workerId: String(row.worker_id), projectId: String(row.project_id), periodId: text(row.period_id), workDate: String(row.work_date || ""), regularHours: numberValue(row.regular_hours), overtimeHours: numberValue(row.overtime_hours), daysWorked: numberValue(row.days_worked), rate: numberValue(row.rate), overtimeRate: row.overtime_rate === null ? undefined : numberValue(row.overtime_rate), description: text(row.description), notes: text(row.notes), status: String(row.status || "DRAFT") as WorkEntry["status"] };
}

function adjustmentFromRow(row: Record<string, unknown>): PayrollAdjustment {
  return { id: String(row.id), payrollEntryId: String(row.payroll_entry_id), type: String(row.type) as PayrollAdjustment["type"], code: text(row.code), description: text(row.description), amount: numberValue(row.amount) };
}

function departmentFromRow(row: Record<string, unknown>): Department {
  return { id: String(row.id), userId: text(row.user_id), name: String(row.name || ""), description: text(row.description), managerWorkerId: text(row.manager_worker_id), active: bool(row.active), createdAt: String(row.created_at || new Date().toISOString()), updatedAt: String(row.updated_at || new Date().toISOString()), archivedAt: text(row.archived_at) };
}

function objectValue(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function scheduleConfiguration(row: Record<string, unknown>) {
  const config = objectValue(row.configuration);
  return {
    frequency: String(row.frequency || config.frequency || "SEMI_MONTHLY") as PayrollSchedule["frequency"],
    weekEndDay: config.weekEndDay === undefined ? undefined : Number(config.weekEndDay) as PayrollSchedule["weekEndDay"],
    anchorPeriodEnd: text(config.anchorPeriodEnd), customCutoffDay: config.customCutoffDay === undefined ? undefined : numberValue(config.customCutoffDay),
    customPeriodLengthDays: config.customPeriodLengthDays === undefined ? undefined : numberValue(config.customPeriodLengthDays),
    customPeriodStartDay: config.customPeriodStartDay === undefined ? undefined : numberValue(config.customPeriodStartDay),
    customPeriodEndDay: config.customPeriodEndDay === undefined ? undefined : numberValue(config.customPeriodEndDay),
    autoSelectCurrentPeriod: config.autoSelectCurrentPeriod === undefined ? undefined : bool(config.autoSelectCurrentPeriod),
    automationMode: String(config.automationMode || "ASSISTED") as PayrollSchedule["automationMode"],
  };
}
function scheduleVersionFromRow(row: Record<string, unknown>): PayrollScheduleVersion {
  return { id: String(row.id), scheduleId: String(row.schedule_id), version: numberValue(row.version), effectiveFrom: String(row.effective_from || ""), effectiveTo: text(row.effective_to), ...scheduleConfiguration(row), payDateRule: objectValue(row.pay_date_rule) as unknown as PayrollScheduleVersion["payDateRule"], autoGeneratePeriods: bool(row.auto_generate_periods), autoCalculate: bool(row.auto_calculate, false), autoCreateRuns: bool(row.auto_calculate, false), active: bool(row.active), createdAt: text(row.created_at), updatedAt: text(row.updated_at) };
}
function scheduleFromRow(row: Record<string, unknown>, versionRows: Record<string, unknown>[]): PayrollSchedule {
  return { id: String(row.id), userId: text(row.user_id), name: text(row.name), effectiveFrom: String(row.effective_from || ""), ...scheduleConfiguration(row), payDateRule: objectValue(row.pay_date_rule) as unknown as PayrollSchedule["payDateRule"], autoGeneratePeriods: bool(row.auto_generate_periods), autoCalculate: bool(row.auto_calculate, false), autoCreateRuns: bool(row.auto_calculate, false), active: bool(row.active), versions: versionRows.filter((version) => String(version.schedule_id) === String(row.id)).map(scheduleVersionFromRow), createdAt: text(row.created_at), updatedAt: text(row.updated_at) };
}
function profileFromRow(row: Record<string, unknown>): WorkerCompensationProfile {
  return { id: text(row.id), workerId: String(row.worker_id), effectiveFrom: String(row.effective_from || ""), effectiveTo: text(row.effective_to), frequency: String(row.frequency || "MONTHLY") as WorkerCompensationProfile["frequency"], rate: numberValue(row.rate), defaultLaborContext: String(row.default_labor_context || "UNALLOCATED_REVIEW") as WorkerCompensationProfile["defaultLaborContext"], defaultProjectId: text(row.default_project_id) };
}
function componentFromRow(row: Record<string, unknown>): RecurringPayrollComponent {
  return { id: String(row.id), workerId: String(row.worker_id), type: String(row.type || "EARNING") as RecurringPayrollComponent["type"], name: text(row.name), amount: row.amount === null ? undefined : numberValue(row.amount), rate: row.rate === null ? undefined : numberValue(row.rate), effectiveFrom: String(row.effective_from || ""), effectiveTo: text(row.effective_to), active: bool(row.active), code: text(row.code) } as RecurringPayrollComponent;
}

export interface PayrollWorkspaceData {
  departments: Department[];
  workers: Worker[];
  assignments: ProjectWorkerAssignment[];
  periods: PayrollPeriod[];
  runs: PayrollRun[];
  entries: PayrollEntry[];
  allocations: PayrollProjectAllocation[];
  workEntries: WorkEntry[];
  adjustments: PayrollAdjustment[];
  schedules?: PayrollSchedule[];
  compensationProfiles?: WorkerCompensationProfile[];
  recurringComponents?: RecurringPayrollComponent[];
}

async function currentUserId() {
  if (!supabase) return null;
  const { data } = await supabase.auth.getUser();
  return data.user?.id || null;
}

function localJson<T>(key: string, storage: Storage | undefined): T[] {
  if (!storage) return [];
  try { return JSON.parse(storage.getItem(key) || "[]") as T[]; } catch { return []; }
}

function writeJson<T>(key: string, value: T[], storage: Storage | undefined) {
  try { storage?.setItem(key, JSON.stringify(value)); } catch { /* local demo storage can be full */ }
}

export function readPayrollWorkspaceFromLocal(storage: Storage | undefined = typeof localStorage === "undefined" ? undefined : localStorage): PayrollWorkspaceData {
  return {
    departments: localJson<Department>(DEPARTMENTS_STORAGE_KEY, storage), workers: localJson<Worker>(WORKERS_STORAGE_KEY, storage), assignments: localJson<ProjectWorkerAssignment>(ASSIGNMENTS_STORAGE_KEY, storage), periods: localJson<PayrollPeriod>(PERIODS_STORAGE_KEY, storage),
    runs: localJson<PayrollRun>(RUNS_STORAGE_KEY, storage), entries: localJson<PayrollEntry>(ENTRIES_STORAGE_KEY, storage), allocations: localJson<PayrollProjectAllocation>(ALLOCATIONS_STORAGE_KEY, storage), workEntries: localJson<WorkEntry>(WORK_ENTRIES_STORAGE_KEY, storage), adjustments: localJson<PayrollAdjustment>(ADJUSTMENTS_STORAGE_KEY, storage),
    schedules: readPayrollSchedulesFromLocal(storage), compensationProfiles: localJson<WorkerCompensationProfile>(COMPENSATION_PROFILES_STORAGE_KEY, storage), recurringComponents: localJson<RecurringPayrollComponent>(RECURRING_COMPONENTS_STORAGE_KEY, storage),
  };
}

export function writePayrollWorkspaceToLocal(data: PayrollWorkspaceData, storage: Storage | undefined = typeof localStorage === "undefined" ? undefined : localStorage) {
  writeJson(DEPARTMENTS_STORAGE_KEY, data.departments, storage); writeJson(WORKERS_STORAGE_KEY, data.workers, storage); writeJson(ASSIGNMENTS_STORAGE_KEY, data.assignments, storage); writeJson(PERIODS_STORAGE_KEY, data.periods, storage); writeJson(RUNS_STORAGE_KEY, data.runs, storage); writeJson(ENTRIES_STORAGE_KEY, data.entries, storage); writeJson(ALLOCATIONS_STORAGE_KEY, data.allocations, storage); writeJson(WORK_ENTRIES_STORAGE_KEY, data.workEntries, storage); writeJson(ADJUSTMENTS_STORAGE_KEY, data.adjustments, storage); writePayrollSchedulesToLocal(data.schedules || [], storage); writeJson(COMPENSATION_PROFILES_STORAGE_KEY, data.compensationProfiles || [], storage); writeJson(RECURRING_COMPONENTS_STORAGE_KEY, data.recurringComponents || [], storage);
}

export function createLocalWorker(input: Omit<Worker, "id" | "createdAt" | "updatedAt">): Worker { const now = new Date().toISOString(); return { ...input, id: id("worker"), createdAt: now, updatedAt: now }; }
export function createLocalDepartment(input: Omit<Department, "id" | "createdAt" | "updatedAt">): Department { const now = new Date().toISOString(); return { ...input, id: id("department"), createdAt: now, updatedAt: now }; }
export function createLocalPeriod(input: Omit<PayrollPeriod, "id" | "createdAt" | "updatedAt">): PayrollPeriod { const now = new Date().toISOString(); return { ...input, id: id("period"), createdAt: now, updatedAt: now }; }
export function createLocalWorkEntry(input: Omit<WorkEntry, "id">): WorkEntry { return { ...input, id: id("work") }; }
export function createLocalAssignment(input: Omit<ProjectWorkerAssignment, "id">): ProjectWorkerAssignment { return { ...input, id: id("assignment") }; }

export function calculateMonthlyProjectAllocations(totalPay: number, allocations: Array<{ projectId: string; percentage: number }>): Array<{ projectId: string; allocationAmount: number; allocationPercentage: number }> {
  const valid = allocations.filter((item) => item.projectId && item.percentage > 0);
  const totalPercentage = valid.reduce((sum, item) => sum + item.percentage, 0);
  if (totalPercentage > 100.01) throw new Error("Payroll project allocation exceeds 100%.");
  let assigned = 0;
  return valid.map((item, index) => {
    const amount = Math.abs(totalPercentage - 100) <= 0.01 && index === valid.length - 1 ? round(totalPay - assigned) : round(totalPay * item.percentage / 100);
    assigned += amount;
    return { projectId: item.projectId, allocationAmount: amount, allocationPercentage: item.percentage };
  });
}

export function calculateWorkEntryCost(entry: Pick<WorkEntry, "regularHours" | "overtimeHours" | "daysWorked" | "rate" | "overtimeRate">, payType: Worker["defaultPayType"]) {
  const regular = payType === "HOURLY" ? (Number(entry.regularHours) || 0) * (Number(entry.rate) || 0) : payType === "DAILY" ? (Number(entry.daysWorked) || 0) * (Number(entry.rate) || 0) : 0;
  const overtime = (Number(entry.overtimeHours) || 0) * (Number(entry.overtimeRate ?? entry.rate) || 0);
  return round(regular + overtime);
}

export function payrollStatusIsConfirmed(status: string) { return status === "APPROVED" || status === "PAID"; }

const PAYROLL_RUN_TRANSITIONS: Readonly<Record<PayrollRunStatus, readonly PayrollRunStatus[]>> = {
  DRAFT: ["CALCULATED", "VOID"],
  CALCULATED: ["APPROVED", "VOID"],
  APPROVED: ["PAID", "VOID"],
  PAID: [],
  VOID: [],
};

export function canTransitionPayrollRun(from: PayrollRunStatus, to: PayrollRunStatus) {
  return from === to || PAYROLL_RUN_TRANSITIONS[from].includes(to);
}

export function validatePayrollRunApproval(run: Pick<PayrollRun, "id" | "status">, entries: PayrollEntry[]): PayrollValidationResult {
  const issues: string[] = [];
  if (run.status !== "CALCULATED") issues.push("Payroll run must be CALCULATED before approval.");
  if (!entries.length) issues.push("Payroll run approval requires at least one payroll entry.");

  const workerIds = new Set<string>();
  for (const entry of entries) {
    if (entry.payrollRunId !== run.id) issues.push(`Payroll entry ${entry.id} belongs to a different payroll run.`);
    if (!entry.workerId) issues.push(`Payroll entry ${entry.id} is missing a worker.`);
    if (workerIds.has(entry.workerId)) issues.push(`Worker ${entry.workerId} appears more than once in the payroll run.`);
    workerIds.add(entry.workerId);
    const snapshot = entry.calculationSnapshot;
    if (!snapshot || Array.isArray(snapshot) || typeof snapshot !== "object" || Object.keys(snapshot).length === 0) {
      issues.push(`Payroll entry ${entry.id} requires a non-empty calculation snapshot.`);
    }
    for (const [field, value] of Object.entries({
      basePay: entry.basePay,
      regularPay: entry.regularPay,
      overtimePay: entry.overtimePay,
      allowances: entry.allowances,
      grossPay: entry.grossPay,
      deductions: entry.deductions,
      netPay: entry.netPay,
      projectAllocatedCost: entry.projectAllocatedCost,
    })) {
      if (!Number.isFinite(value) || value < 0) issues.push(`Payroll entry ${entry.id} has an invalid ${field}.`);
    }
  }
  return { valid: issues.length === 0, issues };
}

export function validatePayrollAllocations(entry: Pick<PayrollEntry, "projectAllocatedCost">, allocations: PayrollProjectAllocation[]): PayrollValidationResult {
  const issues: string[] = [];
  const totalAmount = allocations.reduce((sum, allocation) => sum + (Number(allocation.allocationAmount) || 0), 0);
  const totalPercentage = allocations.reduce((sum, allocation) => sum + (Number(allocation.allocationPercentage) || 0), 0);
  if (totalPercentage > 100.01) issues.push("Payroll allocation percentages exceed 100%.");
  if (totalAmount > (Number(entry.projectAllocatedCost) || 0) + 0.01) issues.push("Payroll allocation amounts exceed the entry project cost.");
  for (const allocation of allocations) {
    if (allocation.allocationPercentage !== undefined && (!Number.isFinite(allocation.allocationPercentage) || allocation.allocationPercentage < 0 || allocation.allocationPercentage > 100)) issues.push(`Allocation ${allocation.id} has a percentage outside 0–100.`);
    if (!Number.isFinite(allocation.allocationAmount) || allocation.allocationAmount < 0) issues.push(`Allocation ${allocation.id} has an invalid amount.`);
  }
  return { valid: issues.length === 0, issues };
}

export async function loadPayrollWorkspaceFromSupabase(): Promise<PayrollWorkspaceData> {
  const userId = await currentUserId();
  if (!supabase || !userId) return { departments: [], workers: [], assignments: [], periods: [], runs: [], entries: [], allocations: [], workEntries: [], adjustments: [] };
  const [departments, workers, assignments, periods, runs, entries, allocations, workEntries, adjustments] = await Promise.all([
    supabase.from("departments").select("*").is("archived_at", null).order("name"),
    supabase.from("workers").select("*").is("archived_at", null).order("last_name"),
    supabase.from("project_worker_assignments").select("*").order("start_date", { ascending: false }),
    supabase.from("payroll_periods").select("*").order("period_end", { ascending: false }),
    supabase.from("payroll_runs").select("*").order("created_at", { ascending: false }),
    supabase.from("payroll_entries").select("*"),
    supabase.from("payroll_project_allocations").select("*"),
    supabase.from("work_entries").select("*").order("work_date", { ascending: false }),
    supabase.from("payroll_adjustments").select("*"),
  ]);
  for (const result of [departments, workers, assignments, periods, runs, entries, allocations, workEntries, adjustments]) if (result.error) throw result.error;
  return {
    departments: (departments.data || []).map((row) => departmentFromRow(row as Record<string, unknown>)),
    workers: (workers.data || []).map((row) => workerFromRow(row as Record<string, unknown>)),
    assignments: (assignments.data || []).map((row) => assignmentFromRow(row as Record<string, unknown>)),
    periods: (periods.data || []).map((row) => periodFromRow(row as Record<string, unknown>)),
    runs: (runs.data || []).map((row) => runFromRow(row as Record<string, unknown>)),
    entries: (entries.data || []).map((row) => entryFromRow(row as Record<string, unknown>)),
    allocations: (allocations.data || []).map((row) => allocationFromRow(row as Record<string, unknown>)),
    workEntries: (workEntries.data || []).map((row) => workEntryFromRow(row as Record<string, unknown>)),
    adjustments: (adjustments.data || []).map((row) => adjustmentFromRow(row as Record<string, unknown>)),
  };
}

export async function saveDepartmentToSupabase(department: Department) {
  const userId = await currentUserId();
  if (!supabase || !userId) throw new Error("Sign in before saving departments.");
  const { data, error } = await supabase.from("departments").upsert({ id: persistedId(department.id, "department"), user_id: userId, name: department.name.trim(), description: department.description || null, manager_worker_id: department.managerWorkerId || null, active: department.active, archived_at: department.archivedAt || null, updated_at: new Date().toISOString() }).select("*").single();
  if (error) throw error;
  return departmentFromRow(data as Record<string, unknown>);
}

export async function saveWorkerToSupabase(worker: Worker) {
  const userId = await currentUserId();
  if (!supabase || !userId) throw new Error("Sign in before saving workers.");
  const { data, error } = await supabase.from("workers").upsert({ id: persistedId(worker.id, "worker"), user_id: userId, auth_user_id: worker.authUserId || null, employee_code: worker.employeeCode, first_name: worker.firstName, middle_name: worker.middleName || null, last_name: worker.lastName, display_name: worker.displayName, employment_type: worker.employmentType, employment_status: worker.employmentStatus || (worker.active ? "ACTIVE" : "INACTIVE"), job_title: worker.jobTitle || null, department: worker.department || null, department_id: worker.departmentId || null, manager_worker_id: worker.managerWorkerId || null, default_pay_type: worker.defaultPayType, default_rate: worker.defaultRate, active: worker.active, hire_date: worker.hireDate || null, end_date: worker.endDate || null, working_days: worker.workingDays || null, working_hours_start: worker.workingHoursStart || null, working_hours_end: worker.workingHoursEnd || null, notes: worker.notes || null, archived_at: worker.archivedAt || null, updated_at: new Date().toISOString() }).select("*").single();
  if (error) throw error;
  return workerFromRow(data as Record<string, unknown>);
}

export async function saveAssignmentToSupabase(assignment: ProjectWorkerAssignment) {
  const userId = await currentUserId();
  if (!supabase || !userId) throw new Error("Sign in before assigning workers.");
  const { data, error } = await supabase.from("project_worker_assignments").upsert({ id: persistedId(assignment.id, "assignment"), user_id: userId, worker_id: assignment.workerId, project_id: assignment.projectId, start_date: assignment.startDate, end_date: assignment.endDate || null, pay_type: assignment.payType || null, rate: assignment.rate ?? null, role_on_project: assignment.roleOnProject || null, active: assignment.active, notes: assignment.notes || null, updated_at: new Date().toISOString() }).select("*").single();
  if (error) throw error;
  return assignmentFromRow(data as Record<string, unknown>);
}

function scheduleConfigurationForPersistence(schedule: PayrollSchedule | PayrollScheduleVersion) {
  return {
    weekEndDay: schedule.weekEndDay ?? null,
    anchorPeriodEnd: schedule.anchorPeriodEnd || null,
    customCutoffDay: schedule.customCutoffDay ?? null,
    customPeriodLengthDays: schedule.customPeriodLengthDays ?? null,
    customPeriodStartDay: schedule.customPeriodStartDay ?? null,
    customPeriodEndDay: schedule.customPeriodEndDay ?? null,
    automationMode: schedule.automationMode || null,
  };
}
function defaultScheduleVersion(schedule: PayrollSchedule): PayrollScheduleVersion {
  return {
    id: `${schedule.id}:v1`, scheduleId: schedule.id, version: 1, effectiveFrom: schedule.effectiveFrom, frequency: schedule.frequency,
    weekEndDay: schedule.weekEndDay, anchorPeriodEnd: schedule.anchorPeriodEnd, customCutoffDay: schedule.customCutoffDay,
    customPeriodLengthDays: schedule.customPeriodLengthDays, customPeriodStartDay: schedule.customPeriodStartDay, customPeriodEndDay: schedule.customPeriodEndDay,
    payDateRule: schedule.payDateRule, autoGeneratePeriods: schedule.autoGeneratePeriods, autoCalculate: schedule.autoCalculate, autoCreateRuns: schedule.autoCreateRuns, autoSelectCurrentPeriod: schedule.autoSelectCurrentPeriod, automationMode: schedule.automationMode, active: schedule.active,
  };
}

export async function savePayrollScheduleToSupabase(schedule: PayrollSchedule) {
  const userId = await currentUserId();
  if (!supabase || !userId) throw new Error("Sign in before saving payroll schedules.");
  const scheduleId = persistedId(schedule.id, "schedule");
  const scheduleRow = { id: scheduleId, user_id: userId, name: schedule.name || "Payroll schedule", frequency: schedule.frequency, effective_from: schedule.effectiveFrom, configuration: scheduleConfigurationForPersistence(schedule), pay_date_rule: schedule.payDateRule, auto_generate_periods: schedule.autoGeneratePeriods, auto_calculate: schedule.autoCreateRuns ?? schedule.autoCalculate, active: schedule.active, updated_at: new Date().toISOString() };
  const { data, error } = await supabase.from("payroll_schedules").upsert(scheduleRow).select("*").single();
  if (error) throw error;
  const sourceVersions = schedule.versions?.length ? schedule.versions : [defaultScheduleVersion({ ...schedule, id: scheduleId })];
  const versionRows = sourceVersions.map((version) => ({ id: persistedId(version.id, "schedule-version"), schedule_id: scheduleId, version: version.version, effective_from: version.effectiveFrom, effective_to: version.effectiveTo || null, frequency: version.frequency, configuration: scheduleConfigurationForPersistence(version), pay_date_rule: version.payDateRule, auto_generate_periods: version.autoGeneratePeriods, auto_calculate: version.autoCreateRuns ?? version.autoCalculate, active: version.active, updated_at: new Date().toISOString() }));
  const { data: savedVersions, error: versionError } = await supabase.from("payroll_schedule_versions").upsert(versionRows, { onConflict: "schedule_id,version" }).select("*");
  if (versionError) throw versionError;
  return scheduleFromRow(data as Record<string, unknown>, (savedVersions || []) as Record<string, unknown>[]);
}

export async function saveWorkerCompensationProfileToSupabase(profile: WorkerCompensationProfile) {
  const userId = await currentUserId();
  if (!supabase || !userId) throw new Error("Sign in before saving compensation profiles.");
  const { data, error } = await supabase.from("worker_compensation_profiles").upsert({ id: persistedId(profile.id, "compensation"), user_id: userId, worker_id: profile.workerId, effective_from: profile.effectiveFrom, effective_to: profile.effectiveTo || null, frequency: profile.frequency, rate: profile.rate, default_labor_context: profile.defaultLaborContext, default_project_id: profile.defaultProjectId || null, active: true, updated_at: new Date().toISOString() }).select("*").single();
  if (error) throw error;
  return profileFromRow(data as Record<string, unknown>);
}

export async function saveRecurringPayrollComponentToSupabase(component: RecurringPayrollComponent) {
  const userId = await currentUserId();
  if (!supabase || !userId) throw new Error("Sign in before saving recurring payroll components.");
  const { data, error } = await supabase.from("recurring_payroll_components").upsert({ id: persistedId(component.id, "component"), user_id: userId, worker_id: component.workerId, type: component.type, code: (component as RecurringPayrollComponent & { code?: string }).code || null, name: component.name || null, amount: component.amount ?? null, rate: component.rate ?? null, effective_from: component.effectiveFrom, effective_to: component.effectiveTo || null, active: component.active, updated_at: new Date().toISOString() }).select("*").single();
  if (error) throw error;
  return componentFromRow(data as Record<string, unknown>);
}
export async function savePayrollPeriodToSupabase(period: PayrollPeriod) {
  const userId = await currentUserId();
  if (!supabase || !userId) throw new Error("Sign in before saving payroll periods.");
  const { data, error } = await supabase.from("payroll_periods").upsert({ id: persistedId(period.id, "period"), user_id: userId, period_start: period.periodStart, period_end: period.periodEnd, pay_date: period.payDate || null, schedule_id: period.scheduleId || null, schedule_version_id: period.scheduleVersionId || null, auto_generated: period.autoGenerated ?? false, locked_at: period.lockedAt || null, status: period.status, notes: period.notes || null, updated_at: new Date().toISOString() }).select("*").single();
  if (error) throw error;
  return periodFromRow(data as Record<string, unknown>);
}

export async function saveWorkEntryToSupabase(entry: WorkEntry) {
  const userId = await currentUserId();
  if (!supabase || !userId) throw new Error("Sign in before saving time entries.");
  const { data, error } = await supabase.from("work_entries").upsert({ id: persistedId(entry.id, "work"), user_id: userId, worker_id: entry.workerId, project_id: entry.projectId, period_id: entry.periodId || null, work_date: entry.workDate, regular_hours: entry.regularHours ?? null, overtime_hours: entry.overtimeHours ?? null, days_worked: entry.daysWorked ?? null, rate: entry.rate, overtime_rate: entry.overtimeRate ?? null, description: entry.description || null, notes: entry.notes || null, status: entry.status, updated_at: new Date().toISOString() }).select("*").single();
  if (error) throw error;
  return workEntryFromRow(data as Record<string, unknown>);
}

export async function savePayrollRunToSupabase(run: PayrollRun) {
  const userId = await currentUserId();
  if (!supabase || !userId) throw new Error("Sign in before creating payroll runs.");
  const { data, error } = await supabase.from("payroll_runs").upsert({ id: persistedId(run.id, "run"), user_id: userId, period_id: run.periodId, import_batch_id: run.importBatchId || null, status: run.status, calculated_at: run.calculatedAt || null, approved_at: run.approvedAt || null, paid_at: run.paidAt || null, notes: run.notes || null }).select("*").single();
  if (error) throw error;
  return runFromRow(data as Record<string, unknown>);
}

export async function savePayrollEntryToSupabase(entry: PayrollEntry, allocations: PayrollProjectAllocation[]) {
  const userId = await currentUserId();
  if (!supabase || !userId) throw new Error("Sign in before saving payroll entries.");
  const entryId = persistedId(entry.id, "entry");
  const { data: entryRow, error: entryError } = await supabase.from("payroll_entries").upsert({ id: entryId, user_id: userId, payroll_run_id: entry.payrollRunId, worker_id: entry.workerId, base_pay: entry.basePay, regular_pay: entry.regularPay, overtime_pay: entry.overtimePay, allowances: entry.allowances, other_earnings: entry.otherEarnings ?? 0, gross_pay: entry.grossPay, deductions: entry.deductions, other_deductions: entry.otherDeductions ?? 0, employer_costs: entry.employerCosts ?? 0, net_pay: entry.netPay, project_allocated_cost: entry.projectAllocatedCost, cost_context: entry.costContext || {}, import_row_id: entry.importRowId || null, calculation_snapshot: entry.calculationSnapshot || {} }).select("*").single();
  if (entryError) throw entryError;
  const { error: deleteError } = await supabase.from("payroll_project_allocations").delete().eq("payroll_entry_id", entryId).eq("user_id", userId);
  if (deleteError) throw deleteError;
  const rows = allocations.map((allocation) => ({ id: allocation.id && !allocation.id.startsWith("local-") ? allocation.id : undefined, user_id: userId, payroll_entry_id: entryId, project_id: allocation.projectId, allocation_amount: allocation.allocationAmount, allocation_percentage: allocation.allocationPercentage ?? null, source: allocation.source }));
  const { data: allocationRows, error: allocationError } = rows.length ? await supabase.from("payroll_project_allocations").insert(rows).select("*") : { data: [], error: null };
  if (allocationError) throw allocationError;
  return { entry: entryFromRow(entryRow as Record<string, unknown>), allocations: (allocationRows || []).map((row) => allocationFromRow(row as Record<string, unknown>)) };
}

export async function deletePayrollEntriesForRunToSupabase(runId: string) {
  const userId = await currentUserId();
  if (!supabase || !userId) throw new Error("Sign in before recalculating payroll.");
  const { error } = await supabase.from("payroll_entries").delete().eq("payroll_run_id", runId).eq("user_id", userId);
  if (error) throw error;
}

export async function savePayrollAdjustmentToSupabase(adjustment: PayrollAdjustment) {
  const userId = await currentUserId();
  if (!supabase || !userId) throw new Error("Sign in before saving payroll adjustments.");
  const { data, error } = await supabase.from("payroll_adjustments").upsert({ id: persistedId(adjustment.id, "adjustment"), user_id: userId, payroll_entry_id: adjustment.payrollEntryId, type: adjustment.type, code: adjustment.code || null, description: adjustment.description || null, amount: adjustment.amount }).select("*").single();
  if (error) throw error;
  return adjustmentFromRow(data as Record<string, unknown>);
}

export async function replacePayrollRunEntriesToSupabase(runId: string, entries: PayrollEntry[], allocations: PayrollProjectAllocation[]) {
  const userId = await currentUserId();
  if (!supabase || !userId) throw new Error("Sign in before recalculating payroll.");
  const { error } = await supabase.rpc("replace_payroll_run_entries", {
    p_run_id: runId,
    p_entries: entries,
    p_allocations: allocations,
  });
  if (error) throw error;
  return { entries, allocations };
}
