import assert from "node:assert/strict";
import test from "node:test";
import { isPayrollPeriodDataBearing, isSafeToDeletePayrollPeriod } from "../src/lib/payrollIntegrity.ts";
import { planLocalPayrollMaintenance } from "../src/lib/payrollMaintenance.ts";
import type { AttendanceRecord, LeaveRequest, OvertimeRequest, PayrollPeriod } from "../src/types.ts";

const period: PayrollPeriod = { id: "period-1", periodStart: "2026-08-01", periodEnd: "2026-08-15", autoGenerated: true, status: "DRAFT", createdAt: "2026-08-01T00:00:00.000Z", updatedAt: "2026-08-01T00:00:00.000Z" };
const attendance: AttendanceRecord = { id: "attendance-1", workerId: "worker-1", periodId: period.id, attendanceDate: "2026-08-03", scheduledMinutes: 480, breakMinutes: 60, regularMinutes: 480, lateMinutes: 0, undertimeMinutes: 0, overtimeMinutes: 0, paidDayFraction: 1, attendanceStatus: "PRESENT", recordStatus: "CONFIRMED", source: "MANUAL", createdAt: "2026-08-03T00:00:00.000Z", updatedAt: "2026-08-03T00:00:00.000Z" };
const leave: LeaveRequest = { id: "leave-1", workerId: "worker-1", leaveType: "PERSONAL", startDate: "2026-08-05", endDate: "2026-08-05", status: "PENDING", createdAt: "2026-08-05T00:00:00.000Z", updatedAt: "2026-08-05T00:00:00.000Z" };
const overtime: OvertimeRequest = { id: "ot-1", workerId: "worker-1", periodId: period.id, overtimeDate: "2026-08-06", requestedMinutes: 60, approvedMinutes: 0, status: "PENDING", source: "MANUAL", createdAt: "2026-08-06T00:00:00.000Z", updatedAt: "2026-08-06T00:00:00.000Z" };

test("attendance, leave, and overtime source records make a payroll period data-bearing", () => {
  assert.equal(isPayrollPeriodDataBearing(period, { attendanceRecords: [attendance] }), true);
  assert.equal(isPayrollPeriodDataBearing(period, { leaveRequests: [leave] }), true);
  assert.equal(isPayrollPeriodDataBearing(period, { overtimeRequests: [overtime] }), true);
  assert.equal(isSafeToDeletePayrollPeriod(period, { attendanceRecords: [attendance] }), false);
});

test("local maintenance preserves workforce sources during reset and rebuild planning", () => {
  const plan = planLocalPayrollMaintenance({
    schedules: [],
    periods: [period],
    runs: [],
    entries: [],
    allocations: [],
    adjustments: [],
    workEntries: [],
    attendanceRecords: [attendance],
    leaveRequests: [leave],
    overtimeRequests: [overtime],
    importData: { batches: [], rows: [], templates: [], costCenters: [] },
    referenceDate: "2026-08-10",
  }, "REBUILD_CALENDAR");
  assert.deepEqual(plan.attendanceRecords, [attendance]);
  assert.deepEqual(plan.leaveRequests, [leave]);
  assert.deepEqual(plan.overtimeRequests, [overtime]);
  assert.equal(plan.periods.some((candidate) => candidate.id === period.id), true);
  assert.equal(plan.preview.protectedDataBearingPeriods >= 1, true);
});
