import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import type { PayrollEntry, PayrollPeriod, PayrollRun } from "../src/types.ts";
import {
  findExactDuplicatePayrollPeriods,
  findOverlappingPayrollPeriods,
  inspectPayrollIntegrity,
  isPayrollPeriodDataBearing,
  isSafeToRetirePayrollPeriod,
  reconcileObsoleteGeneratedPayrollPeriods,
  selectPrimaryPayrollSchedule,
} from "../src/lib/payrollIntegrity.ts";
import { createDefaultPayrollSchedule, ensurePayrollPeriodsAndRuns } from "../src/lib/payrollWorkflow.ts";

function period(overrides: Partial<PayrollPeriod> = {}): PayrollPeriod {
  return { id: "period-1", periodStart: "2026-08-16", periodEnd: "2026-08-31", status: "OPEN", autoGenerated: true, createdAt: "2026-08-01T00:00:00.000Z", updatedAt: "2026-08-01T00:00:00.000Z", ...overrides };
}

test("schedule reconciliation retires an empty obsolete future period but preserves locked history", () => {
  const old = period({ id: "semi-monthly", scheduleId: "schedule-1", scheduleVersionId: "version-1" });
  const weekly = period({ id: "weekly", scheduleId: "schedule-1", scheduleVersionId: "version-2", periodStart: "2026-08-23", periodEnd: "2026-08-29" });
  const result = reconcileObsoleteGeneratedPayrollPeriods([old], [weekly], { referenceDate: "2026-08-23", horizonEnd: "2026-09-05" });
  assert.equal(result.periods.find((item) => item.id === old.id)?.status, "VOID");
  assert.deepEqual(result.retiredPeriodIds, [old.id]);
  const again = reconcileObsoleteGeneratedPayrollPeriods(result.periods, [weekly], { referenceDate: "2026-08-23", horizonEnd: "2026-09-05" });
  assert.deepEqual(again.retiredPeriodIds, []);
  assert.equal(again.periods.find((item) => item.id === old.id)?.status, "VOID");

  const paid = period({ id: "paid-old", status: "PAID", lockedAt: "2026-08-20T00:00:00.000Z" });
  const resultWithPaid = reconcileObsoleteGeneratedPayrollPeriods([paid], [weekly], { referenceDate: "2026-08-23", horizonEnd: "2026-09-05" });
  assert.equal(resultWithPaid.periods[0]?.status, "PAID");
});

test("data-bearing generated periods are never safe to retire", () => {
  const candidate = period({ id: "data-bearing", scheduleId: "schedule-1", scheduleVersionId: "version-1" });
  const run: PayrollRun = { id: "run-1", periodId: candidate.id, status: "DRAFT", createdAt: "2026-08-20T00:00:00.000Z" };
  const entry = { id: "entry-1", payrollRunId: run.id } as PayrollEntry;
  assert.equal(isPayrollPeriodDataBearing(candidate, { runs: [run], entries: [entry] }), true);
  assert.equal(isSafeToRetirePayrollPeriod(candidate, { runs: [run], entries: [entry] }), false);
});

test("integrity diagnostics identify duplicates, overlaps, and multiple active schedules", () => {
  const schedule = createDefaultPayrollSchedule("2026-01-01");
  const second = { ...schedule, id: "schedule-2", updatedAt: "2026-08-22T00:00:00.000Z" };
  const periods = [
    period({ id: "p1", scheduleId: schedule.id, scheduleVersionId: "v1", periodStart: "2026-08-23", periodEnd: "2026-08-29" }),
    period({ id: "p2", scheduleId: "schedule-2", scheduleVersionId: "v2", periodStart: "2026-08-23", periodEnd: "2026-08-29" }),
    period({ id: "p3", scheduleId: schedule.id, scheduleVersionId: "v3", periodStart: "2026-08-28", periodEnd: "2026-09-03" }),
  ];
  assert.equal(findExactDuplicatePayrollPeriods(periods).length, 1);
  assert.equal(findOverlappingPayrollPeriods(periods).length, 3);
  const report = inspectPayrollIntegrity([schedule, second], periods, []);
  assert.equal(report.activeScheduleCount, 2);
  assert.equal(report.issues.some((issue) => issue.code === "MULTIPLE_ACTIVE_SCHEDULES"), true);
  assert.equal(selectPrimaryPayrollSchedule([schedule, second])?.id, "schedule-2");
});

test("normal generation selects one primary schedule and creates only the current draft run", () => {
  const older = { ...createDefaultPayrollSchedule("2026-01-01"), id: "older", updatedAt: "2026-08-01T00:00:00.000Z" };
  const newer = { ...createDefaultPayrollSchedule("2026-01-01"), id: "newer", versions: undefined, frequency: "WEEKLY" as const, weekEndDay: 0 as 0, updatedAt: "2026-08-22T00:00:00.000Z" };
  const result = ensurePayrollPeriodsAndRuns({ schedules: [older, newer], periods: [], runs: [], referenceDate: "2026-08-23", previous: 1, next: 2 });
  assert.equal(result.periods.every((period) => period.scheduleId === newer.id), true);
  assert.equal(result.createdRuns.length, 1);
  assert.equal(result.periods.filter((period) => period.periodStart > "2026-08-23").some((period) => result.runs.some((run) => run.periodId === period.id)), false);
});

test("the additive migration contains table-specific ownership triggers and preserves RLS", () => {
  const sql = readFileSync(new URL("../supabase/migrations/20260823193000_payroll_integrity_repair.sql", import.meta.url), "utf8");
  assert.match(sql, /payroll_schedules_one_active_per_user/);
  assert.match(sql, /validate_payroll_run_ownership/);
  assert.match(sql, /validate_payroll_entry_ownership/);
  assert.match(sql, /validate_worker_compensation_profile_ownership/);
  assert.match(sql, /validate_recurring_payroll_component_ownership/);
  assert.doesNotMatch(sql, /create or replace function public\.validate_engineering_child_ownership/);
  assert.doesNotMatch(sql, /create or replace function public\.validate_payroll_profile_ownership/);
  const runOwnership = sql.slice(sql.indexOf("validate_payroll_run_ownership"), sql.indexOf("validate_payroll_entry_ownership"));
  const recurringOwnership = sql.slice(sql.indexOf("validate_recurring_payroll_component_ownership"), sql.indexOf("drop trigger if exists worker_compensation_profiles_ownership"));
  assert.doesNotMatch(runOwnership, /project_id/);
  assert.doesNotMatch(recurringOwnership, /default_project_id/);
  assert.match(sql, /alter table public\.payroll_runs enable row level security/);
  assert.match(sql, /grant select, insert, update, delete on table/);
});
