import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import type { PayrollPeriod, PayrollRun, WorkEntry } from "../src/types.ts";
import type { PayrollImportBatch, PayrollImportRow, PayrollImportWorkspaceData } from "../src/lib/payrollImportPersistence.ts";
import type { PayrollSchedule } from "../src/lib/payrollSchedule.ts";
import { mergeGeneratedPayrollPeriods } from "../src/lib/payrollSchedule.ts";
import { isSafeToDeletePayrollPeriod, isSafeToDeletePayrollRun } from "../src/lib/payrollIntegrity.ts";
import { planLocalPayrollMaintenance, payrollMaintenancePreviewFromResult, RESET_UNAPPROVED_CONFIRMATION } from "../src/lib/payrollMaintenance.ts";
import { PERMISSION_KEYS } from "../src/utils/accessControl.ts";

function weeklySchedule(): PayrollSchedule {
  return {
    id: "schedule-weekly",
    name: "Weekly payroll",
    effectiveFrom: "2026-01-01",
    frequency: "WEEKLY",
    weekEndDay: 0,
    anchorPeriodEnd: "2026-09-06",
    payDateRule: { type: "SAME_PERIOD_END" },
    autoGeneratePeriods: true,
    autoCalculate: false,
    autoCreateRuns: true,
    autoSelectCurrentPeriod: true,
    automationMode: "ASSISTED",
    active: true,
    versions: undefined,
  } as PayrollSchedule;
}

function semiMonthlySchedule(): PayrollSchedule {
  return {
    id: "schedule-semi",
    name: "Semi-monthly payroll",
    effectiveFrom: "2026-01-01",
    frequency: "SEMI_MONTHLY",
    customCutoffDay: 15,
    payDateRule: { type: "SAME_PERIOD_END" },
    autoGeneratePeriods: true,
    autoCalculate: false,
    autoCreateRuns: true,
    autoSelectCurrentPeriod: true,
    automationMode: "ASSISTED",
    active: true,
    versions: undefined,
  } as PayrollSchedule;
}

function imports(batches: PayrollImportBatch[] = [], rows: PayrollImportRow[] = []): PayrollImportWorkspaceData {
  return { costCenters: [], batches, rows, templates: [] };
}

function period(overrides: Partial<PayrollPeriod> = {}): PayrollPeriod {
  return { id: "period-1", periodStart: "2026-09-01", periodEnd: "2026-09-15", scheduleId: "schedule-weekly", scheduleVersionId: "schedule-weekly:v1", autoGenerated: true, status: "OPEN", createdAt: "2026-09-01T00:00:00.000Z", updatedAt: "2026-09-01T00:00:00.000Z", ...overrides };
}

function dateSpan(start: string, end: string) {
  return Math.round((Date.parse(`${end}T00:00:00Z`) - Date.parse(`${start}T00:00:00Z`)) / 86_400_000) + 1;
}

function committedBatch(): PayrollImportBatch {
  return { id: "batch-1", originalFileName: "payroll.xlsx", fileSha256: "a".repeat(64), storagePath: "companies/company/payroll-imports/batch-1/payroll.xlsx", sheetNames: ["Payroll"], status: "COMMITTED", mappingSnapshot: { version: 1 }, rawMetadata: { source: "fixture" }, warnings: ["keep"], errors: [], committedPayrollPeriodId: "period-1", committedPayrollRunId: "run-1", createdAt: "2026-09-01T00:00:00.000Z", updatedAt: "2026-09-01T00:00:00.000Z", committedAt: "2026-09-01T00:00:00.000Z" };
}

function committedRow(): PayrollImportRow {
  return { id: "row-1", batchId: "batch-1", sourceSheet: "Payroll", sourceRow: 2, originalEmployeeName: "Worker", canonicalData: { sourceSheet: "Payroll", sourceRow: 2, costContext: "PROJECT", rawRow: ["Worker", 100], warnings: [], confidence: { level: "HIGH", score: 1, reasons: [] } }, rawRow: ["Worker", 100], warnings: [], errors: [], confidenceLevel: "HIGH", confidenceScore: 1, status: "COMMITTED", workerMatchStatus: "MATCHED", workerId: "worker-1", projectMatchStatus: "MATCHED", laborContext: { type: "PROJECT", projectId: "project-1", needsReview: false }, committedPayrollEntryId: "entry-1", createdAt: "2026-09-01T00:00:00.000Z", updatedAt: "2026-09-01T00:00:00.000Z" };
}

function workEntry(): WorkEntry { return { id: "work-1", workerId: "worker-1", projectId: "project-1", periodId: "period-1", workDate: "2026-09-10", regularHours: 8, rate: 100, status: "APPROVED" }; }

test("one maintenance action produces a real preview and weekly rebuild replaces malformed boundaries", () => {
  const malformed = period();
  const first = planLocalPayrollMaintenance({ schedules: [weeklySchedule()], periods: [malformed], runs: [], entries: [], allocations: [], adjustments: [], workEntries: [], importData: imports(), referenceDate: "2026-09-10" }, "REBUILD_CALENDAR");
  assert.equal(first.preview.action, "REBUILD_CALENDAR");
  assert.equal(first.periods.some((item) => item.id === malformed.id), false);
  assert.ok(first.preview.periodsToDelete >= 1);
  assert.ok(first.preview.periodsToCreate >= 1);
  assert.ok(first.periods.filter((item) => item.scheduleId === "schedule-weekly").every((item) => dateSpan(item.periodStart, item.periodEnd) === 7));
  assert.ok(first.periods.some((item) => item.periodStart === "2026-09-07" && item.periodEnd === "2026-09-13" && item.status === "OPEN"));
  const second = planLocalPayrollMaintenance({ schedules: [weeklySchedule()], periods: first.periods, runs: first.runs, entries: first.entries, allocations: first.allocations, adjustments: first.adjustments, workEntries: first.workEntries, importData: first.importData, referenceDate: "2026-09-10" }, "REBUILD_CALENDAR");
  assert.equal(second.preview.noChanges, true);
  assert.equal(second.preview.periodsToDelete, 0);
  assert.equal(second.preview.periodsToCreate, 0);
  assert.equal(second.preview.runsToCreate, 0);
});

test("empty generated VOID tombstones are disposable but meaningful VOID history remains protected", () => {
  const empty = period({ id: "empty-tombstone", status: "VOID", notes: undefined });
  const meaningful = period({ id: "meaningful-void", status: "VOID", notes: "Historical correction approved by finance." });
  assert.equal(isSafeToDeletePayrollPeriod(empty, { runs: [], entries: [], workEntries: [], importBatches: [] }), true);
  assert.equal(isSafeToDeletePayrollPeriod(meaningful, { runs: [], entries: [], workEntries: [], importBatches: [] }), false);
  const generated = { periodKey: "generated", scheduleId: "schedule-weekly", scheduleVersionId: "schedule-weekly:v1", periodStart: "2026-09-07", periodEnd: "2026-09-13", status: "DRAFT" as const, active: true };
  assert.equal(mergeGeneratedPayrollPeriods([{ id: empty.id, periodKey: "empty", scheduleId: empty.scheduleId!, scheduleVersionId: empty.scheduleVersionId!, periodStart: empty.periodStart, periodEnd: empty.periodEnd, status: empty.status, active: false, autoGenerated: true }], [generated]).some((item) => item.id === empty.id), false);
  assert.equal(mergeGeneratedPayrollPeriods([{ id: meaningful.id, periodKey: "meaningful", scheduleId: meaningful.scheduleId!, scheduleVersionId: meaningful.scheduleVersionId!, periodStart: generated.periodStart, periodEnd: generated.periodEnd, status: "VOID", active: false, autoGenerated: true, notes: meaningful.notes }], [generated]).some((item) => item.status === "VOID"), true);
});

test("reset unapproved removes derived payroll and reopens committed import provenance without touching source work", () => {
  const schedule = semiMonthlySchedule();
  const base = planLocalPayrollMaintenance({ schedules: [schedule], periods: [], runs: [], entries: [], allocations: [], adjustments: [], workEntries: [], importData: imports(), referenceDate: "2026-09-10" }, "REBUILD_CALENDAR");
  const current = base.periods.find((item) => item.status === "OPEN")!;
  const currentRun = base.runs.find((item) => item.periodId === current.id)!;
  const run: PayrollRun = { ...currentRun, id: "run-1", importBatchId: "batch-1" };
  const entry = { id: "entry-1", payrollRunId: run.id, workerId: "worker-1", basePay: 100, regularPay: 100, overtimePay: 0, allowances: 0, grossPay: 100, deductions: 0, netPay: 100, projectAllocatedCost: 100 };
  const allocation = { id: "allocation-1", payrollEntryId: entry.id, projectId: "project-1", allocationAmount: 100, source: "IMPORT" as const };
  const adjustment = { id: "adjustment-1", payrollEntryId: entry.id, type: "EARNING" as const, amount: 5 };
  const sourceWork = workEntry();
  const plan = planLocalPayrollMaintenance({ schedules: [schedule], periods: base.periods, runs: base.runs.map((item) => item.id === currentRun.id ? run : item), entries: [entry], allocations: [allocation], adjustments: [adjustment], workEntries: [sourceWork], importData: imports([committedBatch()], [committedRow()]), referenceDate: "2026-09-10" }, "RESET_UNAPPROVED");
  assert.equal(plan.preview.action, "RESET_UNAPPROVED");
  assert.equal(plan.preview.entriesToDelete, 1);
  assert.equal(plan.preview.allocationsToDelete, 1);
  assert.equal(plan.preview.adjustmentsToDelete, 1);
  assert.ok(plan.preview.runsToDelete >= 1);
  assert.equal(plan.entries.some((item) => item.id === entry.id), false);
  assert.equal(plan.allocations.some((item) => item.id === allocation.id), false);
  assert.equal(plan.adjustments.some((item) => item.id === adjustment.id), false);
  assert.equal(plan.workEntries[0]?.id, sourceWork.id);
  assert.deepEqual(plan.workEntries[0], sourceWork);
  assert.equal(plan.importData.batches[0]?.status, "VALIDATED");
  assert.equal(plan.importData.batches[0]?.committedPayrollRunId, undefined);
  assert.equal(plan.importData.rows[0]?.status, "READY");
  assert.equal(plan.importData.rows[0]?.committedPayrollEntryId, undefined);
  assert.equal(plan.importData.batches[0]?.rawMetadata.source, "fixture");
});

test("maintenance preview parsing preserves the public count contract and exact confirmation phrase", () => {
  const preview = payrollMaintenancePreviewFromResult({ action: "RESET_UNAPPROVED", referenceDate: "2026-09-10", eligible: true, noChanges: false, entriesToDelete: 2, importRowsToReopen: 3 });
  assert.equal(preview.action, "RESET_UNAPPROVED");
  assert.equal(preview.entriesToDelete, 2);
  assert.equal(preview.importRowsToReopen, 3);
  assert.equal(RESET_UNAPPROVED_CONFIRMATION, "RESET UNAPPROVED PAYROLL");
});

test("frontend modal, permissions, and migration contract cover the maintenance safety boundary", () => {
  const modal = readFileSync(new URL("../src/components/payroll/PayrollAdvancedTools.tsx", import.meta.url), "utf8");
  const migration = readFileSync(new URL("../supabase/migrations/20260824105000_payroll_maintenance_rpcs.sql", import.meta.url), "utf8");
  const access = readFileSync(new URL("../src/utils/accessControl.ts", import.meta.url), "utf8");
  assert.match(modal, /const \[toolMode, setToolMode\] = useState<PayrollAdvancedTool \| null>/);
  assert.match(modal, /toolMode !== null/);
  assert.doesNotMatch(modal, /previewMode/);
  assert.match(modal, /RESET UNAPPROVED PAYROLL/);
  assert.match(modal, /previewRequestRef/);
  assert.equal(PERMISSION_KEYS.payrollSettings, "payroll.settings");
  assert.match(access, /payrollSettings: "payroll\.settings"/);
  assert.match(migration, /create or replace function public\.preview_payroll_maintenance/);
  assert.match(migration, /create or replace function public\.apply_payroll_maintenance/);
  assert.match(migration, /private\.has_company_permission\(p_company_id, 'payroll\.settings'\)/);
  assert.match(migration, /private\.has_company_permission\(p_company_id, 'payroll\.manage'\)/);
  assert.match(migration, /RESET UNAPPROVED PAYROLL/);
  assert.match(migration, /status = 'VALIDATED'/);
  assert.match(migration, /status = case when pir\.status = 'COMMITTED' then 'READY'/);
  assert.match(migration, /delete from public\.payroll_project_allocations/);
  assert.match(migration, /delete from public\.payroll_adjustments/);
  assert.match(migration, /delete from public\.payroll_entries/);
  assert.match(migration, /delete from public\.payroll_runs/);
  assert.match(migration, /PAYROLL_REPAIR_APPLIED/);
  assert.match(migration, /PAYROLL_CALENDAR_REBUILT/);
  assert.match(migration, /PAYROLL_UNAPPROVED_RESET/);
  assert.match(migration, /on conflict do nothing/);
  assert.doesNotMatch(migration, /drop table public\./i);
});