import test from "node:test";
import assert from "node:assert/strict";
import { createDefaultPayrollSchedule, ensurePayrollPeriodsAndRuns } from "../src/lib/payrollWorkflow.ts";
import type { PayrollSchedule } from "../src/lib/payrollSchedule.ts";
import type { PayrollEntry, PayrollPeriod, PayrollRun } from "../src/types.ts";

/** Mirrors the user-reported broken state: weekly schedule saved mid-cycle on 2026-08-25. */
function weeklyUserSchedule(overrides: Partial<PayrollSchedule> = {}): PayrollSchedule {
  return {
    id: "schedule-1",
    name: "Weekly payroll",
    effectiveFrom: "2026-08-25",
    frequency: "WEEKLY",
    weekEndDay: 0,
    payDateRule: { type: "BUSINESS_DAYS", offsetDays: 0 },
    autoGeneratePeriods: true,
    autoCalculate: false,
    autoCreateRuns: true,
    autoSelectCurrentPeriod: true,
    automationMode: "AUTOMATED",
    active: true,
    ...overrides,
  };
}

function storedPeriod(id: string, periodStart: string, periodEnd: string, status: PayrollPeriod["status"], overrides: Partial<PayrollPeriod> = {}): PayrollPeriod {
  return {
    id,
    periodStart,
    periodEnd,
    scheduleId: "schedule-1",
    scheduleVersionId: "schedule-1:v1",
    autoGenerated: true,
    status,
    createdAt: `${periodStart}T00:00:00.000Z`,
    updatedAt: `${periodStart}T00:00:00.000Z`,
    ...overrides,
  };
}

test("ensures a bounded semi-monthly period horizon and opens only the current draft run", () => {
  const schedule = createDefaultPayrollSchedule("2026-08-01");
  const first = ensurePayrollPeriodsAndRuns({ schedules: [schedule], periods: [], runs: [], referenceDate: "2026-08-20", previous: 2, next: 2 });
  assert.equal(first.createdRuns.length, 1);
  assert.equal(first.runs[0]?.periodId, first.periods.find((period) => period.periodStart === "2026-08-16")?.id);
  assert.equal(first.periods.some((period) => period.periodStart === "2026-08-16" && period.periodEnd === "2026-08-31"), true);
  assert.ok(first.periods.length <= 5);
  assert.equal(first.runs.some((run) => run.periodId === first.periods.find((period) => period.periodStart > "2026-08-20")?.id), false);
  const second = ensurePayrollPeriodsAndRuns({ schedules: [schedule], periods: first.periods, runs: first.runs, referenceDate: "2026-08-20", previous: 2, next: 2 });
  assert.equal(second.createdRuns.length, 0);
  assert.equal(second.createdPeriods.length, 0);
  assert.equal(second.runs.length, first.runs.length);
});

test("bootstraps and generates a zero-worker semi-monthly horizon idempotently", () => {
  const schedule = createDefaultPayrollSchedule("2026-08-25");
  assert.equal(schedule.effectiveFrom, "2026-08-16");
  const first = ensurePayrollPeriodsAndRuns({
    schedules: [schedule],
    periods: [],
    runs: [],
    referenceDate: "2026-08-25",
    previous: 2,
    next: 2,
  });
  const current = first.periods.find((period) => period.periodStart === "2026-08-16");

  // Period generation is schedule-driven, not worker-driven.
  assert.ok(first.periods.length > 0);
  assert.equal(first.periods.length, 3, "the effectiveFrom boundary limits the previous side of the horizon");
  assert.equal(current?.periodEnd, "2026-08-31");
  assert.equal(current?.payDate, "2026-09-02");
  assert.equal(first.selectedPeriodId, current?.id);
  assert.equal(first.createdRuns.length, 1);
  assert.equal(first.runs.filter((run) => run.status === "DRAFT").length, 1);
  assert.equal(first.runs[0]?.periodId, current?.id);

  const second = ensurePayrollPeriodsAndRuns({
    schedules: [schedule],
    periods: first.periods,
    runs: first.runs,
    referenceDate: "2026-08-25",
    previous: 2,
    next: 2,
  });
  assert.equal(second.createdPeriods.length, 0);
  assert.equal(second.createdRuns.length, 0);
  assert.deepEqual(second.periods.map((period) => period.id), first.periods.map((period) => period.id));
  assert.deepEqual(second.runs.map((run) => run.id), first.runs.map((run) => run.id));
});

test("preserves an existing future run and approved current run", () => {
  const schedule = createDefaultPayrollSchedule("2026-08-01");
  const first = ensurePayrollPeriodsAndRuns({ schedules: [schedule], periods: [], runs: [], referenceDate: "2026-08-20", previous: 1, next: 2 });
  const currentRun = first.runs[0]!;
  const futurePeriod = first.periods.find((period) => period.periodStart > "2026-08-20")!;
  const futureRun = { id: "future-run", periodId: futurePeriod.id, status: "DRAFT" as const, createdAt: "2026-08-20T00:00:00.000Z" };
  const result = ensurePayrollPeriodsAndRuns({
    schedules: [schedule],
    periods: first.periods,
    runs: [{ ...currentRun, status: "APPROVED" }, futureRun],
    referenceDate: "2026-08-20",
    previous: 1,
    next: 2,
  });
  assert.equal(result.runs.find((run) => run.id === currentRun.id)?.status, "APPROVED");
  assert.equal(result.runs.find((run) => run.id === futureRun.id)?.status, "DRAFT");
  assert.equal(result.createdRuns.length, 0);
});

test("does not replace an approved period when a schedule is edited", () => {
  const schedule = createDefaultPayrollSchedule("2026-08-01");
  const first = ensurePayrollPeriodsAndRuns({ schedules: [schedule], periods: [], runs: [], referenceDate: "2026-08-20", previous: 1, next: 1 });
  const locked = first.periods.find((period) => period.periodStart === "2026-08-16")!;
  const edited = { ...schedule, frequency: "MONTHLY" as const, autoCreateRuns: true };
  const result = ensurePayrollPeriodsAndRuns({ schedules: [edited], periods: [{ ...locked, status: "PAID", lockedAt: "2026-09-01T00:00:00.000Z" }], runs: first.runs, referenceDate: "2026-08-20", previous: 1, next: 1 });
  assert.equal(result.periods.find((period) => period.id === locked.id)?.status, "PAID");
  assert.equal(result.periods.find((period) => period.id === locked.id)?.periodStart, locked.periodStart);
});

test("keeps data-bearing prospective history when a schedule version changes", () => {
  const v1 = {
    ...createDefaultPayrollSchedule("2026-01-01").versions![0]!,
    id: "schedule-1-v1",
    scheduleId: "schedule-1",
    frequency: "MONTHLY" as const,
    effectiveFrom: "2026-01-01",
    payDateRule: { type: "SAME_PERIOD_END" as const },
  };
  const v2 = {
    ...v1,
    id: "schedule-1-v2",
    version: 2,
    frequency: "SEMI_MONTHLY" as const,
    effectiveFrom: "2026-09-01",
    payDateRule: { type: "BUSINESS_DAYS" as const, offsetDays: 2 },
  };
  const schedule = {
    ...createDefaultPayrollSchedule("2026-01-01"),
    id: "schedule-1",
    frequency: "MONTHLY" as const,
    versions: [v1, v2],
  };
  const historical = {
    id: "period-history",
    periodStart: "2026-09-01",
    periodEnd: "2026-09-30",
    scheduleId: "schedule-1",
    scheduleVersionId: v1.id,
    autoGenerated: true,
    status: "OPEN" as const,
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  };
  const result = ensurePayrollPeriodsAndRuns({
    schedules: [schedule],
    periods: [historical],
    runs: [],
    workEntries: [{ id: "work-1", workerId: "worker-1", periodId: historical.id, workDate: "2026-09-10", regularHours: 8, overtimeHours: 0, daysWorked: 1, rate: 100, status: "DRAFT" }],
    referenceDate: "2026-09-10",
    previous: 1,
    next: 1,
  });
  assert.equal(result.periods.find((period) => period.id === historical.id)?.periodEnd, "2026-09-30");
  assert.equal(result.periods.some((period) => period.id === historical.id), true);
});

test("a weekly mid-cycle bootstrap produces a bounded horizon and is idempotent", () => {
  const schedule = weeklyUserSchedule();
  const first = ensurePayrollPeriodsAndRuns({ schedules: [schedule], periods: [], runs: [], entries: [], workEntries: [], referenceDate: "2026-08-25", previous: 2, next: 2 });
  assert.equal(first.createdRuns.length, 0, "no current period exists while the first complete week is still in the future");
  assert.deepEqual(first.periods.map((period) => [period.periodStart, period.periodEnd]).slice().sort(), [
    ["2026-08-31", "2026-09-06"],
    ["2026-09-07", "2026-09-13"],
    ["2026-09-14", "2026-09-20"],
  ]);
  assert.equal(first.runs.length, 0);

  const second = ensurePayrollPeriodsAndRuns({ schedules: [schedule], periods: first.periods, runs: first.runs, entries: [], workEntries: [], referenceDate: "2026-08-25", previous: 2, next: 2 });
  assert.equal(second.createdPeriods.length, 0);
  assert.equal(second.createdRuns.length, 0);
  assert.deepEqual(second.periods.map((period) => [period.periodStart, period.periodEnd]).slice().sort(), first.periods.map((period) => [period.periodStart, period.periodEnd]).slice().sort());
  assert.deepEqual(second.runs.map((run) => run.id).sort(), first.runs.map((run) => run.id).sort());

  const draftRunsPerPeriod = new Map<string, number>();
  for (const run of second.runs) {
    if (run.status !== "DRAFT") continue;
    draftRunsPerPeriod.set(run.periodId, (draftRunsPerPeriod.get(run.periodId) || 0) + 1);
  }
  for (const [periodId, count] of draftRunsPerPeriod) assert.ok(count <= 1, `period ${periodId} has ${count} DRAFT runs`);
});

test("finalized, locked, and data-bearing periods survive a mid-cycle weekly horizon untouched", () => {
  const schedule = weeklyUserSchedule();
  const protectedPeriods: PayrollPeriod[] = [
    storedPeriod("period-approved", "2026-08-03", "2026-08-09", "APPROVED"),
    storedPeriod("period-paid", "2026-08-10", "2026-08-16", "PAID"),
    storedPeriod("period-locked", "2026-08-17", "2026-08-23", "OPEN", { lockedAt: "2026-08-24T00:00:00.000Z" }),
    storedPeriod("period-open-data", "2026-08-24", "2026-08-30", "OPEN"),
  ];
  const dataRun: PayrollRun = { id: "run-data", periodId: "period-open-data", status: "DRAFT", createdAt: "2026-08-25T00:00:00.000Z" };
  const dataEntry: PayrollEntry = { id: "entry-1", payrollRunId: "run-data", workerId: "worker-1", basePay: 0, regularPay: 800, overtimePay: 0, allowances: 0, grossPay: 800, deductions: 0, netPay: 800, projectAllocatedCost: 0, createdAt: "2026-08-26T00:00:00.000Z" };

  const result = ensurePayrollPeriodsAndRuns({
    schedules: [schedule],
    periods: protectedPeriods,
    runs: [dataRun],
    entries: [dataEntry],
    workEntries: [],
    referenceDate: "2026-08-25",
    previous: 2,
    next: 2,
  });

  assert.equal(result.createdPeriods.length, 3);
  assert.equal(result.periods.length, 7);
  assert.equal(new Set(result.periods.map((period) => `${period.scheduleId}:${period.periodStart}:${period.periodEnd}`)).size, 7, "no duplicate boundaries may be created");

  for (const protectedPeriod of protectedPeriods) {
    const kept = result.periods.find((period) => period.id === protectedPeriod.id);
    assert.ok(kept, `${protectedPeriod.id} must survive`);
    assert.equal(kept!.status, protectedPeriod.status);
    assert.equal(kept!.periodStart, protectedPeriod.periodStart);
    assert.equal(kept!.periodEnd, protectedPeriod.periodEnd);
    assert.equal(kept!.scheduleVersionId, protectedPeriod.scheduleVersionId);
  }
  assert.ok(result.createdPeriods.every((period) => !protectedPeriods.some((protectedPeriod) => protectedPeriod.id === period.id)));
  assert.equal(result.selectedPeriodId, "period-open-data");
  assert.deepEqual(result.runs.map((run) => run.id), ["run-data"], "no duplicate run may be created for the already-covered current period");
});

test("switching the saved schedule to monthly keeps one DRAFT run per period and unique boundaries", () => {
  const weekly = weeklyUserSchedule();
  const first = ensurePayrollPeriodsAndRuns({ schedules: [weekly], periods: [], runs: [], entries: [], workEntries: [], referenceDate: "2026-08-25", previous: 2, next: 2 });
  const survivor = first.periods.find((period) => period.periodStart === "2026-09-14")!;

  // Save-like mutation: the edited configuration replaces the schedule wholesale.
  const monthly = weeklyUserSchedule({ frequency: "MONTHLY", weekEndDay: undefined });
  const result = ensurePayrollPeriodsAndRuns({
    schedules: [monthly],
    periods: first.periods,
    runs: first.runs,
    entries: [],
    workEntries: [],
    referenceDate: "2026-08-25",
    previous: 2,
    next: 2,
  });

  const boundaryKeys = result.periods.map((period) => `${period.scheduleId}:${period.periodStart}:${period.periodEnd}`);
  assert.equal(new Set(boundaryKeys).size, boundaryKeys.length, "no duplicate boundaries may exist after the schedule change");
  for (const expected of [["2026-09-01", "2026-09-30"], ["2026-10-01", "2026-10-31"], ["2026-11-01", "2026-11-30"]]) {
    assert.ok(result.periods.some((period) => period.periodStart === expected[0] && period.periodEnd === expected[1]), `monthly period ${expected.join(":")} must be generated`);
  }

  const runsPerPeriod = new Map<string, number>();
  for (const run of result.runs) runsPerPeriod.set(run.periodId, (runsPerPeriod.get(run.periodId) || 0) + 1);
  for (const [periodId, count] of runsPerPeriod) assert.ok(count <= 1, `period ${periodId} has ${count} runs after the schedule change`);

  // The empty weekly horizon is disposable generated infrastructure: after the
  // switch to monthly it is retired together with its empty auto-created draft
  // run instead of lingering as a permanent shape mismatch. Periods holding
  // real data (entries, work, attendance, finalized runs) remain protected.
  assert.equal(result.periods.find((period) => period.id === survivor.id), undefined, "the obsolete empty weekly period must not linger after the monthly switch");
  assert.equal(result.runs.some((run) => run.periodId === survivor.id), false, "the retired period's empty auto-created run must be retired with it");
  assert.ok(result.runs.every((run) => result.periods.some((period) => period.id === run.periodId)), "no orphaned runs may remain after the schedule change");
});

test("generates the mid-cycle weekly horizon without any workers in the input at all", () => {
  const schedule = weeklyUserSchedule();
  const result = ensurePayrollPeriodsAndRuns({ schedules: [schedule], periods: [], runs: [], referenceDate: "2026-08-25", previous: 2, next: 2 });
  assert.equal(result.periods.length, 3);
  assert.deepEqual(result.periods.map((period) => [period.periodStart, period.periodEnd]).slice().sort(), [
    ["2026-08-31", "2026-09-06"],
    ["2026-09-07", "2026-09-13"],
    ["2026-09-14", "2026-09-20"],
  ]);
  assert.equal(result.createdRuns.length, 0, "automatic draft runs wait for an actual current period");
  assert.equal(result.runs.length, 0);
});
