import test from "node:test";
import assert from "node:assert/strict";
import {
  findFirstGeneratablePayrollPeriod,
  generatePayrollPeriodsAroundReference,
  resolvePayrollScheduleVersion,
  selectActualPayrollPeriod,
  selectCurrentPayrollPeriod,
  selectNearestUpcomingPayrollPeriod,
  validatePayrollSchedule,
  type PayrollSchedule,
  type PayrollScheduleVersion,
  type ScheduledPayrollPeriod,
} from "../src/lib/payrollSchedule.ts";
import { repairFuturePayrollScheduleVersionGaps } from "../src/lib/payrollIntegrity.ts";
import { ensurePayrollPeriodsAndRuns } from "../src/lib/payrollWorkflow.ts";
import type { PayrollPeriod } from "../src/types.ts";

function weeklySchedule(overrides: Partial<PayrollSchedule> = {}): PayrollSchedule {
  return {
    id: "schedule-1",
    name: "Weekly payroll",
    effectiveFrom: "2026-08-25",
    frequency: "WEEKLY",
    weekEndDay: 0,
    payDateRule: { type: "SAME_PERIOD_END" },
    autoGeneratePeriods: true,
    autoCalculate: false,
    autoCreateRuns: true,
    autoSelectCurrentPeriod: true,
    automationMode: "AUTOMATED",
    active: true,
    ...overrides,
  };
}

function scheduledPeriod(id: string, periodStart: string, periodEnd: string, status: string = "DRAFT", overrides: Partial<ScheduledPayrollPeriod> = {}): ScheduledPayrollPeriod {
  return {
    id,
    periodKey: `schedule-1:schedule-1:v1:${periodStart}:${periodEnd}`,
    scheduleId: "schedule-1",
    scheduleVersionId: "schedule-1:v1",
    periodStart,
    periodEnd,
    status,
    active: true,
    autoGenerated: true,
    ...overrides,
  };
}

function storedPeriod(id: string, periodStart: string, periodEnd: string, status: PayrollPeriod["status"] = "DRAFT", overrides: Partial<PayrollPeriod> = {}): PayrollPeriod {
  return {
    id,
    periodStart,
    periodEnd,
    scheduleId: "schedule-1",
    scheduleVersionId: "schedule-1:v1",
    autoGenerated: true,
    status,
    createdAt: `${periodStart}T00:00:00.000Z`,
    updatedAt: `${periodStart}T00:00:00.000Z`,
    ...overrides,
  };
}

function version(overrides: Partial<PayrollScheduleVersion> = {}): PayrollScheduleVersion {
  return {
    id: "schedule-1-v1",
    scheduleId: "schedule-1",
    version: 1,
    effectiveFrom: "2026-08-25",
    frequency: "WEEKLY",
    weekEndDay: 0,
    payDateRule: { type: "SAME_PERIOD_END" },
    autoGeneratePeriods: true,
    autoCalculate: false,
    autoCreateRuns: true,
    autoSelectCurrentPeriod: true,
    automationMode: "AUTOMATED",
    active: true,
    ...overrides,
  };
}

test("selects the nearest upcoming weekly period instead of the farthest future period", () => {
  const periods = [
    scheduledPeriod("aug31", "2026-08-31", "2026-09-06"),
    scheduledPeriod("sep7", "2026-09-07", "2026-09-13"),
    scheduledPeriod("sep14", "2026-09-14", "2026-09-20"),
  ];

  assert.equal(selectNearestUpcomingPayrollPeriod(periods, "2026-08-26")?.id, "aug31");
  assert.equal(selectCurrentPayrollPeriod(periods, "2026-08-26")?.id, "aug31");
  assert.equal(selectActualPayrollPeriod(periods, "2026-08-26"), undefined);
});

test("selects the actual period containing each reference date", () => {
  const periods = [
    scheduledPeriod("aug31", "2026-08-31", "2026-09-06"),
    scheduledPeriod("sep7", "2026-09-07", "2026-09-13"),
    scheduledPeriod("sep14", "2026-09-14", "2026-09-20"),
  ];

  assert.equal(selectActualPayrollPeriod(periods, "2026-09-02")?.id, "aug31");
  assert.equal(selectCurrentPayrollPeriod(periods, "2026-09-02")?.id, "aug31");
  assert.equal(selectActualPayrollPeriod(periods, "2026-09-08")?.id, "sep7");
  assert.equal(selectCurrentPayrollPeriod(periods, "2026-09-08")?.id, "sep7");
  assert.equal(selectActualPayrollPeriod(periods, "2026-09-15")?.id, "sep14");
  assert.equal(selectCurrentPayrollPeriod(periods, "2026-09-15")?.id, "sep14");
  assert.equal(selectCurrentPayrollPeriod(periods, "2026-09-30")?.id, "sep14");
});

test("future weekly periods remain drafts and do not receive a current run before the first boundary", () => {
  const result = ensurePayrollPeriodsAndRuns({
    schedules: [weeklySchedule()],
    periods: [],
    runs: [],
    entries: [],
    workEntries: [],
    referenceDate: "2026-08-26",
    previous: 2,
    next: 2,
  });

  assert.deepEqual(result.periods.map((period) => [period.periodStart, period.periodEnd]).sort(), [
    ["2026-08-31", "2026-09-06"],
    ["2026-09-07", "2026-09-13"],
    ["2026-09-14", "2026-09-20"],
  ]);
  assert.equal(result.selectedPeriodId, result.periods.find((period) => period.periodStart === "2026-08-31")?.id);
  assert.equal(result.createdRuns.length, 0);
  assert.equal(result.periods.some((period) => period.status === "OPEN"), false);
  assert.equal(result.periods.every((period) => period.status === "DRAFT"), true);
});

test("a stale system-created future run is retired when no period is active", () => {
  const schedule = weeklySchedule();
  const generated = ensurePayrollPeriodsAndRuns({ schedules: [schedule], periods: [], runs: [], entries: [], workEntries: [], referenceDate: "2026-08-26", previous: 2, next: 2 });
  const future = generated.periods.find((period) => period.periodStart === "2026-09-14")!;
  const staleRun = { id: "stale-future-run", periodId: future.id, status: "DRAFT" as const, notes: "Auto-created draft run for the current payroll period.", createdAt: "2026-08-26T00:00:00.000Z" };
  const result = ensurePayrollPeriodsAndRuns({ schedules: [schedule], periods: generated.periods, runs: [staleRun], entries: [], workEntries: [], referenceDate: "2026-08-26", previous: 2, next: 2 });
  assert.equal(result.runs.some((run) => run.id === staleRun.id), false);
  assert.deepEqual(result.retiredRunIds, [staleRun.id]);
  assert.equal(result.periods.find((period) => period.id === future.id)?.status, "DRAFT");
});

test("an existing later period is reused while the two missing canonical weekly periods are reconstructed", () => {
  const later = storedPeriod("sep14", "2026-09-14", "2026-09-20");
  const result = ensurePayrollPeriodsAndRuns({
    schedules: [weeklySchedule()],
    periods: [later],
    runs: [],
    entries: [],
    workEntries: [],
    referenceDate: "2026-08-26",
    previous: 2,
    next: 2,
  });

  const boundaries = result.periods.map((period) => `${period.periodStart}:${period.periodEnd}`).sort();
  assert.deepEqual(boundaries, ["2026-08-31:2026-09-06", "2026-09-07:2026-09-13", "2026-09-14:2026-09-20"]);
  assert.equal(result.periods.filter((period) => period.periodStart === "2026-09-14" && period.periodEnd === "2026-09-20").length, 1);
  assert.equal(result.periods.find((period) => period.id === "sep14")?.status, "DRAFT");
  assert.equal(result.createdRuns.length, 0);
});

test("locked reset-era VOID tombstones do not block new periods from the governing version", () => {
  const v1 = version({ id: "schedule-1-v1", version: 1, effectiveFrom: "2026-08-23", effectiveTo: "2026-08-23", frequency: "SEMI_MONTHLY" as const, weekEndDay: undefined });
  const v2 = version({ id: "schedule-1-v2", version: 2, effectiveFrom: "2026-08-24", effectiveTo: "2026-08-24" });
  const v3 = version({ id: "schedule-1-v3", version: 3, effectiveFrom: "2026-08-25", effectiveTo: "2026-08-25" });
  const v4 = version({ id: "schedule-1-v4", version: 4, effectiveFrom: "2026-08-26" });
  const schedule = weeklySchedule({ effectiveFrom: "2026-08-23", versions: [v1, v2, v3, v4] });
  const tombstones = [
    storedPeriod("void-aug31", "2026-08-31", "2026-09-06", "VOID", { scheduleVersionId: v2.id, lockedAt: "2026-08-24T04:22:43.161Z", notes: "Retired by the explicit unapproved payroll reset." }),
    storedPeriod("void-sep7", "2026-09-07", "2026-09-13", "VOID", { scheduleVersionId: v2.id, lockedAt: "2026-08-24T04:22:43.161Z", notes: "Retired by the explicit unapproved payroll reset." }),
    storedPeriod("sep14", "2026-09-14", "2026-09-20", "OPEN", { scheduleVersionId: v4.id }),
  ];

  const result = ensurePayrollPeriodsAndRuns({
    schedules: [schedule],
    periods: tombstones,
    runs: [{ id: "void-run", periodId: "void-aug31", status: "DRAFT", notes: "Auto-created draft run for the current payroll period.", createdAt: "2026-08-24T00:00:00.000Z" }],
    entries: [],
    workEntries: [],
    referenceDate: "2026-08-26",
    previous: 2,
    next: 2,
  });
  const active = result.periods.filter((period) => period.status !== "VOID");
  assert.deepEqual(active.map((period) => [period.periodStart, period.periodEnd]).sort(), [
    ["2026-08-31", "2026-09-06"],
    ["2026-09-07", "2026-09-13"],
    ["2026-09-14", "2026-09-20"],
  ]);
  assert.equal(result.periods.filter((period) => period.periodStart === "2026-08-31" && period.status !== "VOID").length, 1);
  assert.equal(result.periods.filter((period) => period.periodStart === "2026-09-07" && period.status !== "VOID").length, 1);
  assert.equal(result.periods.filter((period) => period.periodStart === "2026-09-14").length, 1);
  assert.equal(result.periods.filter((period) => period.status === "VOID").length, 2, "immutable reset tombstones must remain present");
  assert.equal(result.createdPeriods.length, 2);
  assert.deepEqual(result.retiredRunIds, ["void-run"]);
  assert.equal(result.runs.length, 0, "an empty auto-run attached to a locked VOID tombstone is disposable");
  assert.equal(result.selectedPeriodId, result.periods.find((period) => period.periodStart === "2026-08-31" && period.status !== "VOID")?.id);
  assert.equal(result.periods.some((period) => period.status === "OPEN" && period.periodStart > "2026-08-26"), false);
});

test("a continuous version chain carries the weekly horizon across its boundary", () => {
  const v1 = version({ id: "schedule-1-v1", version: 1, effectiveTo: "2026-09-13" });
  const v2 = version({ id: "schedule-1-v2", version: 2, effectiveFrom: "2026-09-14" });
  const schedule = weeklySchedule({ versions: [v1, v2] });

  assert.equal(resolvePayrollScheduleVersion(schedule, "2026-08-26")?.id, "schedule-1-v1");
  assert.equal(resolvePayrollScheduleVersion(schedule, "2026-09-14")?.id, "schedule-1-v2");
  assert.deepEqual(generatePayrollPeriodsAroundReference(schedule, "2026-08-26", { previous: 2, next: 2 }).map((period) => [period.periodStart, period.periodEnd, period.scheduleVersionId]), [
    ["2026-08-31", "2026-09-06", "schedule-1-v1"],
    ["2026-09-07", "2026-09-13", "schedule-1-v1"],
    ["2026-09-14", "2026-09-20", "schedule-1-v2"],
  ]);
});

test("an uncovered version gap is not filled by an out-of-range fallback version", () => {
  const v1 = version({ id: "schedule-1-v1", version: 1, effectiveTo: "2026-08-30" });
  const v2 = version({ id: "schedule-1-v2", version: 2, effectiveFrom: "2026-09-14" });
  const schedule = weeklySchedule({ versions: [v1, v2] });

  assert.equal(resolvePayrollScheduleVersion(schedule, "2026-09-07"), undefined);
  assert.equal(findFirstGeneratablePayrollPeriod(schedule, "2026-08-26"), undefined);
  assert.deepEqual(generatePayrollPeriodsAroundReference(schedule, "2026-08-26", { previous: 2, next: 2 }), []);
  const validation = validatePayrollSchedule(schedule);
  assert.equal(validation.valid, false);
  assert.ok(validation.issues.some((issue) => issue.includes("uncovered date gap")));
});

test("a safe future version gap is repaired before rebuilding a lone later period", () => {
  const v1 = version({ id: "schedule-1-v1", version: 1, effectiveTo: "2026-08-30" });
  const v2 = version({ id: "schedule-1-v2", version: 2, effectiveFrom: "2026-09-14" });
  const schedule = weeklySchedule({ versions: [v1, v2] });
  const later = storedPeriod("sep14", "2026-09-14", "2026-09-20", "DRAFT", { scheduleVersionId: v2.id });

  const repair = repairFuturePayrollScheduleVersionGaps(schedule, "2026-08-26", { periods: [later], runs: [], entries: [], workEntries: [] });
  assert.equal(repair.repaired, true);
  assert.deepEqual(repair.repairedGaps.map((gap) => [gap.gapStart, gap.gapEnd]), [["2026-08-31", "2026-09-13"]]);
  assert.equal(repair.schedule.versions?.find((candidate) => candidate.id === v1.id)?.effectiveTo, "2026-09-13");

  const ensured = ensurePayrollPeriodsAndRuns({
    schedules: [schedule],
    periods: [later],
    runs: [],
    entries: [],
    workEntries: [],
    referenceDate: "2026-08-26",
    previous: 2,
    next: 2,
  });
  assert.deepEqual(ensured.periods.map((period) => [period.periodStart, period.periodEnd]).sort(), [
    ["2026-08-31", "2026-09-06"],
    ["2026-09-07", "2026-09-13"],
    ["2026-09-14", "2026-09-20"],
  ]);
  assert.equal(ensured.periods.filter((period) => period.periodStart === "2026-09-14").length, 1);
  assert.equal(ensured.selectedPeriodId, ensured.periods.find((period) => period.periodStart === "2026-08-31")?.id);
  assert.equal(ensured.periods.some((period) => period.status === "OPEN"), false);
  assert.equal(ensured.schedules?.[0]?.versions?.find((candidate) => candidate.id === v1.id)?.effectiveTo, "2026-09-13");
});

test("a future version gap with source data remains manual review", () => {
  const v1 = version({ id: "schedule-1-v1", version: 1, effectiveTo: "2026-08-30" });
  const v2 = version({ id: "schedule-1-v2", version: 2, effectiveFrom: "2026-09-14" });
  const schedule = weeklySchedule({ versions: [v1, v2] });
  const repair = repairFuturePayrollScheduleVersionGaps(schedule, "2026-08-26", {
    periods: [],
    runs: [],
    entries: [],
    workEntries: [{ id: "work-gap", workerId: "worker-1", workDate: "2026-09-02", regularHours: 8, overtimeHours: 0, daysWorked: 1, rate: 100, status: "DRAFT" }],
  });
  assert.equal(repair.repaired, false);
  assert.equal(repair.unresolvedGaps.length, 1);
  assert.equal(repair.schedule, schedule);
});

test("actual-current lifecycle opens and creates a run only after a weekly boundary is active", () => {
  const schedule = weeklySchedule();
  const before = ensurePayrollPeriodsAndRuns({ schedules: [schedule], periods: [], runs: [], entries: [], workEntries: [], referenceDate: "2026-08-26", previous: 2, next: 2 });
  const current = ensurePayrollPeriodsAndRuns({ schedules: [schedule], periods: before.periods, runs: before.runs, entries: [], workEntries: [], referenceDate: "2026-09-02", previous: 2, next: 2 });

  const active = current.periods.find((period) => period.periodStart === "2026-08-31" && period.periodEnd === "2026-09-06");
  assert.ok(active);
  assert.equal(active!.status, "OPEN");
  assert.equal(current.selectedPeriodId, active!.id);
  assert.equal(current.createdRuns.length, 1);
  assert.equal(current.createdRuns[0]?.periodId, active!.id);
  assert.equal(current.periods.some((period) => period.periodStart > "2026-09-02" && period.status === "OPEN"), false);
});
