import test from "node:test";
import assert from "node:assert/strict";
import type { PayrollEntry, PayrollPeriod, PayrollRun } from "../src/types.ts";
import {
  payrollPeriodFrequencyLabel,
  planPayrollRepair,
  previewSafePayrollReset,
  validatePayrollPeriodAgainstSchedule,
} from "../src/lib/payrollIntegrity.ts";
import type { PayrollSchedule, PayrollScheduleVersion } from "../src/lib/payrollSchedule.ts";
import { validatePayrollPeriodShape } from "../src/lib/payrollSchedule.ts";

function version(overrides: Partial<PayrollScheduleVersion> = {}): PayrollScheduleVersion {
  return {
    id: "schedule-v1",
    scheduleId: "schedule-1",
    version: 1,
    effectiveFrom: "2026-01-01",
    frequency: "SEMI_MONTHLY",
    customCutoffDay: 15,
    payDateRule: { type: "SAME_PERIOD_END" },
    autoGeneratePeriods: true,
    autoCalculate: false,
    autoCreateRuns: true,
    active: true,
    ...overrides,
  };
}

function schedule(overrides: Partial<PayrollSchedule> = {}): PayrollSchedule {
  return {
    id: "schedule-1",
    effectiveFrom: "2026-01-01",
    frequency: "SEMI_MONTHLY",
    customCutoffDay: 15,
    payDateRule: { type: "SAME_PERIOD_END" },
    autoGeneratePeriods: true,
    autoCalculate: false,
    autoCreateRuns: true,
    active: true,
    versions: [version()],
    ...overrides,
  };
}

function period(overrides: Partial<PayrollPeriod> = {}): PayrollPeriod {
  return { id: "period-1", periodStart: "2026-09-01", periodEnd: "2026-09-15", scheduleId: "schedule-1", scheduleVersionId: "schedule-v1", autoGenerated: true, status: "DRAFT", createdAt: "2026-08-01T00:00:00.000Z", updatedAt: "2026-08-01T00:00:00.000Z", ...overrides };
}

test("validates daily, weekly, biweekly, semi-monthly, monthly, and custom shapes", () => {
  const shapes: Array<[PayrollScheduleVersion, string, string]> = [
    [version({ id: "daily", frequency: "DAILY" }), "2026-09-01", "2026-09-01"],
    [version({ id: "weekly", frequency: "WEEKLY", weekEndDay: 0, anchorPeriodEnd: "2026-09-06" }), "2026-08-31", "2026-09-06"],
    [version({ id: "biweekly", frequency: "BIWEEKLY", anchorPeriodEnd: "2026-09-12" }), "2026-08-30", "2026-09-12"],
    [version({ id: "semi", frequency: "SEMI_MONTHLY" }), "2028-02-16", "2028-02-29"],
    [version({ id: "monthly", frequency: "MONTHLY" }), "2028-02-01", "2028-02-29"],
    [version({ id: "custom", frequency: "CUSTOM", customPeriodLengthDays: 5, anchorPeriodEnd: "2026-09-05" }), "2026-09-01", "2026-09-05"],
  ];
  for (const [candidate, start, end] of shapes) assert.equal(validatePayrollPeriodShape({ periodStart: start, periodEnd: end, scheduleId: candidate.scheduleId, scheduleVersionId: candidate.id }, candidate).valid, true, candidate.frequency);
  assert.equal(validatePayrollPeriodShape({ periodStart: "2028-02-01", periodEnd: "2028-02-15" }, version({ frequency: "SEMI_MONTHLY" })).valid, true);
});

test("rejects invalid fixed-frequency boundaries and period/version mismatches", () => {
  const weekly = version({ id: "weekly", frequency: "WEEKLY", weekEndDay: 0, anchorPeriodEnd: "2026-09-06" });
  const biweekly = version({ id: "biweekly", frequency: "BIWEEKLY", anchorPeriodEnd: "2026-09-12" });
  const monthly = version({ id: "monthly", frequency: "MONTHLY" });
  assert.equal(validatePayrollPeriodShape({ periodStart: "2026-09-01", periodEnd: "2026-09-15" }, weekly).valid, false);
  assert.equal(validatePayrollPeriodShape({ periodStart: "2026-08-31", periodEnd: "2026-09-07" }, weekly).valid, false);
  assert.equal(validatePayrollPeriodShape({ periodStart: "2026-08-31", periodEnd: "2026-09-12" }, biweekly).valid, false);
  assert.equal(validatePayrollPeriodShape({ periodStart: "2026-09-02", periodEnd: "2026-09-30" }, monthly).valid, false);
  assert.equal(validatePayrollPeriodShape({ periodStart: "2026-09-02", periodEnd: "2026-09-15" }, version({ frequency: "SEMI_MONTHLY" })).valid, false);
  const configured = schedule({ versions: [version({ id: "semi-v1", frequency: "SEMI_MONTHLY" }), version({ id: "weekly-v2", version: 2, frequency: "WEEKLY", weekEndDay: 0, anchorPeriodEnd: "2026-09-06", effectiveFrom: "2026-09-01" })] });
  const mismatched = period({ scheduleVersionId: "weekly-v2" });
  assert.equal(validatePayrollPeriodAgainstSchedule(mismatched, [configured]).valid, false);
});

test("repair deterministically retires duplicate empty periods and runs idempotently", () => {
  const primary = period({ id: "period-a" });
  const duplicate = period({ id: "period-b", createdAt: "2026-08-02T00:00:00.000Z" });
  const runA: PayrollRun = { id: "run-a", periodId: primary.id, status: "DRAFT", createdAt: "2026-08-01T00:00:00.000Z" };
  const runB: PayrollRun = { id: "run-b", periodId: primary.id, status: "DRAFT", createdAt: "2026-08-02T00:00:00.000Z" };
  const plan = planPayrollRepair({ schedules: [schedule()], periods: [primary, duplicate], runs: [runA, runB], desiredPeriods: [], referenceDate: "2026-09-01" });
  assert.deepEqual(plan.retiredPeriodIds, ["period-b"]);
  assert.deepEqual(plan.retiredRunIds, ["run-b"]);
  const again = planPayrollRepair({ schedules: [schedule()], periods: plan.periods, runs: plan.runs, desiredPeriods: [], referenceDate: "2026-09-01" });
  assert.deepEqual(again.retiredPeriodIds, []);
  assert.deepEqual(again.retiredRunIds, []);
});

test("repair protects finalized and data-bearing history and reconciles stale future periods", () => {
  const safeOld = period({ id: "semi-monthly", periodStart: "2026-09-01", periodEnd: "2026-09-15" });
  const protectedPeriod = period({ id: "approved", status: "APPROVED", lockedAt: "2026-09-15T00:00:00.000Z" });
  const dataPeriod = period({ id: "data-bearing" });
  const dataRun: PayrollRun = { id: "data-run", periodId: dataPeriod.id, status: "DRAFT", createdAt: "2026-09-01T00:00:00.000Z" };
  const entry: PayrollEntry = { id: "entry", payrollRunId: dataRun.id, workerId: "worker", basePay: 100, regularPay: 100, overtimePay: 0, allowances: 0, grossPay: 100, deductions: 0, netPay: 100, projectAllocatedCost: 100 };
  const weekly = period({ id: "weekly", periodStart: "2026-09-14", periodEnd: "2026-09-20", scheduleVersionId: "weekly-v2" });
  const plan = planPayrollRepair({ schedules: [schedule()], periods: [safeOld, protectedPeriod, dataPeriod], runs: [dataRun], entries: [entry], desiredPeriods: [weekly], referenceDate: "2026-09-01" });
  assert.equal(plan.periods.find((candidate) => candidate.id === safeOld.id)?.status, "VOID");
  assert.equal(plan.periods.find((candidate) => candidate.id === protectedPeriod.id)?.status, "APPROVED");
  assert.equal(plan.periods.find((candidate) => candidate.id === dataPeriod.id)?.status, "DRAFT");
});

test("safe reset preview reports protected rows without exposing internal identifiers", () => {
  const empty = period({ id: "empty" });
  const locked = period({ id: "locked", status: "PAID", lockedAt: "2026-09-15T00:00:00.000Z" });
  const preview = previewSafePayrollReset({ schedules: [schedule()], periods: [empty, locked], runs: [], referenceDate: "2026-09-01" });
  assert.equal(preview.safeGeneratedPeriods, 1);
  assert.equal(preview.protectedPeriods, 1);
  assert.ok(preview.messages.every((message) => !message.includes("empty") || !message.includes("period-")));
});

test("historical frequency presentation follows the own schedule version", () => {
  const configured = schedule({ frequency: "WEEKLY", versions: [version({ id: "semi-v1", frequency: "SEMI_MONTHLY" }), version({ id: "weekly-v2", version: 2, frequency: "WEEKLY", effectiveFrom: "2026-09-16", weekEndDay: 0, anchorPeriodEnd: "2026-09-20" })] });
  assert.equal(payrollPeriodFrequencyLabel(period({ scheduleVersionId: "semi-v1" }), [configured]), "SEMI MONTHLY");
  assert.equal(payrollPeriodFrequencyLabel(period({ scheduleVersionId: undefined }), [configured]), "Legacy payroll period");
});
