import test from "node:test";
import assert from "node:assert/strict";
import type { InvoiceData, InvoiceProjectAllocation, Project } from "../src/types.ts";
import { filterProjects, findBestProjectMatch, getProjectInvoiceAllocationPresentation, normalizeProjectText, rankProjectMatches } from "../src/utils/projectMatching.ts";

function project(overrides: Partial<Project> = {}): Project { return { id: "project-1", projectCode: "NB-2026", projectName: "North Bridge Package", clientName: "Acme Infrastructure", location: "Quezon City", projectManager: "Mara Santos", status: "ACTIVE", projectBudget: 100000, currency: "PHP", createdAt: "2026-08-23", updatedAt: "2026-08-23", ...overrides }; }
function invoice(overrides: Partial<InvoiceData> = {}): InvoiceData { return { id: "invoice-1", invoiceNumber: "INV-001", invoiceDate: "2026-08-23", projectReference: "NB 2026", currency: "PHP", grandTotal: 10000, vendor: { name: "ConcreteGrid Materials" }, customer: { name: "Acme Infrastructure" }, items: [], subtotal: 10000, totalTax: 0, extractedAt: "2026-08-23", modelUsed: "test", ...overrides }; }

test("project matching normalizes OCR punctuation and prioritizes an exact reference", () => { const results = rankProjectMatches(invoice(), [project({ id: "weaker", projectCode: "OTHER-1", projectName: "Road Repairs", clientName: "Acme Infrastructure" }), project({ id: "exact" })]); assert.equal(results[0]?.project.id, "exact"); assert.equal(results[0]?.confidence, "EXACT"); assert.ok(results[0]?.matchedFields.includes("code")); assert.equal(normalizeProjectText(" NB–2026 / Québec "), "nb 2026 quebec"); });
test("project search excludes archived projects by default", () => { const matches = filterProjects([project({ id: "bridge" }), project({ id: "warehouse", projectCode: "WH-1", projectName: "Warehouse Retrofit", clientName: "Acme Infrastructure", location: "Cebu" }), project({ id: "archived", projectName: "North Bridge Archive", status: "ARCHIVED", archivedAt: "2026-08-22T00:00:00Z" })], { query: "acme infrastructure cebu" }); assert.deepEqual(matches.map((item) => item.id), ["warehouse"]); assert.equal(filterProjects([project({ id: "archived", status: "ARCHIVED" })], { includeArchived: true }).length, 1); });
test("allocation presentation distinguishes full, partial, and unallocated invoice cost", () => { const partial: InvoiceProjectAllocation = { id: "a", invoiceId: "invoice-1", projectId: "project-1", allocationType: "PERCENTAGE", allocationPercentage: 25, allocationAmount: 2500 }; assert.equal(getProjectInvoiceAllocationPresentation(invoice(), partial, "ALLOCATION").allocationStatus, "PARTIAL"); assert.equal(getProjectInvoiceAllocationPresentation(invoice(), partial, "ALLOCATION").allocatedAmount, 2500); assert.equal(getProjectInvoiceAllocationPresentation(invoice(), { ...partial, allocationType: "AMOUNT", allocationPercentage: undefined, allocationAmount: 10000 }, "ALLOCATION").allocationStatus, "ALLOCATED"); assert.equal(getProjectInvoiceAllocationPresentation(invoice(), undefined, "PROJECT_REFERENCE").allocationStatus, "UNALLOCATED"); });
test("best project match is deterministic", () => { const matches = rankProjectMatches({ projectName: "Shared Package" }, [project({ id: "project-z", projectCode: "SHARED-Z", projectName: "Shared Package" }), project({ id: "project-a", projectCode: "SHARED-A", projectName: "Shared Package" })]); assert.equal(findBestProjectMatch({ projectName: "Shared Package" }, matches.map((match) => match.project))?.project.id, "project-a"); });

