import React from "react";
import { Plus, Receipt, Trash2 } from "lucide-react";
import { Expense } from "../../types";

interface ProjectExpensesProps { projectId: string; currency: string; expenses: Expense[]; onAdd?: () => void; onArchive?: (expense: Expense) => void; }
function money(value: number, currency: string) { try { return new Intl.NumberFormat("en-PH", { style: "currency", currency, maximumFractionDigits: 2 }).format(value || 0); } catch { return `${currency} ${(value || 0).toFixed(2)}`; } }

export const ProjectExpenses: React.FC<ProjectExpensesProps> = ({ currency, expenses, onAdd, onArchive }) => <section className="bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden"><div className="p-5 border-b border-slate-100 flex items-center justify-between gap-3"><div><h3 className="text-sm font-black">Project expenses</h3><p className="text-xs text-slate-500 mt-1">Direct costs stay separate from supplier invoices.</p></div>{onAdd && <button onClick={onAdd} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-xl bg-indigo-600 text-white text-xs font-bold"><Plus className="w-3.5 h-3.5" /> Add expense</button>}</div>{expenses.length ? <div className="divide-y divide-slate-100">{expenses.map((expense) => <div key={expense.id} className="px-5 py-4 flex items-center justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2 flex-wrap"><p className="text-xs font-bold truncate">{expense.description}</p><span className="px-2 py-0.5 rounded-full bg-slate-100 text-[9px] font-black text-slate-600">{expense.status}</span></div><p className="text-[10px] text-slate-500 mt-1">{expense.expenseDate} • {expense.category}{expense.payee ? ` • ${expense.payee}` : ""}</p></div><div className="flex items-center gap-2 shrink-0"><p className="text-xs font-black font-sans tabular-nums">{money(expense.amount, expense.currency || currency)}</p>{onArchive && expense.status !== "VOID" && <button onClick={() => onArchive(expense)} className="p-2 rounded-lg text-slate-400 hover:bg-rose-50 hover:text-rose-700" aria-label="Archive expense"><Trash2 className="w-3.5 h-3.5" /></button>}</div></div>)}</div> : <div className="p-10 text-center"><Receipt className="w-8 h-8 mx-auto text-slate-300" /><p className="mt-3 text-sm font-bold text-slate-700">No additional expenses recorded.</p><p className="text-xs text-slate-500 mt-1">Add fuel, transport, permits, meals, or other direct costs here.</p></div>}</section>;

