/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\ui\engoryxTheme.ts
 * Command: astryx theme build src\ui\engoryxTheme.ts --out src\ui\engoryx.css
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const engoryxIconRegistry: IconRegistry;
export declare const engoryxTheme: DefinedTheme;
