/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\ui\engoryxTheme.ts
 * Command: astryx theme build src\ui\engoryxTheme.ts --out src\ui\engoryx.css
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

import { engoryxIconRegistry } from "./icons.ts";
/**
 * engoryx theme — built by `bunx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { engoryxTheme } from './engoryx';
 *   import './engoryx.css';
 */
export const engoryxTheme = {
  name: 'engoryx',
  __built: true,
  tokens: {
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.4375rem",
    "--font-size-2xs": "0.5625rem",
    "--font-size-xs": "0.625rem",
    "--font-size-sm": "0.75rem",
    "--font-size-base": "0.875rem",
    "--font-size-lg": "1.0625rem",
    "--font-size-xl": "1.1875rem",
    "--font-size-2xl": "1.4375rem",
    "--font-size-3xl": "1.6875rem",
    "--font-size-4xl": "2rem",
    "--font-size-5xl": "2.375rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-bold)",
    "--text-heading-1-leading": "1.3913",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-bold)",
    "--text-heading-2-leading": "1.4737",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-bold)",
    "--text-heading-3-leading": "1.4118",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-bold)",
    "--text-heading-4-leading": "1.4286",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.6667",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.6",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.4286",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4118",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.4286",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.4286",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.6667",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.2632",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.25",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.3333",
    "--duration-fast-min": "90ms",
    "--duration-fast": "120ms",
    "--duration-fast-max": "160ms",
    "--duration-medium-min": "180ms",
    "--duration-medium": "240ms",
    "--duration-medium-max": "320ms",
    "--duration-slow-min": "340ms",
    "--duration-slow": "450ms",
    "--duration-slow-max": "600ms",
    "--font-family-body": "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
    "--font-family-heading": "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
    "--font-family-code": "ui-monospace, \"SF Mono\", Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
    "--color-syntax-keyword": "light-dark(#4f46e5, #818cf8)",
    "--color-syntax-string": "light-dark(#059669, #34d399)",
    "--color-syntax-comment": "light-dark(#64748b, #94a3b8)",
    "--color-syntax-number": "light-dark(#d97706, #fbbf24)",
    "--color-syntax-function": "light-dark(#2563eb, #60a5fa)",
    "--color-syntax-type": "light-dark(#7c3aed, #a78bfa)",
    "--color-syntax-variable": "light-dark(#0f172a, #f8fafc)",
    "--color-syntax-operator": "light-dark(#475569, #94a3b8)",
    "--color-syntax-constant": "light-dark(#ea580c, #fb923c)",
    "--color-syntax-tag": "light-dark(#e11d48, #f43f5e)",
    "--color-syntax-attribute": "light-dark(#0284c7, #38bdf8)",
    "--color-syntax-property": "light-dark(#0d9488, #2dd4bf)",
    "--color-syntax-punctuation": "light-dark(#94a3b8, #64748b)",
    "--color-syntax-background": "light-dark(#f8fafc, #0f172a)",
    "--color-background-surface": "light-dark(#ffffff, #1e293b)",
    "--color-background-body": "light-dark(#f8fafc, #0f172a)",
    "--color-background-card": "light-dark(#ffffff, #1e293b)",
    "--color-background-popover": "light-dark(#ffffff, #1e293b)",
    "--color-background-muted": "light-dark(#f1f5f9, #1e293b)",
    "--color-accent": "light-dark(#4f46e5, #818cf8)",
    "--color-accent-muted": "light-dark(#eef2ff, #312e81)",
    "--color-neutral": "light-dark(#0000000D, #FFFFFF14)",
    "--color-overlay": "light-dark(#0f172a80, #000000CC)",
    "--color-overlay-hover": "light-dark(#00000008, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#00000014, #FFFFFF1A)",
    "--color-text-primary": "light-dark(#0f172a, #f8fafc)",
    "--color-text-secondary": "light-dark(#475569, #94a3b8)",
    "--color-text-disabled": "light-dark(#94a3b8, #64748b)",
    "--color-text-accent": "light-dark(#4f46e5, #818cf8)",
    "--color-on-dark": "#ffffff",
    "--color-on-light": "#0f172a",
    "--color-on-accent": "light-dark(#ffffff, #0f172a)",
    "--color-on-success": "light-dark(#ffffff, #0f172a)",
    "--color-on-error": "light-dark(#ffffff, #0f172a)",
    "--color-on-warning": "#0f172a",
    "--color-icon-accent": "light-dark(#4f46e5, #818cf8)",
    "--color-icon-primary": "light-dark(#0f172a, #f8fafc)",
    "--color-icon-secondary": "light-dark(#64748b, #94a3b8)",
    "--color-icon-disabled": "light-dark(#94a3b8, #64748b)",
    "--color-success": "light-dark(#059669, #34d399)",
    "--color-error": "light-dark(#e11d48, #f43f5e)",
    "--color-warning": "light-dark(#d97706, #fbbf24)",
    "--color-success-muted": "light-dark(#ecfdf5, #064e3b3D)",
    "--color-error-muted": "light-dark(#fff1f2, #8813373D)",
    "--color-warning-muted": "light-dark(#fffbeb, #78350f3D)",
    "--color-border": "light-dark(#e2e8f0, #334155)",
    "--color-border-emphasized": "light-dark(#cbd5e1, #475569)",
    "--color-skeleton": "light-dark(#e2e8f0, #334155)",
    "--color-shadow": "light-dark(#0f172a0f, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--color-background-blue": "light-dark(#e0f2fe, #0369a13D)",
    "--color-border-blue": "light-dark(#bae6fd, #38bdf8)",
    "--color-icon-blue": "light-dark(#0284c7, #38bdf8)",
    "--color-text-blue": "light-dark(#0369a1, #7dd3fc)",
    "--color-background-green": "light-dark(#dcfce7, #15803d3D)",
    "--color-border-green": "light-dark(#bbf7d0, #4ade80)",
    "--color-icon-green": "light-dark(#16a34a, #4ade80)",
    "--color-text-green": "light-dark(#15803d, #86efac)",
    "--color-background-yellow": "light-dark(#fef9c3, #a162073D)",
    "--color-border-yellow": "light-dark(#fde047, #eab308)",
    "--color-icon-yellow": "light-dark(#ca8a04, #facc15)",
    "--color-text-yellow": "light-dark(#a16207, #fde047)",
    "--color-background-red": "light-dark(#ffe4e6, #be123c3D)",
    "--color-border-red": "light-dark(#fecdd3, #fb7185)",
    "--color-icon-red": "light-dark(#e11d48, #fb7185)",
    "--color-text-red": "light-dark(#be123c, #fda4af)",
    "--color-background-purple": "light-dark(#f3e8ff, #7e22ce3D)",
    "--color-border-purple": "light-dark(#e9d5ff, #c084fc)",
    "--color-icon-purple": "light-dark(#9333ea, #c084fc)",
    "--color-text-purple": "light-dark(#7e22ce, #d8b4fe)",
    "--color-background-orange": "light-dark(#ffedd5, #c2410c3D)",
    "--color-border-orange": "light-dark(#fed7aa, #fb923c)",
    "--color-icon-orange": "light-dark(#ea580c, #fb923c)",
    "--color-text-orange": "light-dark(#c2410c, #fdba74)",
    "--color-background-teal": "light-dark(#ccfbf1, #0f766e3D)",
    "--color-border-teal": "light-dark(#99f6e4, #2dd4bf)",
    "--color-icon-teal": "light-dark(#0d9488, #2dd4bf)",
    "--color-text-teal": "light-dark(#0f766e, #5eead4)",
    "--color-background-cyan": "light-dark(#cffafe, #0e74903D)",
    "--color-border-cyan": "light-dark(#a5f3fc, #22d3ee)",
    "--color-icon-cyan": "light-dark(#0891b2, #22d3ee)",
    "--color-text-cyan": "light-dark(#0e7490, #67e8f9)",
    "--color-background-pink": "light-dark(#fce7f3, #be185d3D)",
    "--color-border-pink": "light-dark(#fbcfe8, #f472b6)",
    "--color-icon-pink": "light-dark(#db2777, #f472b6)",
    "--color-text-pink": "light-dark(#be185d, #f9a8d4)",
    "--color-background-gray": "light-dark(#f1f5f9, #1e293b)",
    "--color-border-gray": "light-dark(#e2e8f0, #334155)",
    "--color-icon-gray": "light-dark(#64748b, #94a3b8)",
    "--color-text-gray": "light-dark(#334155, #cbd5e1)",
    "--radius-none": "0px",
    "--radius-inner": "0.375rem",
    "--radius-element": "0.5rem",
    "--radius-container": "0.75rem",
    "--radius-page": "1.25rem",
    "--radius-full": "9999px",
    "--shadow-low": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
    "--shadow-med": "0 4px 6px -1px rgb(0 0 0 / 0.07), 0 2px 4px -2px rgb(0 0 0 / 0.05)",
    "--shadow-high": "0 10px 15px -3px rgb(0 0 0 / 0.08), 0 4px 6px -4px rgb(0 0 0 / 0.04)",
    "--shadow-inset-hover": "inset 0px 0px 0px 2px #4f46e54D",
    "--shadow-inset-selected": "inset 0px 0px 0px 2px #4f46e580",
    "--shadow-inset-success": "inset 0px 0px 0px 2px #0596694D",
    "--shadow-inset-warning": "inset 0px 0px 0px 2px #d977064D",
    "--shadow-inset-error": "inset 0px 0px 0px 2px #e11d484D"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "variant:primary": {
        "backgroundColor": "var(--color-accent)",
        "color": "#ffffff"
      },
      "variant:destructive": {
        "backgroundColor": "var(--color-error-muted)",
        "color": "var(--color-error)"
      }
    },
    "card": {
      "base": {
        "padding": "var(--spacing-3)"
      }
    },
    "badge": {
      "variant:info": {
        "backgroundColor": "light-dark(#e0f2fe, #0369a13D)",
        "color": "light-dark(#0369a1, #7dd3fc)"
      },
      "variant:success": {
        "backgroundColor": "light-dark(#dcfce7, #15803d3D)",
        "color": "light-dark(#15803d, #86efac)"
      },
      "variant:warning": {
        "backgroundColor": "light-dark(#fef9c3, #a162073D)",
        "color": "light-dark(#a16207, #fde047)"
      },
      "variant:error": {
        "backgroundColor": "light-dark(#ffe4e6, #be123c3D)",
        "color": "light-dark(#be123c, #fda4af)"
      },
      "variant:neutral": {
        "backgroundColor": "var(--color-background-gray)",
        "color": "var(--color-text-gray)"
      }
    },
    "statusdot": {
      "variant:success": {
        "backgroundColor": "light-dark(#059669, #34d399)"
      },
      "variant:warning": {
        "backgroundColor": "light-dark(#d97706, #fbbf24)"
      },
      "variant:error": {
        "backgroundColor": "light-dark(#e11d48, #f43f5e)"
      },
      "variant:accent": {
        "backgroundColor": "light-dark(#4f46e5, #818cf8)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  icons: engoryxIconRegistry,
};

export { engoryxIconRegistry };
