/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\ui\hydroqualisenseTheme.ts
 * Command: astryx theme build src\ui\hydroqualisenseTheme.ts --out src\ui\hydroqualisense.css
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const hydroqualisenseIconRegistry: IconRegistry;
export declare const hydroqualisenseTheme: DefinedTheme;
