import { WORKFLOW_GRAPH as BASE_WORKFLOW_GRAPH } from "./graph.ts";
import type { WorkflowEdge, WorkflowGraph, WorkflowInvariant, WorkflowNode } from "./types.ts";

const procurementRefs = [
  "src/components/procurement/ProcurementPage.tsx",
  "src/lib/purchaseOrders.ts",
  "src/lib/rfqs.ts",
  "src/utils/projectCosting.ts",
] as const;

const commercialRefs = [
  "src/lib/subcontracts.ts",
  "src/lib/subcontractClaims.ts",
  "src/lib/subcontractVariations.ts",
  "src/utils/projectCosting.ts",
] as const;

const procurementTests = ["tests/procurementProjectCostIntegration.test.ts"] as const;
const commercialTests = [
  "tests/subcontractProjectCostIntegration.test.ts",
  "tests/subcontractVariations.test.ts",
] as const;

export const P2_WORKFLOW_INVARIANTS: readonly WorkflowInvariant[] = [
  {
    id: "procurement-po-commitment-not-actual",
    label: "Issued purchase orders are commitments, not actual cost",
    description: "Approved/issued purchase-order commitments contribute to Committed Cost only. They must not create or increase Actual Cost until a separate actual-cost source exists.",
    sourceClassification: "curated",
    fileRefs: ["src/lib/purchaseOrders.ts", "src/utils/projectCosting.ts"],
    testRefs: procurementTests,
  },
  {
    id: "procurement-rfq-precommitment",
    label: "RFQs and quotations remain pre-commitment",
    description: "RFQs, supplier quotations, and supplier selection are sourcing evidence only; they are neither Committed Cost nor Actual Cost. Commitment begins only through the purchase-order lifecycle.",
    sourceClassification: "curated",
    fileRefs: ["src/lib/rfqs.ts", "src/lib/purchaseOrders.ts", "src/utils/projectCosting.ts"],
    testRefs: procurementTests,
  },
  {
    id: "commercial-subcontract-remaining-commitment",
    label: "Eligible subcontracts contribute remaining commitment",
    description: "Eligible approved/active subcontracts contribute remaining commitment to project Committed Cost after certified progress is deducted.",
    sourceClassification: "curated",
    fileRefs: ["src/lib/subcontracts.ts", "src/lib/subcontractClaims.ts", "src/utils/projectCosting.ts"],
    testRefs: commercialTests,
  },
  {
    id: "commercial-progress-claim-certification-not-actual",
    label: "Progress claims certify work without creating actual cost",
    description: "Approved progress claims represent certified gross work and reduce remaining subcontract commitment. They must not automatically create Actual Cost, supplier invoices, payments, or settlement records.",
    sourceClassification: "curated",
    fileRefs: ["src/lib/subcontractClaims.ts", "src/utils/projectCosting.ts"],
    testRefs: ["tests/subcontractProjectCostIntegration.test.ts"],
  },
  {
    id: "commercial-approved-variation-revises-subcontract-only",
    label: "Only approved subcontract variations revise subcontract commitment",
    description: "Only APPROVED subcontract variations change revised subcontract value and remaining subcontract commitment. They must not alter projects.contract_value, projects.project_budget, or Actual Cost.",
    sourceClassification: "curated",
    fileRefs: ["src/lib/subcontractVariations.ts", "src/utils/projectCosting.ts"],
    testRefs: commercialTests,
  },
  {
    id: "p2-no-implicit-cross-currency-aggregation",
    label: "Do not aggregate unrelated currencies without explicit FX",
    description: "Procurement and subcontract commitments must not be summed across unrelated currencies unless an explicit exchange-rate conversion has been applied.",
    sourceClassification: "curated",
    fileRefs: ["src/lib/purchaseOrders.ts", "src/lib/subcontracts.ts", "src/utils/projectCosting.ts"],
    testRefs: ["tests/procurementProjectCostIntegration.test.ts", "tests/subcontractProjectCostIntegration.test.ts"],
  },
] as const;

export const P2_WORKFLOW_NODES: readonly WorkflowNode[] = [
  {
    id: "procurement-workspace",
    label: "Procurement Workspace",
    domain: "procurement",
    type: "screen",
    description: "Project procurement workspace covering purchase orders, receipts, supplier matching, RFQs, quotations, and conversion into draft purchase orders.",
    sourceClassification: "mixed",
    scope: "project",
    fileRefs: procurementRefs,
    testRefs: procurementTests,
    tags: ["procurement", "purchase order", "rfq", "supplier quotation"],
  },
  {
    id: "purchase-order-lifecycle",
    label: "Purchase Order Approval and Commitment",
    domain: "procurement",
    type: "workflow",
    description: "Creates and advances purchase orders through approval/issue states so eligible issued orders contribute to project committed cost.",
    sourceClassification: "mixed",
    scope: "project",
    fileRefs: ["src/lib/purchaseOrders.ts", "src/utils/projectCosting.ts"],
    testRefs: procurementTests,
    invariantIds: ["procurement-po-commitment-not-actual", "p2-no-implicit-cross-currency-aggregation"],
    tags: ["purchase order approval", "purchase order", "po approval", "issued po", "committed cost"],
  },
  {
    id: "purchase-order-receipts",
    label: "Purchase Order Goods and Delivery Receipts",
    domain: "procurement",
    type: "workflow",
    description: "Records goods/delivery receipt evidence against purchase orders without redefining the project actual-cost source of truth.",
    sourceClassification: "code-derived",
    scope: "project",
    fileRefs: ["src/lib/purchaseOrders.ts", "src/components/procurement/ProcurementPage.tsx"],
    testRefs: procurementTests,
    invariantIds: ["procurement-po-commitment-not-actual"],
    tags: ["goods receipt", "delivery receipt", "purchase order receipt"],
  },
  {
    id: "supplier-invoice-po-matching",
    label: "Supplier Invoice to Purchase Order Matching",
    domain: "procurement",
    type: "workflow",
    description: "Associates supplier invoice evidence with purchase orders while preserving the separate actual-cost and settlement workflow boundaries.",
    sourceClassification: "code-derived",
    scope: "project",
    fileRefs: ["src/lib/purchaseOrders.ts", "src/components/procurement/ProcurementPage.tsx"],
    testRefs: procurementTests,
    invariantIds: ["procurement-po-commitment-not-actual"],
    tags: ["supplier invoice", "po matching", "invoice purchase order match"],
  },
  {
    id: "procurement-rfq",
    label: "Request for Quotation",
    domain: "procurement",
    type: "workflow",
    description: "Creates and manages RFQs before a purchase commitment exists.",
    sourceClassification: "code-derived",
    scope: "project",
    fileRefs: ["src/lib/rfqs.ts", "src/components/procurement/ProcurementPage.tsx"],
    testRefs: procurementTests,
    invariantIds: ["procurement-rfq-precommitment"],
    tags: ["rfq", "request for quotation", "supplier sourcing"],
  },
  {
    id: "supplier-quotation-selection",
    label: "Supplier Quotations and Human Selection",
    domain: "procurement",
    type: "action",
    description: "Captures supplier quotations and keeps supplier selection as an explicit human sourcing decision before purchase-order commitment.",
    sourceClassification: "mixed",
    scope: "project",
    confirmationRequirement: "human",
    fileRefs: ["src/lib/rfqs.ts", "src/components/procurement/ProcurementPage.tsx"],
    testRefs: procurementTests,
    invariantIds: ["procurement-rfq-precommitment"],
    tags: ["supplier quotation", "supplier selection", "human selection", "quotation comparison"],
  },
  {
    id: "rfq-draft-po-conversion",
    label: "RFQ to Draft Purchase Order",
    domain: "procurement",
    type: "action",
    description: "Converts the selected RFQ/quotation outcome into a DRAFT purchase order; the conversion itself does not yet create committed or actual cost.",
    sourceClassification: "mixed",
    scope: "project",
    fileRefs: ["src/lib/rfqs.ts", "src/lib/purchaseOrders.ts"],
    testRefs: procurementTests,
    invariantIds: ["procurement-rfq-precommitment", "procurement-po-commitment-not-actual"],
    tags: ["rfq draft po", "convert rfq", "draft purchase order"],
  },
  {
    id: "subcontract-packages",
    label: "Subcontract Packages",
    domain: "commercial",
    type: "workflow",
    description: "Creates and maintains project subcontract packages that establish the commercial scope for subcontract commitments and claims.",
    sourceClassification: "code-derived",
    scope: "project",
    fileRefs: ["src/lib/subcontracts.ts"],
    testRefs: commercialTests,
    tags: ["subcontract", "subcontract package", "commercial"],
  },
  {
    id: "subcontract-commitment",
    label: "Subcontract Commitment",
    domain: "commercial",
    type: "derived-data",
    description: "Represents eligible approved/active subcontract value as project commitment before certified progress is deducted.",
    sourceClassification: "mixed",
    scope: "project",
    fileRefs: ["src/lib/subcontracts.ts", "src/utils/projectCosting.ts"],
    testRefs: commercialTests,
    invariantIds: ["commercial-subcontract-remaining-commitment", "p2-no-implicit-cross-currency-aggregation"],
    tags: ["subcontract commitment", "committed cost", "commercial commitment"],
  },
  {
    id: "subcontract-progress-claims",
    label: "Subcontract Progress Claims",
    domain: "commercial",
    type: "workflow",
    description: "Records subcontract progress claims and approved certification used to reduce remaining subcontract commitment.",
    sourceClassification: "code-derived",
    scope: "project",
    fileRefs: ["src/lib/subcontractClaims.ts", "src/utils/projectCosting.ts"],
    testRefs: ["tests/subcontractProjectCostIntegration.test.ts"],
    invariantIds: ["commercial-progress-claim-certification-not-actual", "commercial-subcontract-remaining-commitment"],
    tags: ["progress claim", "subcontract claim", "certified gross"],
  },
  {
    id: "subcontract-retention",
    label: "Subcontract Retention",
    domain: "commercial",
    type: "derived-data",
    description: "Tracks retention within subcontract claim certification while keeping it separate from payment or settlement creation.",
    sourceClassification: "code-derived",
    scope: "project",
    fileRefs: ["src/lib/subcontractClaims.ts"],
    testRefs: ["tests/subcontractProjectCostIntegration.test.ts"],
    invariantIds: ["commercial-progress-claim-certification-not-actual"],
    tags: ["subcontract retention", "retention", "progress claim retention"],
  },
  {
    id: "subcontract-variations",
    label: "Subcontract Variations and Change Orders",
    domain: "commercial",
    type: "workflow",
    description: "Manages subcontract variations/change orders; only APPROVED variations revise subcontract value and commitment.",
    sourceClassification: "code-derived",
    scope: "project",
    statusValues: ["DRAFT", "SUBMITTED", "APPROVED", "REJECTED"],
    fileRefs: ["src/lib/subcontractVariations.ts", "src/utils/projectCosting.ts"],
    testRefs: ["tests/subcontractVariations.test.ts", "tests/subcontractProjectCostIntegration.test.ts"],
    invariantIds: ["commercial-approved-variation-revises-subcontract-only", "p2-no-implicit-cross-currency-aggregation"],
    tags: ["subcontract variations", "subcontract variation", "change order", "approved variation"],
  },
  {
    id: "revised-subcontract-value",
    label: "Revised Subcontract Value",
    domain: "commercial",
    type: "derived-data",
    description: "Derives revised subcontract value from the base subcontract plus APPROVED variations only.",
    sourceClassification: "mixed",
    scope: "project",
    fileRefs: ["src/lib/subcontracts.ts", "src/lib/subcontractVariations.ts", "src/utils/projectCosting.ts"],
    testRefs: commercialTests,
    invariantIds: ["commercial-approved-variation-revises-subcontract-only"],
    tags: ["revised subcontract value", "approved variation value"],
  },
  {
    id: "remaining-subcontract-commitment",
    label: "Remaining Subcontract Commitment",
    domain: "commercial",
    type: "derived-data",
    description: "Derives remaining subcontract commitment from revised subcontract value less approved certified progress claims.",
    sourceClassification: "mixed",
    scope: "project",
    fileRefs: commercialRefs,
    testRefs: commercialTests,
    invariantIds: ["commercial-subcontract-remaining-commitment", "commercial-progress-claim-certification-not-actual", "commercial-approved-variation-revises-subcontract-only", "p2-no-implicit-cross-currency-aggregation"],
    tags: ["remaining subcontract commitment", "remaining commitment", "certified gross"],
  },
  {
    id: "project-budget-control",
    label: "Project Budget Control",
    domain: "projects",
    type: "derived-data",
    description: "Consumes project cost aggregation so actual and committed cost remain visible against the project budget without changing contract value or budget source fields.",
    sourceClassification: "mixed",
    scope: "project",
    fileRefs: ["src/utils/projectCosting.ts"],
    testRefs: ["tests/procurementProjectCostIntegration.test.ts", "tests/subcontractProjectCostIntegration.test.ts"],
    invariantIds: ["procurement-po-commitment-not-actual", "commercial-subcontract-remaining-commitment", "commercial-approved-variation-revises-subcontract-only", "p2-no-implicit-cross-currency-aggregation"],
    tags: ["project budget control", "project cost aggregation", "actual cost", "committed cost"],
  },
] as const;

export const P2_WORKFLOW_EDGES: readonly WorkflowEdge[] = [
  { id: "p2-project-procurement", source: "project-cost-aggregation", target: "procurement-workspace", type: "links-to", kind: "context", label: "project procurement contributes commitment context" },
  { id: "p2-procurement-po", source: "procurement-workspace", target: "purchase-order-lifecycle", type: "contains", kind: "context", label: "procurement manages purchase orders" },
  { id: "p2-po-committed-cost", source: "purchase-order-lifecycle", target: "project-cost-aggregation", type: "feeds", kind: "derived-data", label: "eligible issued PO contributes committed cost", invariantIds: ["procurement-po-commitment-not-actual"] },
  { id: "p2-po-receipts", source: "purchase-order-lifecycle", target: "purchase-order-receipts", type: "links-to", kind: "context", label: "purchase order receives goods/delivery evidence" },
  { id: "p2-po-invoice-match", source: "purchase-order-lifecycle", target: "supplier-invoice-po-matching", type: "links-to", kind: "context", label: "purchase order supports supplier invoice matching" },
  { id: "p2-rfq-quotations", source: "procurement-rfq", target: "supplier-quotation-selection", type: "feeds", kind: "read-flow", label: "RFQ collects supplier quotations for human selection", invariantIds: ["procurement-rfq-precommitment"] },
  { id: "p2-selection-draft-po", source: "supplier-quotation-selection", target: "rfq-draft-po-conversion", type: "executes-through", kind: "confirmation", label: "human supplier selection enables draft PO conversion", confirmationRequirement: "human", invariantIds: ["procurement-rfq-precommitment"] },
  { id: "p2-rfq-conversion-po", source: "rfq-draft-po-conversion", target: "purchase-order-lifecycle", type: "writes", kind: "mutation", label: "creates a DRAFT purchase order", invariantIds: ["procurement-rfq-precommitment", "procurement-po-commitment-not-actual"] },
  { id: "p2-subcontract-package-commitment", source: "subcontract-packages", target: "subcontract-commitment", type: "derives", kind: "derived-data", label: "eligible subcontract establishes commitment", invariantIds: ["commercial-subcontract-remaining-commitment"] },
  { id: "p2-subcontract-claim", source: "subcontract-commitment", target: "subcontract-progress-claims", type: "links-to", kind: "context", label: "subcontract receives progress claims" },
  { id: "p2-claim-retention", source: "subcontract-progress-claims", target: "subcontract-retention", type: "derives", kind: "derived-data", label: "claim certification derives retention", invariantIds: ["commercial-progress-claim-certification-not-actual"] },
  { id: "p2-variation-revised-value", source: "subcontract-variations", target: "revised-subcontract-value", type: "derives", kind: "derived-data", label: "APPROVED variation revises subcontract value", condition: "variation.status === APPROVED", invariantIds: ["commercial-approved-variation-revises-subcontract-only"] },
  { id: "p2-subcontract-revised-value", source: "subcontract-commitment", target: "revised-subcontract-value", type: "derives", kind: "derived-data", label: "base subcontract contributes to revised value" },
  { id: "p2-revised-value-claim", source: "revised-subcontract-value", target: "subcontract-progress-claims", type: "links-to", kind: "context", label: "progress claim is evaluated against revised subcontract value" },
  { id: "p2-claim-remaining-commitment", source: "subcontract-progress-claims", target: "remaining-subcontract-commitment", type: "derives", kind: "derived-data", label: "approved certified gross reduces remaining commitment", invariantIds: ["commercial-progress-claim-certification-not-actual", "commercial-subcontract-remaining-commitment"] },
  { id: "p2-revised-value-remaining-commitment", source: "revised-subcontract-value", target: "remaining-subcontract-commitment", type: "derives", kind: "derived-data", label: "revised subcontract value is the commitment basis", invariantIds: ["commercial-approved-variation-revises-subcontract-only"] },
  { id: "p2-subcontract-project-cost", source: "remaining-subcontract-commitment", target: "project-cost-aggregation", type: "feeds", kind: "derived-data", label: "remaining subcontract value contributes committed cost", invariantIds: ["commercial-subcontract-remaining-commitment"] },
  { id: "p2-cost-budget-control", source: "project-cost-aggregation", target: "project-budget-control", type: "feeds", kind: "derived-data", label: "actual and committed project costs feed budget control" },
] as const;

export const WORKFLOW_GRAPH: WorkflowGraph = {
  ...BASE_WORKFLOW_GRAPH,
  version: `${BASE_WORKFLOW_GRAPH.version}+p2-procurement-commercial`,
  canonicalSource: "scripts/workflow-map/p2-graph.ts",
  sourceClassification: "mixed",
  phaseTags: [...BASE_WORKFLOW_GRAPH.phaseTags, "P2-procurement-commercial"],
  invariants: [...BASE_WORKFLOW_GRAPH.invariants, ...P2_WORKFLOW_INVARIANTS],
  nodes: [...BASE_WORKFLOW_GRAPH.nodes, ...P2_WORKFLOW_NODES],
  edges: [...BASE_WORKFLOW_GRAPH.edges, ...P2_WORKFLOW_EDGES],
};
