import { defineQaScenario, QA_VIEWPORTS } from "./structuredEvidence.ts";
import type { QaScenarioDefinition, QaScenarioDefinitionInput } from "./structuredEvidence.ts";

export type DemoQaScenarioMetadataInput = Omit<QaScenarioDefinitionInput, "action"> & { readonly actionId?: string };
export type DemoQaScenarioMetadata = Omit<QaScenarioDefinition, "action"> & { readonly actionId?: string };

export function defineQaScenarioMetadata(input: DemoQaScenarioMetadataInput): DemoQaScenarioMetadata {
  const { actionId, ...scenario } = input;
  return { ...defineQaScenario(scenario), ...(actionId === undefined ? {} : { actionId }) };
}
export const PROJECT_ROOT = "/demo/app/projects/demo-project-warehouse";

export const R4C_VIEWPORTS = [
  { name: "r4c-desktop-1440", width: 1440, height: 1000 },
  { name: "r4c-laptop-1280", width: 1280, height: 800 },
  { name: "r4c-tablet-768", width: 768, height: 1024 },
  { name: "r4c-phone-390", width: 390, height: 844 },
] as const;

export const R4E_VIEWPORTS = [
  { name: "r4e-desktop-1440", width: 1440, height: 1000 },
  { name: "r4e-laptop-1280", width: 1280, height: 800 },
  { name: "r4e-tablet-768", width: 768, height: 1024 },
  { name: "r4e-phone-390", width: 390, height: 844 },
] as const;

export const UX_EDIT_1A_VIEWPORTS = [
  { name: "ux-edit-desktop-1440", width: 1440, height: 900 },
  { name: "ux-edit-laptop-1280", width: 1280, height: 800 },
  { name: "ux-edit-tablet-768", width: 768, height: 1024 },
  { name: "ux-edit-phone-390", width: 390, height: 844 },
] as const;

export const R4D_CONSTRAINED_LAPTOP = { name: "r4d-laptop-1280", width: 1280, height: 800 } as const;

export const R4D_TABLET = { name: "r4d-tablet-768", width: 768, height: 1024 } as const;

export function route(id: string, canonicalPath: string) {
  return { id, canonicalPath } as const;
}

export const R4E_VISUAL_ROUTES = [
  { id: "dashboard", canonicalPath: "/dashboard", path: "/demo/app/dashboard", label: "Home" },
  { id: "invoices", canonicalPath: "/invoices", path: "/demo/app/invoices", label: "Supplier Invoices" },
  { id: "review", canonicalPath: "/review?invoiceId=:invoiceId", path: "/demo/app/review?invoiceId=demo-invoice-07", label: "Invoice Review" },
  { id: "payroll", canonicalPath: "/payroll", path: "/demo/app/payroll", label: "Payroll" },
  { id: "inbox", canonicalPath: "/email-sms", path: "/demo/app/email-sms?view=compose", label: "Email and SMS" },
  { id: "cash", canonicalPath: "/cash", path: "/demo/app/cash", label: "Cash and Banking" },
  { id: "expenses", canonicalPath: "/expenses", path: "/demo/app/expenses", label: "Expenses" },
  { id: "procurement", canonicalPath: "/procurement", path: "/demo/app/procurement", label: "Procurement" },
  { id: "warehouse", canonicalPath: "/warehouse", path: "/demo/app/warehouse", label: "Warehouse" },
  { id: "equipment", canonicalPath: "/equipment", path: "/demo/app/equipment", label: "Equipment" },
  { id: "documents", canonicalPath: "/documents", path: "/demo/app/documents", label: "Documents" },
  { id: "reports", canonicalPath: "/reports", path: "/demo/app/reports", label: "Reports" },
  { id: "project-materials-equipment", canonicalPath: "/projects/:projectId/materials-equipment", path: "/demo/app/projects/demo-project-warehouse/materials-equipment", label: "Project Materials and Equipment" },
  { id: "rfis", canonicalPath: "/projects/:projectId/rfis", path: "/demo/app/projects/demo-project-warehouse/rfis", label: "RFIs" },
  { id: "submittals", canonicalPath: "/projects/:projectId/submittals", path: "/demo/app/projects/demo-project-warehouse/submittals", label: "Submittals" },
  { id: "site-logs", canonicalPath: "/projects/:projectId/site-logs", path: "/demo/app/projects/demo-project-warehouse/site-logs", label: "Site Logs" },
  { id: "vendors", canonicalPath: "/vendors", path: "/demo/app/vendors", label: "Vendors" },
  { id: "settings", canonicalPath: "/settings", path: "/demo/app/settings", label: "Settings" },
] as const;

export const R4E_SYSTEM_THEME_ROUTES = R4E_VISUAL_ROUTES.filter((candidate) => ["dashboard", "invoices", "payroll"].includes(candidate.id));

export const R4E_DARK_ROUTE_AUDIT = [
  { id: "project-overview", canonicalPath: "/projects/:projectId", path: "/demo/app/projects/demo-project-warehouse", label: "Project overview" },
  { id: "project-financial-control", canonicalPath: "/projects/:projectId", path: "/demo/app/projects/demo-project-solar", label: "Project financial control" },
  { id: "project-documents", canonicalPath: "/projects/:projectId/documents", path: "/demo/app/projects/demo-project-warehouse/documents", label: "Project documents" },
  { id: "blueprint-viewer", canonicalPath: "/projects/:projectId/documents", path: "/demo/app/projects/demo-project-warehouse/documents", label: "Blueprint viewer" },
  { id: "engineering-documents", canonicalPath: "/documents", path: "/demo/app/documents", label: "Engineering documents" },
  { id: "rfi-detail", canonicalPath: "/projects/:projectId/rfis?rfiId=:rfiId", path: "/demo/app/projects/demo-project-warehouse/rfis?rfiId=demo-rfi-missing-s3e", label: "RFI detail recovery" },
  { id: "submittal-detail", canonicalPath: "/projects/:projectId/submittals?submittalId=:submittalId&roundId=:roundId", path: "/demo/app/projects/demo-project-warehouse/submittals?submittalId=demo-sub-missing-s3e&roundId=demo-round-missing-s3e", label: "Submittal detail recovery" },
  { id: "site-log-detail", canonicalPath: "/projects/:projectId/site-logs?siteLogId=:siteLogId", path: "/demo/app/projects/demo-project-warehouse/site-logs?siteLogId=demo-site-log-wh-concrete", label: "Site Log detail" },
  { id: "cash-settlement", canonicalPath: "/cash?transactionId=:transactionId", path: "/demo/app/cash?transactionId=demo-transaction-19", label: "Cash settlement" },
  { id: "extract", canonicalPath: "/extract", path: "/demo/app/extract", label: "Invoice extraction" },
  { id: "invoice-detail", canonicalPath: "/invoices/:invoiceId", path: "/demo/app/invoices/demo-invoice-01", label: "Supplier invoice detail" },
  { id: "payroll-run", canonicalPath: "/payroll?runId=:runId", path: "/demo/app/payroll?runId=demo-payroll-run-9", label: "Payroll run" },
  { id: "project-billing", canonicalPath: "/projects/:projectId/billing?billingId=:billingId", path: "/demo/app/projects/demo-project-warehouse/billing?billingId=demo-client-billing-warehouse-02", label: "Client billing" },
  { id: "assistant", canonicalPath: "/assistant", path: "/demo/app/assistant", label: "Assistant" },
  { id: "help", canonicalPath: "/help?topic=invoice-review", path: "/help?topic=invoice-review", label: "Help Center article" },
] as const;

export const DEMO_QA_SCENARIO_METADATA: readonly DemoQaScenarioMetadata[] = [
  defineQaScenarioMetadata({ feature: "demo", route: route("landing", "/demo"), path: "/demo", interactionState: "base route loaded", viewport: QA_VIEWPORTS.desktop }),
  defineQaScenarioMetadata({ feature: "dashboard", route: route("dashboard", "/dashboard"), path: "/demo/app/dashboard", interactionState: "base route loaded", viewport: QA_VIEWPORTS.desktop }),
  defineQaScenarioMetadata({ feature: "dashboard", route: route("dashboard", "/dashboard"), path: "/demo/app/dashboard", interactionState: "base route loaded", viewport: QA_VIEWPORTS.laptop }),
  defineQaScenarioMetadata({ feature: "dashboard", route: route("dashboard", "/dashboard"), path: "/demo/app/dashboard", interactionState: "mobile navigation opened", viewport: QA_VIEWPORTS.mobile, actionId: "openMobileNavigation" }),
  defineQaScenarioMetadata({ feature: "projects", route: route("projects", "/projects"), path: "/demo/app/projects", interactionState: "portfolio dashboard verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyPortfolioDashboard" }),
  defineQaScenarioMetadata({ feature: "projects", route: route("projects", "/projects"), path: "/demo/app/projects", interactionState: "attention filters verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyPortfolioAttention" }),
  defineQaScenarioMetadata({ feature: "projects", route: route("projects", "/projects"), path: "/demo/app/projects", interactionState: "portfolio dashboard verified", viewport: QA_VIEWPORTS.laptop, actionId: "verifyPortfolioDashboard" }),
  defineQaScenarioMetadata({ feature: "projects", route: route("projects", "/projects"), path: "/demo/app/projects", interactionState: "portfolio dashboard verified", viewport: QA_VIEWPORTS.tablet, actionId: "verifyPortfolioDashboard" }),
  defineQaScenarioMetadata({ feature: "projects", route: route("projects", "/projects"), path: "/demo/app/projects", interactionState: "portfolio dashboard verified", viewport: QA_VIEWPORTS.mobile, actionId: "verifyPortfolioDashboard" }),
  defineQaScenarioMetadata({ feature: "projects", route: route("projects", "/projects"), path: "/demo/app/projects", interactionState: "UI-PROJECTS-ACTION-1 Light popover reachability", viewport: R4E_VIEWPORTS[1], actionId: "projectCardActionTheme:light" }),
  defineQaScenarioMetadata({ feature: "projects", route: route("projects", "/projects"), path: "/demo/app/projects", interactionState: "UI-PROJECTS-ACTION-1 Dark popover reachability", viewport: R4E_VIEWPORTS[1], actionId: "projectCardActionTheme:dark" }),
  defineQaScenarioMetadata({ feature: "projects", route: route("projects", "/projects"), path: "/demo/app/projects", interactionState: "UI-PROJECTS-ACTION-1 Light phone popover reachability", viewport: R4E_VIEWPORTS[3], actionId: "projectCardActionTheme:light" }),
  defineQaScenarioMetadata({ feature: "projects", route: route("projects", "/projects"), path: "/demo/app/projects", interactionState: "UI-PROJECTS-ACTION-1 Dark phone popover reachability", viewport: R4E_VIEWPORTS[3], actionId: "projectCardActionTheme:dark" }),
  defineQaScenarioMetadata({ feature: "procurement", route: route("procurement", "/procurement"), path: "/demo/app/procurement", interactionState: "base route loaded", viewport: QA_VIEWPORTS.desktop }),
  defineQaScenarioMetadata({ feature: "procurement", route: route("procurement", "/procurement"), path: "/demo/app/procurement", interactionState: "RFQ and Purchase Order draft worksheets verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyProcurementDraftWorksheets" }),
  defineQaScenarioMetadata({ feature: "procurement", route: route("procurement", "/procurement"), path: "/demo/app/procurement", interactionState: "RFQ and Purchase Order draft worksheets verified", viewport: QA_VIEWPORTS.tablet, actionId: "verifyProcurementDraftWorksheets" }),
  defineQaScenarioMetadata({ feature: "procurement", route: route("procurement", "/procurement"), path: "/demo/app/procurement", interactionState: "RFQ and Purchase Order draft worksheets verified", viewport: QA_VIEWPORTS.mobile, actionId: "verifyProcurementDraftWorksheets" }),
  defineQaScenarioMetadata({ feature: "procurement", route: route("procurement", "/procurement"), path: "/demo/app/procurement", interactionState: "subcontract claim and variation parity verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyProcurementSubcontractParity" }),
  defineQaScenarioMetadata({ feature: "procurement", route: route("procurement", "/procurement"), path: "/demo/app/procurement", interactionState: "subcontract claim settlement workflow verified", viewport: QA_VIEWPORTS.mobile, actionId: "verifySubcontractMobileSettlementWorkflow" }),
  defineQaScenarioMetadata({ feature: "document-delivery", route: route("procurement", "/procurement"), path: "/demo/app/procurement", interactionState: "Purchase Order delivery preview and disconnected history verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyPurchaseOrderDocumentDeliverySurface" }),
  defineQaScenarioMetadata({ feature: "document-delivery", route: route("procurement", "/procurement"), path: "/demo/app/procurement", interactionState: "Purchase Order delivery preview and disconnected history verified", viewport: QA_VIEWPORTS.mobile, actionId: "verifyPurchaseOrderDocumentDeliverySurface" }),
  defineQaScenarioMetadata({ feature: "warehouse-inventory", route: route("warehouse", "/warehouse"), path: "/demo/app/warehouse", interactionState: "warehouse ledger rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifyWarehouseInventoryScreen" }),
  defineQaScenarioMetadata({ feature: "warehouse-inventory", route: route("warehouse", "/warehouse"), path: "/demo/app/warehouse", interactionState: "warehouse source continuation verified", viewport: QA_VIEWPORTS.mobile, actionId: "verifyWarehouseInventoryScreen" }),
  defineQaScenarioMetadata({ feature: "warehouse-item-master", route: route("warehouse", "/warehouse"), path: "/demo/app/warehouse", interactionState: "Warehouse item create worksheet and validation verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyWarehouseItemWorksheetCreate" }),
  defineQaScenarioMetadata({ feature: "warehouse-item-master", route: route("warehouse", "/warehouse"), path: "/demo/app/warehouse", interactionState: "Warehouse item edit worksheet verified", viewport: QA_VIEWPORTS.laptop, actionId: "verifyWarehouseItemWorksheetEdit" }),
  defineQaScenarioMetadata({ feature: "warehouse-item-master", route: route("warehouse", "/warehouse"), path: "/demo/app/warehouse", interactionState: "Warehouse item phone worksheet verified", viewport: QA_VIEWPORTS.mobile, actionId: "verifyWarehouseItemWorksheetEdit" }),
  defineQaScenarioMetadata({ feature: "equipment-registry", route: route("equipment", "/equipment"), path: "/demo/app/equipment", interactionState: "Equipment Registry rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifyEquipmentRegistryScreen" }),
  defineQaScenarioMetadata({ feature: "equipment-master", route: route("equipment", "/equipment"), path: "/demo/app/equipment", interactionState: "Equipment create worksheet verified", viewport: QA_VIEWPORTS.tablet, actionId: "verifyCanonicalEquipmentWorksheetCreate" }),
  defineQaScenarioMetadata({ feature: "equipment-master", route: route("equipment", "/equipment"), path: "/demo/app/equipment", interactionState: "Equipment edit worksheet verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyCanonicalEquipmentWorksheetEdit" }),
  defineQaScenarioMetadata({ feature: "equipment-master", route: route("equipment", "/equipment"), path: "/demo/app/equipment", interactionState: "Equipment phone worksheet verified", viewport: QA_VIEWPORTS.mobile, actionId: "verifyCanonicalEquipmentWorksheetEdit" }),
  defineQaScenarioMetadata({ feature: "project-workspace", route: route("project-overview", "/projects/:projectId"), path: "/demo/app/projects", interactionState: "project selected", viewport: QA_VIEWPORTS.desktop, actionId: "openProjectFromDirectory" }),
  defineQaScenarioMetadata({ feature: "project-workspace", route: route("project-overview", "/projects/:projectId"), path: PROJECT_ROOT, interactionState: "attention and engineering drilldowns verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyProjectAttentionAndEngineering" }),
  defineQaScenarioMetadata({ feature: "project-materials-equipment", route: route("project-materials-equipment", "/projects/:projectId/materials-equipment"), path: `${PROJECT_ROOT}/materials-equipment`, interactionState: "materials and equipment browse rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifyMaterialsEquipmentBrowse" }),
  defineQaScenarioMetadata({ feature: "project-materials-equipment", route: route("project-materials-equipment", "/projects/:projectId/materials-equipment"), path: `${PROJECT_ROOT}/materials-equipment`, interactionState: "materials and equipment browse rendered", viewport: QA_VIEWPORTS.laptop, actionId: "verifyMaterialsEquipmentBrowse" }),
  defineQaScenarioMetadata({ feature: "project-materials-equipment", route: route("project-materials-equipment", "/projects/:projectId/materials-equipment"), path: `${PROJECT_ROOT}/materials-equipment`, interactionState: "materials and equipment browse rendered", viewport: QA_VIEWPORTS.tablet, actionId: "verifyMaterialsEquipmentBrowse" }),
  defineQaScenarioMetadata({ feature: "project-materials-equipment", route: route("project-materials-equipment", "/projects/:projectId/materials-equipment"), path: `${PROJECT_ROOT}/materials-equipment`, interactionState: "materials and equipment browse rendered", viewport: QA_VIEWPORTS.mobile, actionId: "verifyMaterialsEquipmentBrowse" }),
  defineQaScenarioMetadata({ feature: "project-materials-equipment", route: route("project-materials-equipment", "/projects/:projectId/materials-equipment"), path: `${PROJECT_ROOT}/materials-equipment`, interactionState: "material worksheet create rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifyMaterialWorksheetCreate" }),
  defineQaScenarioMetadata({ feature: "project-materials-equipment", route: route("project-materials-equipment", "/projects/:projectId/materials-equipment"), path: `${PROJECT_ROOT}/materials-equipment`, interactionState: "material worksheet validation rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifyMaterialWorksheetValidation" }),
  defineQaScenarioMetadata({ feature: "project-materials-equipment", route: route("project-materials-equipment", "/projects/:projectId/materials-equipment"), path: `${PROJECT_ROOT}/materials-equipment`, interactionState: "material worksheet edit rendered", viewport: QA_VIEWPORTS.laptop, actionId: "verifyMaterialWorksheetEdit" }),
  defineQaScenarioMetadata({ feature: "project-materials-equipment", route: route("project-materials-equipment", "/projects/:projectId/materials-equipment"), path: `${PROJECT_ROOT}/materials-equipment`, interactionState: "equipment worksheet create rendered", viewport: QA_VIEWPORTS.tablet, actionId: "verifyEquipmentWorksheetCreate" }),
  defineQaScenarioMetadata({ feature: "project-materials-equipment", route: route("project-materials-equipment", "/projects/:projectId/materials-equipment"), path: `${PROJECT_ROOT}/materials-equipment`, interactionState: "equipment worksheet edit rendered", viewport: QA_VIEWPORTS.mobile, actionId: "verifyEquipmentWorksheetEdit" }),
  defineQaScenarioMetadata({ feature: "project-financial-control", route: route("project-financial-control", "/projects/:projectId"), path: PROJECT_ROOT, interactionState: "financial control dashboard verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyProjectFinancialControlDashboard" }),
  defineQaScenarioMetadata({ feature: "project-financial-control", route: route("project-financial-control", "/projects/:projectId"), path: PROJECT_ROOT, interactionState: "financial control dashboard verified", viewport: QA_VIEWPORTS.laptop, actionId: "verifyProjectFinancialControlDashboard" }),
  defineQaScenarioMetadata({ feature: "project-financial-control", route: route("project-financial-control", "/projects/:projectId"), path: PROJECT_ROOT, interactionState: "financial control dashboard verified", viewport: QA_VIEWPORTS.tablet, actionId: "verifyProjectFinancialControlDashboard" }),
  defineQaScenarioMetadata({ feature: "project-financial-control", route: route("project-financial-control", "/projects/:projectId"), path: PROJECT_ROOT, interactionState: "financial control dashboard verified", viewport: QA_VIEWPORTS.mobile, actionId: "verifyProjectFinancialControlDashboard" }),
  defineQaScenarioMetadata({ feature: "project-financial-control", route: route("project-financial-control", "/projects/:projectId"), path: "/demo/app/projects/demo-project-solar", interactionState: "mixed-currency control state verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyPhpOnlyProjectControlState" }),
  defineQaScenarioMetadata({ feature: "project-workspace", route: route("project-overview", "/projects/:projectId"), path: PROJECT_ROOT, interactionState: "base route loaded", viewport: QA_VIEWPORTS.tablet }),
  defineQaScenarioMetadata({ feature: "project-workspace", route: route("project-documents", "/projects/:projectId/documents"), path: `${PROJECT_ROOT}/documents`, interactionState: "base route loaded", viewport: QA_VIEWPORTS.desktop }),
  defineQaScenarioMetadata({ feature: "project-workspace", route: route("project-documents", "/projects/:projectId/documents"), path: `${PROJECT_ROOT}/documents`, interactionState: "base route loaded", viewport: QA_VIEWPORTS.mobile }),
  defineQaScenarioMetadata({ feature: "engineering-documents", route: route("blueprint-viewer", "/projects/:projectId/documents"), path: `${PROJECT_ROOT}/documents`, interactionState: "demo drawing preview opened", viewport: QA_VIEWPORTS.desktop, actionId: "openDemoDrawingPreview" }),
  defineQaScenarioMetadata({ feature: "documents", route: route("documents", "/documents"), path: "/demo/app/documents", interactionState: "unified document Library rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifyDocumentsWorkspace" }),
  defineQaScenarioMetadata({ feature: "documents", route: route("documents", "/documents"), path: "/demo/app/documents", interactionState: "unified document Library rendered", viewport: QA_VIEWPORTS.tablet, actionId: "verifyDocumentsWorkspace" }),
  defineQaScenarioMetadata({ feature: "documents", route: route("documents", "/documents"), path: "/demo/app/documents", interactionState: "unified document Library rendered", viewport: QA_VIEWPORTS.mobile, actionId: "verifyDocumentsWorkspace" }),
  defineQaScenarioMetadata({ feature: "documents", route: route("documents", "/documents?managedId=:managedId"), path: "/demo/app/documents?managedId=demo-managed-warranty-001", interactionState: "managed document detail and immutable version history rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifyManagedDocumentDetail" }),
  defineQaScenarioMetadata({ feature: "documents", route: route("documents", "/documents?managedId=:managedId"), path: "/demo/app/documents?managedId=demo-managed-warranty-001", interactionState: "managed document detail and immutable version history rendered", viewport: QA_VIEWPORTS.mobile, actionId: "verifyManagedDocumentDetail" }),
  defineQaScenarioMetadata({ feature: "documents", route: route("documents", "/documents?managedId=:managedId"), path: "/demo/app/documents?managedId=demo-managed-artifact-001", interactionState: "managed generated artifact provenance and read-only state rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifyManagedArtifactDetail" }),
  defineQaScenarioMetadata({ feature: "documents", route: route("documents", "/documents"), path: "/demo/app/documents", interactionState: "Document Center Create rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifyDocumentsCreateWorkspace" }),
  defineQaScenarioMetadata({ feature: "documents", route: route("documents", "/documents"), path: "/demo/app/documents", interactionState: "Document Center Create rendered", viewport: QA_VIEWPORTS.mobile, actionId: "verifyDocumentsCreateWorkspace" }),
  defineQaScenarioMetadata({ feature: "documents", route: route("documents", "/documents"), path: "/demo/app/documents", interactionState: "Document Center Templates rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifyDocumentsTemplatesWorkspace" }),
  defineQaScenarioMetadata({ feature: "documents", route: route("documents", "/documents"), path: "/demo/app/documents", interactionState: "Document Center Templates rendered", viewport: QA_VIEWPORTS.mobile, actionId: "verifyDocumentsTemplatesWorkspace" }),
  defineQaScenarioMetadata({ feature: "documents", route: route("documents", "/documents"), path: "/demo/app/documents", interactionState: "exact document handoff to Email / SMS compose", viewport: QA_VIEWPORTS.desktop, actionId: "verifyDocumentsToEmailHandoff" }),
  defineQaScenarioMetadata({ feature: "engineering-documents", route: route("engineering-documents", "/documents"), path: "/demo/app/documents", interactionState: "base route loaded", viewport: QA_VIEWPORTS.desktop }),
  defineQaScenarioMetadata({ feature: "rfis", route: route("rfis", "/projects/:projectId/rfis"), path: `${PROJECT_ROOT}/rfis`, interactionState: "base route loaded", viewport: QA_VIEWPORTS.desktop }),
  defineQaScenarioMetadata({ feature: "rfis", route: route("rfi-detail", "/projects/:projectId/rfis?rfiId=:rfiId"), path: `${PROJECT_ROOT}/rfis?rfiId=demo-rfi-missing-s3e`, interactionState: "missing-record recovery rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifyRfiMissingRecordRecovery" }),
  defineQaScenarioMetadata({ feature: "submittals", route: route("submittals", "/projects/:projectId/submittals"), path: `${PROJECT_ROOT}/submittals`, interactionState: "base route loaded", viewport: QA_VIEWPORTS.desktop }),
  defineQaScenarioMetadata({ feature: "submittals", route: route("submittal-detail", "/projects/:projectId/submittals?submittalId=:submittalId&roundId=:roundId"), path: `${PROJECT_ROOT}/submittals?submittalId=demo-sub-missing-s3e&roundId=demo-round-missing-s3e`, interactionState: "missing-record recovery rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifySubmittalMissingRecordRecovery" }),
  defineQaScenarioMetadata({ feature: "site-logs", route: route("site-logs", "/projects/:projectId/site-logs"), path: `${PROJECT_ROOT}/site-logs`, interactionState: "base route loaded", viewport: QA_VIEWPORTS.desktop }),
  defineQaScenarioMetadata({ feature: "site-logs", route: route("site-log-detail", "/projects/:projectId/site-logs?siteLogId=:siteLogId"), path: `${PROJECT_ROOT}/site-logs?siteLogId=demo-site-log-wh-concrete`, interactionState: "Site Log detail opened", viewport: QA_VIEWPORTS.desktop }),
  defineQaScenarioMetadata({ feature: "site-logs", route: route("site-logs", "/projects/:projectId/site-logs"), path: `${PROJECT_ROOT}/site-logs`, interactionState: "base route loaded", viewport: QA_VIEWPORTS.tablet }),
  defineQaScenarioMetadata({ feature: "site-logs", route: route("site-logs", "/projects/:projectId/site-logs"), path: `${PROJECT_ROOT}/site-logs`, interactionState: "base route loaded", viewport: QA_VIEWPORTS.mobile }),
  defineQaScenarioMetadata({ feature: "cash-banking", route: route("cash", "/cash"), path: "/demo/app/cash", interactionState: "base route loaded", viewport: QA_VIEWPORTS.desktop }),
  defineQaScenarioMetadata({ feature: "cash-banking", route: route("cash", "/cash"), path: "/demo/app/cash", interactionState: "cash browse with intentional allocation choice", viewport: QA_VIEWPORTS.desktop, actionId: "verifyCashBrowseAndChoice" }),
  defineQaScenarioMetadata({ feature: "cash-banking", route: route("cash-settlement", "/cash?transactionId=:transactionId"), path: "/demo/app/cash?transactionId=demo-transaction-split-01", interactionState: "cash settlement workspace opened", viewport: QA_VIEWPORTS.desktop }),
  defineQaScenarioMetadata({ feature: "cash-banking", route: route("cash", "/cash"), path: "/demo/app/cash", interactionState: "base route loaded", viewport: QA_VIEWPORTS.tablet }),
  defineQaScenarioMetadata({ feature: "cash-banking", route: route("cash-settlement", "/cash?transactionId=:transactionId"), path: "/demo/app/cash?transactionId=demo-transaction-19", interactionState: "cash settlement result and return context verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyCashSettlementResult" }),
  defineQaScenarioMetadata({ feature: "cash-banking", route: route("cash-settlement", "/cash?transactionId=:transactionId"), path: "/demo/app/cash?transactionId=demo-transaction-19", interactionState: "cash settlement result and return context verified", viewport: QA_VIEWPORTS.mobile, actionId: "verifyCashSettlementResult" }),
  defineQaScenarioMetadata({ feature: "cash-banking", route: route("cash", "/cash"), path: "/demo/app/cash", interactionState: "cash internal transfer workflow kept separate", viewport: QA_VIEWPORTS.desktop, actionId: "verifyCashTransferWorkflowSeparation" }),
  defineQaScenarioMetadata({ feature: "invoice-extraction", route: route("extract", "/extract"), path: "/demo/app/extract", interactionState: "extractor screen rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifyExtractorScreen" }),
  defineQaScenarioMetadata({ feature: "email-sms", route: route("inbox", "/email-sms"), path: "/demo/app/email-sms", interactionState: "Email / SMS workspace rendered with provider-gated compose and history", viewport: QA_VIEWPORTS.desktop, actionId: "verifyEmailSmsWorkspace" }),
  defineQaScenarioMetadata({ feature: "email-sms", route: route("inbox", "/email-sms"), path: "/demo/app/email-sms", interactionState: "Email / SMS workspace rendered with provider-gated compose and history", viewport: QA_VIEWPORTS.tablet, actionId: "verifyEmailSmsWorkspace" }),
  defineQaScenarioMetadata({ feature: "email-sms", route: route("inbox", "/email-sms"), path: "/demo/app/email-sms", interactionState: "Email / SMS workspace rendered with provider-gated compose and history", viewport: QA_VIEWPORTS.mobile, actionId: "verifyEmailSmsWorkspace" }),
  defineQaScenarioMetadata({ feature: "email-sms", route: route("inbox", "/email-sms"), path: "/demo/app/email-sms?view=compose", interactionState: "Email compose review surface rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifyEmailComposeWorkspace" }),
  defineQaScenarioMetadata({ feature: "email-sms", route: route("inbox", "/email-sms"), path: "/demo/app/email-sms?view=compose", interactionState: "Email compose review surface rendered", viewport: QA_VIEWPORTS.mobile, actionId: "verifyEmailComposeWorkspace" }),
  defineQaScenarioMetadata({ feature: "email-sms", route: route("inbox", "/email-sms"), path: "/demo/app/email-sms?view=compose&channel=sms", interactionState: "SMS compose review surface rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifySmsComposeWorkspace" }),
  defineQaScenarioMetadata({ feature: "email-sms", route: route("inbox", "/email-sms"), path: "/demo/app/email-sms?view=compose&channel=sms", interactionState: "SMS compose review surface rendered", viewport: QA_VIEWPORTS.mobile, actionId: "verifySmsComposeWorkspace" }),
  defineQaScenarioMetadata({ feature: "email-sms", route: route("inbox", "/email-sms"), path: "/demo/app/email-sms?view=sent", interactionState: "sent delivery history surface rendered", viewport: QA_VIEWPORTS.desktop }),
  defineQaScenarioMetadata({ feature: "email-sms", route: route("inbox", "/email-sms"), path: "/demo/app/email-sms?view=sms", interactionState: "SMS not-configured surface rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifySmsNotConfigured" }),
  defineQaScenarioMetadata({ feature: "email-sms", route: route("inbox", "/email-sms"), path: "/demo/app/email-sms?view=sms", interactionState: "SMS not-configured surface rendered", viewport: QA_VIEWPORTS.mobile, actionId: "verifySmsNotConfigured" }),
  defineQaScenarioMetadata({ feature: "invoices", route: route("invoices", "/invoices"), path: "/demo/app/invoices", interactionState: "supplier invoice navigation and register verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifySupplierInvoiceNavigation" }),
  defineQaScenarioMetadata({ feature: "invoices", route: route("invoice-detail", "/invoices/:invoiceId"), path: "/demo/app/invoices/demo-invoice-01", interactionState: "invoice detail opened", viewport: QA_VIEWPORTS.desktop }),
  defineQaScenarioMetadata({ feature: "supplier-payables", route: route("invoice-detail", "/invoices/:invoiceId"), path: "/demo/app/invoices/demo-invoice-02", interactionState: "inline supplier payment modal opened", viewport: QA_VIEWPORTS.desktop, actionId: "verifySupplierPayableBridge" }),
  defineQaScenarioMetadata({ feature: "supplier-payables", route: route("invoice-detail", "/invoices/:invoiceId"), path: "/demo/app/invoices/demo-invoice-02", interactionState: "inline supplier payment modal opened", viewport: QA_VIEWPORTS.mobile, actionId: "verifySupplierPayableBridge" }),
  ...UX_EDIT_1A_VIEWPORTS.map((viewport) => defineQaScenarioMetadata({ feature: "supplier-invoice-ux-edit-1a", route: route("review", "/review?invoiceId=:invoiceId"), path: "/demo/app/review?invoiceId=demo-invoice-07", interactionState: "Supplier Invoice source and extracted worksheet review", viewport, actionId: "verifySupplierInvoiceReview" })),
  ...([UX_EDIT_1A_VIEWPORTS[1], UX_EDIT_1A_VIEWPORTS[3]] as const).map((viewport) => defineQaScenarioMetadata({ feature: "supplier-invoice-ux-edit-1a-readonly", route: route("review", "/review?invoiceId=:invoiceId"), path: "/demo/app/review?invoiceId=demo-invoice-01", interactionState: "Verified Supplier Invoice cells remain read-only after one pointer click", viewport, actionId: "verifySupplierInvoiceReadOnlyCell" })),
  defineQaScenarioMetadata({ feature: "vendors", route: route("vendors", "/vendors"), path: "/demo/app/vendors", interactionState: "vendor directory rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifyVendorsScreen" }),
  defineQaScenarioMetadata({ feature: "vendors", route: route("vendors", "/vendors"), path: "/demo/app/vendors", interactionState: "vendor master worksheet maintenance rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifyVendorMasterWorksheet" }),
  defineQaScenarioMetadata({ feature: "vendors", route: route("vendors", "/vendors"), path: "/demo/app/vendors", interactionState: "vendor master worksheet maintenance rendered", viewport: QA_VIEWPORTS.mobile, actionId: "verifyVendorMasterWorksheet" }),
  defineQaScenarioMetadata({ feature: "payroll", route: route("payroll", "/payroll"), path: "/demo/app/payroll", interactionState: "base route loaded", viewport: QA_VIEWPORTS.desktop }),
  defineQaScenarioMetadata({ feature: "payroll", route: route("payroll", "/payroll"), path: "/demo/app/payroll", interactionState: "Payroll normal-cycle next step verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyPayrollNormalCycleOverview" }),
  defineQaScenarioMetadata({ feature: "payroll", route: route("payroll", "/payroll"), path: "/demo/app/payroll", interactionState: "Payroll normal-cycle next step verified", viewport: QA_VIEWPORTS.mobile, actionId: "verifyPayrollNormalCycleOverview" }),
  defineQaScenarioMetadata({ feature: "payroll", route: route("payroll-run", "/payroll?runId=:runId"), path: "/demo/app/payroll?runId=demo-payroll-run-9", interactionState: "payroll run opened", viewport: QA_VIEWPORTS.desktop }),
  defineQaScenarioMetadata({ feature: "payroll", route: route("payroll-run", "/payroll?runId=:runId"), path: "/demo/app/payroll?runId=demo-payroll-run-9", interactionState: "approved Payroll Cash & Banking settlement handoff verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyPayrollApprovedSettlementHandoff" }),
  defineQaScenarioMetadata({ feature: "payroll", route: route("payroll-run", "/payroll?runId=:runId"), path: "/demo/app/payroll?runId=demo-payroll-run-9", interactionState: "approved Payroll Cash & Banking settlement handoff verified", viewport: QA_VIEWPORTS.mobile, actionId: "verifyPayrollApprovedSettlementHandoff" }),
  defineQaScenarioMetadata({ feature: "expenses", route: route("expenses", "/expenses"), path: "/demo/app/expenses", interactionState: "base route loaded", viewport: QA_VIEWPORTS.desktop }),
  defineQaScenarioMetadata({ feature: "supplier-payables", route: route("expenses", "/expenses?expenseId=:expenseId"), path: "/demo/app/expenses?expenseId=demo-expense-supplier-bm-02", interactionState: "authoritative Expense payment surface opened", viewport: QA_VIEWPORTS.desktop, actionId: "verifyExpensePaymentSurface" }),
  defineQaScenarioMetadata({ feature: "supplier-payables", route: route("expenses", "/expenses?expenseId=:expenseId"), path: "/demo/app/expenses?expenseId=demo-expense-supplier-bm-02", interactionState: "authoritative Expense payment surface opened", viewport: QA_VIEWPORTS.mobile, actionId: "verifyExpensePaymentSurface" }),
  defineQaScenarioMetadata({ feature: "supplier-payables", route: route("invoice-detail", "/invoices/:invoiceId"), path: "/demo/app/invoices/demo-missing-invoice", interactionState: "stale supplier invoice recovery verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyStaleSupplierInvoiceRecovery" }),
  defineQaScenarioMetadata({ feature: "supplier-payables", route: route("cash", "/cash?fromTargetType=:fromTargetType&fromTargetId=:fromTargetId&returnTo=:returnTo"), path: "/demo/app/cash?fromTargetType=EXPENSE&fromTargetId=demo-expense-supplier-bm-02&returnTo=%2Fexpenses%3FexpenseId%3Ddemo-expense-supplier-bm-02", interactionState: "Cash Expense target and return context opened", viewport: QA_VIEWPORTS.desktop, actionId: "verifyCashExpenseTarget" }),
  defineQaScenarioMetadata({ feature: "supplier-payables", route: route("cash", "/cash?fromTargetType=:fromTargetType&fromTargetId=:fromTargetId&returnTo=:returnTo"), path: "/demo/app/cash?fromTargetType=EXPENSE&fromTargetId=demo-expense-supplier-bm-02&returnTo=%2Fexpenses%3FexpenseId%3Ddemo-expense-supplier-bm-02", interactionState: "Cash Expense target and return context opened", viewport: QA_VIEWPORTS.mobile, actionId: "verifyCashExpenseTarget" }),
  defineQaScenarioMetadata({ feature: "client-receivables", route: route("project-billing", "/projects/:projectId/billing?billingId=:billingId"), path: "/demo/app/projects/demo-project-warehouse/billing?billingId=demo-client-billing-warehouse-02", interactionState: "client invoice collection lifecycle verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyClientReceivableLifecycle" }),
  defineQaScenarioMetadata({ feature: "client-receivables", route: route("project-billing", "/projects/:projectId/billing?billingId=:billingId"), path: "/demo/app/projects/demo-project-warehouse/billing?billingId=demo-client-billing-warehouse-02", interactionState: "client invoice collection lifecycle verified", viewport: QA_VIEWPORTS.mobile, actionId: "verifyClientReceivableLifecycle" }),
  defineQaScenarioMetadata({ feature: "client-receivables", route: route("project-billing", "/projects/:projectId/billing?billingId=:billingId"), path: "/demo/app/projects/demo-project-drainage/billing?billingId=demo-client-billing-drainage-02", interactionState: "Client Billing draft worksheet editing verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyClientBillingDraftWorksheet" }),
  defineQaScenarioMetadata({ feature: "client-receivables", route: route("project-billing", "/projects/:projectId/billing?billingId=:billingId"), path: "/demo/app/projects/demo-project-drainage/billing?billingId=demo-client-billing-drainage-02", interactionState: "Client Billing draft worksheet editing verified", viewport: QA_VIEWPORTS.tablet, actionId: "verifyClientBillingDraftWorksheet" }),
  defineQaScenarioMetadata({ feature: "client-receivables", route: route("project-billing", "/projects/:projectId/billing?billingId=:billingId"), path: "/demo/app/projects/demo-project-drainage/billing?billingId=demo-client-billing-drainage-02", interactionState: "Client Billing draft worksheet editing verified", viewport: QA_VIEWPORTS.mobile, actionId: "verifyClientBillingDraftWorksheet" }),
  defineQaScenarioMetadata({ feature: "document-delivery", route: route("project-billing", "/projects/:projectId/billing?billingId=:billingId"), path: "/demo/app/projects/demo-project-warehouse/billing?billingId=demo-client-billing-warehouse-02", interactionState: "Client Invoice delivery preview and disconnected history verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyClientInvoiceDocumentDeliverySurface" }),
  defineQaScenarioMetadata({ feature: "document-delivery", route: route("project-billing", "/projects/:projectId/billing?billingId=:billingId"), path: "/demo/app/projects/demo-project-warehouse/billing?billingId=demo-client-billing-warehouse-02", interactionState: "Client Invoice delivery preview and disconnected history verified", viewport: QA_VIEWPORTS.mobile, actionId: "verifyClientInvoiceDocumentDeliverySurface" }),
  defineQaScenarioMetadata({ feature: "reports", route: route("reports", "/reports"), path: "/demo/app/reports", interactionState: "base route loaded", viewport: QA_VIEWPORTS.desktop }),
  defineQaScenarioMetadata({ feature: "settings", route: route("settings", "/settings"), path: "/demo/app/settings", interactionState: "settings product surface verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifySettingsScreen" }),
  defineQaScenarioMetadata({ feature: "assistant", route: route("assistant", "/assistant"), path: "/demo/app/assistant", interactionState: "base route loaded", viewport: QA_VIEWPORTS.desktop }),
  defineQaScenarioMetadata({ feature: "help", route: route("help", "/help"), path: "/help", interactionState: "Help Center index rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifyHelpIndex" }),
  defineQaScenarioMetadata({ feature: "help", route: route("help", "/help"), path: "/help", interactionState: "Help Center index rendered", viewport: QA_VIEWPORTS.laptop, actionId: "verifyHelpIndex" }),
  defineQaScenarioMetadata({ feature: "help", route: route("help", "/help"), path: "/help", interactionState: "Help Center index rendered", viewport: QA_VIEWPORTS.tablet, actionId: "verifyHelpIndex" }),
  defineQaScenarioMetadata({ feature: "help", route: route("help", "/help"), path: "/help", interactionState: "Help Center index rendered", viewport: QA_VIEWPORTS.mobile, actionId: "verifyHelpIndex" }),
  defineQaScenarioMetadata({ feature: "help", route: route("help", "/help?topic=invoice-review"), path: "/help?topic=invoice-review", interactionState: "Help Center invoice-review article rendered", viewport: QA_VIEWPORTS.desktop, actionId: "verifyHelpArticle" }),
  defineQaScenarioMetadata({ feature: "help", route: route("help", "/help?topic=invoice-review"), path: "/help?topic=invoice-review", interactionState: "Help Center invoice-review article rendered", viewport: QA_VIEWPORTS.laptop, actionId: "verifyHelpArticle" }),
  defineQaScenarioMetadata({ feature: "help", route: route("help", "/help?topic=invoice-review"), path: "/help?topic=invoice-review", interactionState: "Help Center invoice-review article rendered", viewport: QA_VIEWPORTS.tablet, actionId: "verifyHelpArticle" }),
  defineQaScenarioMetadata({ feature: "help", route: route("help", "/help?topic=invoice-review"), path: "/help?topic=invoice-review", interactionState: "Help Center invoice-review article rendered", viewport: QA_VIEWPORTS.mobile, actionId: "verifyHelpArticle" }),
  defineQaScenarioMetadata({ feature: "help", route: route("help", "/help"), path: "/help", interactionState: "Help navigation interactions verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyHelpNavigation" }),
  defineQaScenarioMetadata({ feature: "help", route: route("help", "/help?topic=:topic"), path: "/help?topic=not-a-topic", interactionState: "unknown Help topic fallback verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyHelpUnknownTopicFallback" }),
  defineQaScenarioMetadata({ feature: "help-navigation", route: route("projects", "/projects"), path: "/projects", interactionState: "Projects PageHeader Help action verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyPageHeaderHelpAction" }),
  defineQaScenarioMetadata({ feature: "help-navigation", route: route("cash", "/cash"), path: "/cash", interactionState: "Cash & Banking PageHeader Help action verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyPageHeaderHelpAction" }),
  defineQaScenarioMetadata({ feature: "contextual-help", route: route("inbox", "/email-sms"), path: "/demo/app/email-sms?view=compose", interactionState: "Email attachment contextual help verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyAttachmentContextualHelp" }),
  defineQaScenarioMetadata({ feature: "contextual-help", route: route("inbox", "/email-sms"), path: "/demo/app/email-sms?view=compose", interactionState: "Email attachment contextual help verified", viewport: QA_VIEWPORTS.mobile, actionId: "verifyAttachmentContextualHelp" }),
  defineQaScenarioMetadata({ feature: "demo", route: route("demo-tour", "/demo/app/dashboard"), path: "/demo/app/dashboard", interactionState: "demo tour opened", viewport: QA_VIEWPORTS.desktop, actionId: "openDemoTour" }),
  ...R4C_VIEWPORTS.flatMap((viewport) => [
    defineQaScenarioMetadata({ feature: "dashboard", route: route("dashboard", "/dashboard"), path: "/demo/app/dashboard", interactionState: "R4C Home Light theme visual", viewport, actionId: "applyLightTheme" }),
    defineQaScenarioMetadata({ feature: "dashboard", route: route("dashboard", "/dashboard"), path: "/demo/app/dashboard", interactionState: "R4C Home Dark theme visual", viewport, actionId: "applyDarkTheme" }),
    defineQaScenarioMetadata({ feature: "projects", route: route("projects", "/projects"), path: "/demo/app/projects", interactionState: "R4C Project Portfolio Light theme visual", viewport, actionId: "applyLightTheme" }),
    defineQaScenarioMetadata({ feature: "projects", route: route("projects", "/projects"), path: "/demo/app/projects", interactionState: "R4C Project Portfolio Dark theme visual", viewport, actionId: "applyDarkTheme" }),
  ]),
  defineQaScenarioMetadata({ feature: "projects", route: route("projects", "/projects"), path: "/demo/app/projects", interactionState: "R4C Project Portfolio Dark filters and attention visual", viewport: R4C_VIEWPORTS[1], actionId: "verifyPortfolioAttentionDark" }),
  defineQaScenarioMetadata({ feature: "dashboard", route: route("dashboard", "/dashboard?view=insights"), path: "/demo/app/dashboard?view=insights", interactionState: "R4C Operations Insights Light theme visual", viewport: R4C_VIEWPORTS[0], actionId: "applyLightTheme" }),
  defineQaScenarioMetadata({ feature: "dashboard", route: route("dashboard", "/dashboard?view=insights"), path: "/demo/app/dashboard?view=insights", interactionState: "R4C Operations Insights Dark theme visual", viewport: R4C_VIEWPORTS[0], actionId: "applyDarkTheme" }),
  defineQaScenarioMetadata({ feature: "entity-media", route: route("projects", "/projects"), path: "/demo/app/projects", interactionState: "R4D Project media and deterministic fallback · Light", viewport: QA_VIEWPORTS.desktop, actionId: "verifyProjectMediaLight" }),
  defineQaScenarioMetadata({ feature: "entity-media", route: route("projects", "/projects"), path: "/demo/app/projects", interactionState: "R4D Project media and deterministic fallback · Constrained laptop", viewport: R4D_CONSTRAINED_LAPTOP, actionId: "verifyProjectMediaLight" }),
  defineQaScenarioMetadata({ feature: "entity-media", route: route("projects", "/projects"), path: "/demo/app/projects", interactionState: "R4D Project media and deterministic fallback · Dark phone", viewport: QA_VIEWPORTS.mobile, actionId: "verifyProjectMediaDark" }),
  defineQaScenarioMetadata({ feature: "entity-media", route: route("projects", "/projects"), path: "/demo/app/projects", interactionState: "R4D Project image Replace/Remove controls · Dark", viewport: QA_VIEWPORTS.desktop, actionId: "verifyProjectMediaControls" }),
  defineQaScenarioMetadata({ feature: "entity-media", route: route("projects", "/projects"), path: "/demo/app/projects", interactionState: "R4D Project image Replace/Remove controls · Dark phone", viewport: QA_VIEWPORTS.mobile, actionId: "verifyProjectMediaControls" }),
  defineQaScenarioMetadata({ feature: "entity-media", route: route("project-workspace", "/projects/:projectId"), path: "/demo/app/projects/demo-project-solar", interactionState: "R4D linked Project Material media and text context · Light", viewport: QA_VIEWPORTS.desktop, actionId: "verifyProjectMaterialImage" }),
  defineQaScenarioMetadata({ feature: "entity-media", route: route("equipment", "/equipment"), path: "/demo/app/equipment", interactionState: "R4D canonical Equipment media and fallback · Light", viewport: QA_VIEWPORTS.desktop, actionId: "verifyEquipmentMediaLight" }),
  defineQaScenarioMetadata({ feature: "entity-media", route: route("equipment", "/equipment"), path: "/demo/app/equipment", interactionState: "R4D canonical Equipment media and fallback · Constrained laptop", viewport: R4D_CONSTRAINED_LAPTOP, actionId: "verifyEquipmentMediaDark" }),
  defineQaScenarioMetadata({ feature: "entity-media", route: route("equipment", "/equipment"), path: "/demo/app/equipment", interactionState: "R4D canonical Equipment media and fallback · Dark phone", viewport: QA_VIEWPORTS.mobile, actionId: "verifyEquipmentMediaDark" }),
  defineQaScenarioMetadata({ feature: "entity-media", route: route("warehouse", "/warehouse"), path: "/demo/app/warehouse", interactionState: "R4D canonical Material media and fallback · Dark", viewport: QA_VIEWPORTS.desktop, actionId: "verifyMaterialMediaDark" }),
  defineQaScenarioMetadata({ feature: "entity-media", route: route("warehouse", "/warehouse"), path: "/demo/app/warehouse", interactionState: "R4D canonical Material media and fallback · Tablet", viewport: R4D_TABLET, actionId: "verifyMaterialMediaLight" }),
  defineQaScenarioMetadata({ feature: "entity-media", route: route("warehouse", "/warehouse"), path: "/demo/app/warehouse", interactionState: "R4D canonical Material media and fallback · Light phone", viewport: QA_VIEWPORTS.mobile, actionId: "verifyMaterialMediaLight" }),
  defineQaScenarioMetadata({ feature: "ui-r4e-theme", route: route("payroll", "/payroll"), path: "/demo/app/payroll", interactionState: "R4E Dark surface and legacy neutral contrast inspected", viewport: QA_VIEWPORTS.desktop, actionId: "verifyR4eLegacySurfaceContrast" }),
  defineQaScenarioMetadata({ feature: "ui-r4e-theme", route: route("procurement", "/procurement"), path: "/demo/app/procurement", interactionState: "R4E Dark procurement committed metric contrast inspected", viewport: QA_VIEWPORTS.desktop, actionId: "verifyR4eProcurementMetricContrast" }),
  defineQaScenarioMetadata({ feature: "ui-r4e-responsive-density", route: route("expenses", "/expenses"), path: "/demo/app/expenses", interactionState: "R4E Expenses register fits or exposes the complete responsive record path", viewport: R4E_VIEWPORTS[0], actionId: "verifyR4eExpenseRegisterFit" }),
  defineQaScenarioMetadata({ feature: "ui-r4e-theme", route: route("invoices", "/invoices"), path: "/demo/app/invoices", interactionState: "R4E Dark primary action contrast inspected", viewport: QA_VIEWPORTS.desktop, actionId: "verifyR4ePrimaryButtonContrast" }),
  defineQaScenarioMetadata({ feature: "ui-r4e-invoice-directory", route: route("invoices", "/invoices"), path: "/demo/app/invoices", interactionState: "R4E compact invoice filters and removable active chip verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyInvoiceRegisterCompactFilters" }),
  defineQaScenarioMetadata({ feature: "ui-r4e-invoice-directory", route: route("invoices", "/invoices"), path: "/demo/app/invoices", interactionState: "R4E readable invoice cards verified at phone width", viewport: QA_VIEWPORTS.mobile, actionId: "verifyInvoiceRegisterPhoneCards" }),
  defineQaScenarioMetadata({ feature: "ui-r4e-invoice-directory", route: route("invoices", "/invoices"), path: "/demo/app/invoices", interactionState: "R4E filter disclosure opened at phone width", viewport: QA_VIEWPORTS.mobile, actionId: "verifyInvoiceFilterSheetPhone" }),
  defineQaScenarioMetadata({ feature: "ui-r4e-theme-overlays", route: route("invoices", "/invoices"), path: "/demo/app/invoices", interactionState: "R4E Dark phone filter sheet contrast and focus inspected", viewport: R4E_VIEWPORTS[3], actionId: "verifyDarkInvoiceFilterSheet" }),
  defineQaScenarioMetadata({ feature: "ui-r4e-payroll-hierarchy", route: route("payroll", "/payroll"), path: "/demo/app/payroll", interactionState: "R4E Payroll next step prioritized at phone width", viewport: QA_VIEWPORTS.mobile, actionId: "verifyPayrollFirstView" }),
  defineQaScenarioMetadata({ feature: "ui-r4e-payroll-hierarchy", route: route("payroll", "/payroll"), path: "/demo/app/payroll", interactionState: "R4E secondary Payroll period details remain available by disclosure", viewport: R4E_VIEWPORTS[0], actionId: "verifyPayrollSummaryDisclosure" }),
  defineQaScenarioMetadata({ feature: "ui-r4e-email-compose", route: route("inbox", "/email-sms"), path: "/demo/app/email-sms?view=compose", interactionState: "R4E Email compose task-first phone view", viewport: QA_VIEWPORTS.mobile, actionId: "verifyEmailComposeFirstView" }),
  defineQaScenarioMetadata({ feature: "ui-r4e-demo-chrome", route: route("dashboard", "/dashboard"), path: "/demo/app/dashboard", interactionState: "R4E safe-demo chrome compact at phone width", viewport: QA_VIEWPORTS.mobile, actionId: "verifyDemoWorkspaceChrome" }),
  defineQaScenarioMetadata({ feature: "ui-r4e-demo-chrome", route: route("dashboard", "/dashboard"), path: "/demo/app/dashboard", interactionState: "R4E safe-demo chrome compact at desktop width", viewport: QA_VIEWPORTS.desktop, actionId: "verifyDemoWorkspaceChrome" }),
  defineQaScenarioMetadata({ feature: "ui-r4e-action-grammar", route: route("cash", "/cash"), path: "/demo/app/cash", interactionState: "R4E Cash header action variants verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyPageHeaderActionVariants:cash" }),
  defineQaScenarioMetadata({ feature: "ui-r4e-action-grammar", route: route("expenses", "/expenses"), path: "/demo/app/expenses", interactionState: "R4E Expenses header action variants verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyPageHeaderActionVariants:expenses" }),
  defineQaScenarioMetadata({ feature: "ui-r4e-action-grammar", route: route("equipment", "/equipment"), path: "/demo/app/equipment", interactionState: "R4E Equipment header action variant verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyPageHeaderActionVariants:equipment" }),
  defineQaScenarioMetadata({ feature: "ui-r4e-action-grammar", route: route("warehouse", "/warehouse"), path: "/demo/app/warehouse", interactionState: "R4E Warehouse header action variants verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyPageHeaderActionVariants:warehouse" }),
  defineQaScenarioMetadata({ feature: "ui-r4e-action-grammar", route: route("procurement", "/procurement"), path: "/demo/app/procurement", interactionState: "R4E Procurement header action variant verified", viewport: QA_VIEWPORTS.desktop, actionId: "verifyPageHeaderActionVariants:procurement" }),
  ...R4E_VISUAL_ROUTES.flatMap((visualRoute) => R4E_VIEWPORTS.flatMap((viewport) => (["light", "dark"] as const).map((theme) =>
    defineQaScenarioMetadata({
      feature: "ui-r4e-visual-matrix",
      route: route(visualRoute.id, visualRoute.canonicalPath),
      path: visualRoute.path,
      interactionState: `R4E ${theme} theme visual · ${visualRoute.label}`,
      viewport,
      actionId: `r4eThemeAction:${theme}`,
    })
  ))),
  ...R4E_SYSTEM_THEME_ROUTES.flatMap((visualRoute) => R4E_VIEWPORTS.flatMap((viewport) => (["system-light", "system-dark"] as const).map((systemTheme) =>
    defineQaScenarioMetadata({
      feature: "ui-r4e-visual-matrix",
      route: route(visualRoute.id, visualRoute.canonicalPath),
      path: visualRoute.path,
      interactionState: `R4E ${systemTheme === "system-light" ? "System/OS Light" : "System/OS Dark"} · ${visualRoute.label}`,
      viewport,
      actionId: `r4eThemeAction:${systemTheme}`,
    })
  ))),
  ...R4E_DARK_ROUTE_AUDIT.map((auditRoute) => defineQaScenarioMetadata({
    feature: "ui-r4e-route-audit",
    route: route(auditRoute.id, auditRoute.canonicalPath),
    path: auditRoute.path,
    interactionState: `R4E Dark route audit · ${auditRoute.label}`,
    viewport: R4E_VIEWPORTS[0],
    actionId: "verifyR4eDarkRouteAudit",
  })),
  defineQaScenarioMetadata({ feature: "ui-r4e-keyboard-touch", route: route("dashboard", "/dashboard"), path: "/demo/app/dashboard", interactionState: "R4E desktop keyboard focus and account menu verified", viewport: R4E_VIEWPORTS[0], actionId: "verifyR4eKeyboardAccountNavigation" }),
  defineQaScenarioMetadata({ feature: "ui-r4e-keyboard-touch", route: route("dashboard", "/dashboard"), path: "/demo/app/dashboard", interactionState: "R4E mobile navigation and account menu verified", viewport: R4E_VIEWPORTS[3], actionId: "verifyR4eMobileNavigationAndAccount" }),
  defineQaScenarioMetadata({ feature: "shared-shell-smoke", route: route("dashboard", "/dashboard"), path: "/demo/app/dashboard", interactionState: "app shell content visible", viewport: QA_VIEWPORTS.desktop, actionId: "verifyR4eResponsiveShell" }),
  defineQaScenarioMetadata({ feature: "shared-shell-smoke", route: route("dashboard", "/dashboard"), path: "/demo/app/dashboard", interactionState: "mobile navigation can open and restore focus", viewport: QA_VIEWPORTS.mobile, actionId: "openMobileNavigation" }),
];
