import React, { useMemo, useState } from "react";
import { BarChart3, Download, FileSpreadsheet } from "lucide-react";
import { Expense, InvoiceData, InvoiceProjectAllocation, PayrollEntry, PayrollPeriod, PayrollProjectAllocation, PayrollRun, Project, ProjectWorkerAssignment, Worker } from "../../types";
import { buildExpenseReport, buildPayrollReportWithContext, buildProjectCostReport, buildProjectInvoiceReport, buildProjectLaborAggregateReport, ProjectCostReportRow } from "../../utils/projectReports";
import { CostPayrollRecord } from "../../utils/projectCosting";
import type { ProjectLaborCostAggregate, ProjectLaborSource } from "../../utils/projectLaborCostAggregate.ts";

interface ProjectReportsProps { projects: Project[]; invoices: InvoiceData[]; invoiceAllocations: InvoiceProjectAllocation[]; expenses: Expense[]; workers: Worker[]; assignments: ProjectWorkerAssignment[]; periods: PayrollPeriod[]; runs: PayrollRun[]; entries: PayrollEntry[]; payrollAllocations: PayrollProjectAllocation[]; projectLaborAggregates?: readonly ProjectLaborCostAggregate[]; laborSource?: ProjectLaborSource; payrollDetailVisible?: boolean; onExport?: () => void; }
type ReportTab = "cost" | "invoices" | "payroll" | "expenses";

export const ProjectReports: React.FC<ProjectReportsProps> = ({ projects, invoices, invoiceAllocations, expenses, workers, periods, runs, entries, payrollAllocations, projectLaborAggregates = [], laborSource, payrollDetailVisible, onExport }) => {
  const [tab, setTab] = useState<ReportTab>("cost");
  const showPayrollDetail = payrollDetailVisible ?? (laborSource === undefined || laborSource === "detail");
  const payroll: CostPayrollRecord[] = runs.map((run) => ({ id: run.id, status: run.status, entries: entries.filter((entry) => entry.payrollRunId === run.id), allocations: payrollAllocations.filter((allocation) => entries.some((entry) => entry.id === allocation.payrollEntryId && entry.payrollRunId === run.id)) }));
  const costRows = useMemo(() => buildProjectCostReport(projects, invoices, invoiceAllocations, payroll, expenses, { projectLaborAggregates, laborSource }), [projects, invoices, invoiceAllocations, payroll, expenses, projectLaborAggregates, laborSource]);
  const invoiceRows = useMemo(() => buildProjectInvoiceReport(projects, invoices, invoiceAllocations), [projects, invoices, invoiceAllocations]);
  const payrollRows = useMemo(() => buildPayrollReportWithContext(projects, workers, periods, runs, entries, payrollAllocations), [projects, workers, periods, runs, entries, payrollAllocations]);
  const aggregateRows = useMemo(() => buildProjectLaborAggregateReport(projects, projectLaborAggregates), [projects, projectLaborAggregates]);
  const expenseRows = useMemo(() => buildExpenseReport(projects, expenses), [projects, expenses]);
  const tabs: Array<[ReportTab, string]> = [["cost", "Project cost summary"], ["invoices", "Invoice register"], ["payroll", "Payroll summary"], ["expenses", "Expense register"]];
  return <div className="space-y-5"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[0.2em] font-black text-indigo-600">Engineering reporting</p><h2 className="text-xl sm:text-2xl font-black">Project reports</h2><p className="text-xs text-slate-500 mt-1">Confirmed project costs and source registers, with allocations visible where permitted. Archive is visibility-only; void is excluded from active cost.</p></div>{onExport && <button onClick={onExport} className="inline-flex items-center gap-2 px-3 py-2 rounded-xl bg-indigo-600 text-white text-xs font-bold"><Download className="w-3.5 h-3.5" /> Export project workbook</button>}</div><nav className="flex gap-1 overflow-x-auto no-scrollbar bg-white border border-slate-200 p-1 rounded-xl shadow-sm">{tabs.map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={`px-3 py-2 rounded-lg text-xs font-bold whitespace-nowrap ${tab === id ? "bg-indigo-600 text-white" : "text-slate-600"}`}>{label}</button>)}</nav>{tab === "cost" && <CostTable rows={costRows} />}{tab === "invoices" && <SimpleTable title="Project invoice register" columns={["Project", "Vendor", "Invoice #", "Allocated", "Total", "Payment", "Review", "Lifecycle"]} rows={invoiceRows.map((row) => [row.projectCode ? `${row.projectCode} — ${row.project}` : row.project, row.vendor, row.invoiceNumber, `${row.currency} ${row.allocatedAmount.toFixed(2)}`, `${row.currency} ${row.invoiceTotal.toFixed(2)}`, row.paymentStatus, row.reviewStatus, `${row.lifecycleStatus} · ${row.visibility}`])} />}{tab === "payroll" && (showPayrollDetail ? <SimpleTable title="Project payroll summary" columns={["Period", "Worker", "Project", "Role", "Allocated labor", "Status"]} rows={payrollRows.map((row) => [row.period, row.worker, row.project, row.role, `₱${row.allocatedLaborCost.toFixed(2)}`, row.status])} /> : <SimpleTable title="Project labor-cost aggregate" columns={["Project", "Currency", "Confirmed labor", "Pending labor", "Status"]} rows={aggregateRows.map((row) => [`${row.projectCode} — ${row.projectName}`, row.currency, `${row.currency} ${row.confirmedLaborCost.toFixed(2)}`, `${row.currency} ${row.pendingLaborCost.toFixed(2)}`, row.status])} />)}{tab === "expenses" && <SimpleTable title="Project expense register" columns={["Date", "Project", "Category", "Description", "Payee", "Amount", "Status", "Visibility"]} rows={expenseRows.map((row) => [row.date, row.project, row.category, row.description, row.payee, `${row.currency} ${row.amount.toFixed(2)}`, row.status, row.visibility])} />}</div>;
};

const CostTable: React.FC<{ rows: ProjectCostReportRow[] }> = ({ rows }) => <SimpleTable title="Project cost summary" columns={["Project", "Budget", "Invoice cost", "Payroll", "Other expenses", "Actual cost", "Remaining", "Budget %"]} rows={rows.map((row) => [`${row.projectCode} — ${row.projectName}`, `${row.currency} ${row.budget.toFixed(2)}`, `${row.currency} ${row.invoiceCost.toFixed(2)}`, `${row.currency} ${row.payrollCost.toFixed(2)}`, `${row.currency} ${row.otherExpenseCost.toFixed(2)}`, `${row.currency} ${row.totalActualCost.toFixed(2)}`, `${row.currency} ${row.remainingBudget.toFixed(2)}`, `${row.budgetUsedPercent.toFixed(1)}%`])} />;
const SimpleTable: React.FC<{ title: string; columns: string[]; rows: Array<Array<string | number>> }> = ({ title, columns, rows }) => <section className="bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden"><div className="p-5 border-b border-slate-100 flex items-center gap-2"><FileSpreadsheet className="w-4 h-4 text-indigo-600" /><h3 className="text-sm font-black">{title}</h3></div>{rows.length ? <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr>{columns.map((column) => <th key={column} className="px-5 py-3 whitespace-nowrap">{column}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row, index) => <tr key={index} className="hover:bg-slate-50">{row.map((cell, cellIndex) => <td key={cellIndex} className={`px-5 py-3 ${cellIndex > 0 ? "font-sans tabular-nums" : ""}`}>{cell}</td>)}</tr>)}</tbody></table></div> : <div className="p-10 text-center"><BarChart3 className="w-8 h-8 mx-auto text-slate-300" /><p className="mt-3 text-sm font-bold text-slate-700">No report rows yet.</p><p className="text-xs text-slate-500 mt-1">Add projects and source records to populate this report.</p></div>}</section>;

