import React, { useMemo, useState } from "react";
import { CalendarDays, Plus } from "lucide-react";
import type { PayrollPeriod, PayrollPeriodStatus } from "../../types";
import type { PayrollSchedule } from "../../lib/payrollSchedule";
import { payrollPeriodFrequencyLabel } from "../../lib/payrollIntegrity";
import { createLocalPeriod } from "../../lib/payroll";

interface PayrollPeriodsProps { periods: PayrollPeriod[]; schedules?: readonly PayrollSchedule[]; onSave: (period: PayrollPeriod) => void; canManage?: boolean; }

export const PayrollPeriods: React.FC<PayrollPeriodsProps> = ({ periods, schedules, onSave, canManage = true }) => {
  const [editing, setEditing] = useState<PayrollPeriod | null>(null);
  const [includeVoided, setIncludeVoided] = useState(false);
  const activePeriods = useMemo(() => periods.filter((period) => period.status !== "VOID"), [periods]);
  const voidedPeriods = useMemo(() => periods.filter((period) => period.status === "VOID"), [periods]);
  const visiblePeriods = includeVoided ? periods : activePeriods;
  const save = (event: React.FormEvent) => { event.preventDefault(); if (!canManage || !editing?.periodStart || !editing.periodEnd) return; onSave(editing); setEditing(null); };

  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between gap-3 border-b border-slate-100 p-5"><div><h3 className="text-sm font-black">Payroll periods</h3><p className="mt-1 text-xs text-slate-500">Active operational periods stay in the main list; VOID history remains available without inflating the count.</p></div>{canManage && <button onClick={() => setEditing(createLocalPeriod({ periodStart: new Date().toISOString().slice(0, 10), periodEnd: new Date().toISOString().slice(0, 10), status: "DRAFT", notes: "" }))} type="button" className="inline-flex items-center gap-1.5 rounded-xl bg-indigo-600 px-3 py-2 text-xs font-bold text-white"><Plus className="h-3.5 w-3.5" /> New period</button>}</div>
    {voidedPeriods.length > 0 && <div className="flex items-center justify-between gap-2 border-b border-slate-100 bg-slate-50 px-5 py-2.5"><span className="text-[10px] font-bold text-slate-600">Voided history ({voidedPeriods.length})</span><button type="button" aria-pressed={includeVoided} onClick={() => setIncludeVoided((value) => !value)} className="rounded-lg border border-slate-300 bg-white px-2.5 py-1.5 text-[10px] font-bold text-slate-700">{includeVoided ? "Hide voided" : "Include voided"}</button></div>}
    {visiblePeriods.length ? <div className="divide-y divide-slate-100">{visiblePeriods.map((period) => <div key={period.id} className="flex items-center justify-between gap-3 px-5 py-4"><div className="flex min-w-0 items-center gap-3"><CalendarDays className="h-4 w-4 shrink-0 text-indigo-600" /><div className="min-w-0"><p className="truncate text-xs font-bold">{period.periodStart} – {period.periodEnd}</p><p className="truncate text-[10px] text-slate-500">{schedules ? payrollPeriodFrequencyLabel(period, schedules) : "Payroll period"} · Pay date {period.payDate || "not set"}</p></div></div>{canManage ? <button type="button" onClick={() => setEditing(period)} className={`text-[10px] font-bold ${period.status === "VOID" ? "text-slate-500" : "text-indigo-700"}`}>{period.status}</button> : <span className="text-[10px] font-bold text-slate-500">{period.status}</span>}</div>)}</div> : <div className="p-10 text-center"><p className="text-sm font-bold text-slate-700">No active payroll periods yet.</p><p className="mt-1 text-xs text-slate-500">{voidedPeriods.length ? `${voidedPeriods.length} voided historical period${voidedPeriods.length === 1 ? " remains" : "s remain"}. Include voided to inspect it.` : canManage ? "Create Aug 1–15 or Aug 16–31 periods as needed." : "Payroll period management is restricted to payroll managers."}</p></div>}
    {canManage && editing && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={save} className="w-full max-w-md space-y-4 rounded-2xl bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><h3 className="text-lg font-black">Payroll period</h3><button type="button" onClick={() => setEditing(null)} className="text-xl text-slate-400" aria-label="Close payroll period">×</button></div><label className="block space-y-1"><span className="field-label">Period start</span><input type="date" required value={editing.periodStart} onChange={(event) => setEditing({ ...editing, periodStart: event.target.value })} className="field-input" /></label><label className="block space-y-1"><span className="field-label">Period end</span><input type="date" required value={editing.periodEnd} onChange={(event) => setEditing({ ...editing, periodEnd: event.target.value })} className="field-input" /></label><label className="block space-y-1"><span className="field-label">Pay date</span><input type="date" value={editing.payDate || ""} onChange={(event) => setEditing({ ...editing, payDate: event.target.value || undefined })} className="field-input" /></label><label className="block space-y-1"><span className="field-label">Status</span><select value={editing.status} onChange={(event) => setEditing({ ...editing, status: event.target.value as PayrollPeriodStatus })} className="field-input">{["DRAFT", "OPEN", "CALCULATED", "APPROVED", "PAID", "VOID"].map((value) => <option key={value} value={value}>{value}</option>)}</select></label><div className="flex justify-end gap-2"><button type="button" onClick={() => setEditing(null)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold">Cancel</button><button type="submit" className="rounded-xl bg-indigo-600 px-4 py-2 text-xs font-bold text-white">Save period</button></div></form></div>}
  </section>;
};
