import React from "react";
import { AlertTriangle, CheckCircle2, Mail, RotateCcw, ShieldCheck, Undo2 } from "lucide-react";
import { InvoiceData } from "../types";
import { formatMoney } from "../utils/invoiceLogic";

interface ReviewPanelProps { invoice: InvoiceData; onVerify: () => void; onReopen?: () => void; onRevertToAI?: () => void; }

export const ReviewPanel: React.FC<ReviewPanelProps> = ({ invoice, onVerify, onReopen, onRevertToAI }) => {
  const issues = invoice.validation?.issues || [];
  const vat = invoice.validation?.philippineVat;
  const completeness = invoice.philippineInvoiceCompleteness;
  const needsReview = invoice.reviewStatus === "NEEDS_REVIEW";
  return <div className={`rounded-2xl border p-4 shadow-sm ${needsReview ? "bg-amber-50 border-amber-200" : "bg-emerald-50 border-emerald-200"}`}>
    <div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-4">
      <div className="flex gap-3 min-w-0"><div className={`w-9 h-9 rounded-xl flex items-center justify-center shrink-0 ${needsReview ? "bg-amber-100 text-amber-700" : "bg-emerald-100 text-emerald-700"}`}>{needsReview ? <AlertTriangle className="w-4 h-4" /> : <ShieldCheck className="w-4 h-4" />}</div><div className="min-w-0"><h3 className="text-sm font-bold">{needsReview ? "Human verification required" : "Invoice verified"}</h3><p className="text-[10px] text-slate-600 mt-0.5">{issues.length ? `${issues.length} validation flag${issues.length === 1 ? "" : "s"} found.` : "Line totals and financial summary reconcile with the extracted data."}{invoice.confidenceScore !== undefined ? ` • AI confidence ${Math.round(invoice.confidenceScore)}%` : ""}</p>{invoice.sourceType === "EMAIL" && <p className="text-[10px] text-indigo-700 mt-1 flex items-center gap-1 truncate"><Mail className="w-3 h-3 shrink-0" />{invoice.sourceMetadata?.subject || "Extracted from email"}{invoice.sourceMetadata?.sender ? ` • ${invoice.sourceMetadata.sender}` : ""}</p>}</div></div>
      <div className="flex flex-wrap items-center justify-end gap-2 shrink-0">{invoice.aiSnapshot && onRevertToAI && <button onClick={onRevertToAI} className="inline-flex items-center justify-center gap-1.5 px-3 py-2 rounded-xl border border-slate-300 bg-white text-slate-700 text-xs font-bold"><Undo2 className="w-3.5 h-3.5" /> Revert all to AI</button>}{needsReview ? <button onClick={onVerify} className="inline-flex items-center justify-center gap-2 px-3 py-2 rounded-xl bg-emerald-700 hover:bg-emerald-800 text-white text-xs font-bold"><CheckCircle2 className="w-3.5 h-3.5" /> Mark verified</button> : onReopen && <button onClick={onReopen} className="inline-flex items-center justify-center gap-1.5 px-3 py-2 rounded-xl border border-emerald-300 bg-white text-emerald-800 text-xs font-bold"><RotateCcw className="w-3.5 h-3.5" /> Reopen</button>}</div>
    </div>
    {(vat?.applicable || completeness?.status && completeness.status !== "NOT_APPLICABLE" || invoice.withholdingTaxAmount !== undefined) && <div className="grid md:grid-cols-3 gap-2 mt-4"><div className="bg-white/70 rounded-xl p-3"><p className="text-[9px] uppercase font-black text-slate-500">PH VAT validation</p><p className={`text-xs font-black mt-1 ${vat?.status === "PASS" ? "text-emerald-700" : vat?.status === "REVIEW" ? "text-amber-700" : "text-slate-500"}`}>{vat?.status === "PASS" ? "PASS" : vat?.status === "REVIEW" ? "NEEDS REVIEW" : "Not applicable"}</p>{vat?.expectedVat !== undefined && <p className="text-[9px] text-slate-600 mt-1">Expected {formatMoney(vat.expectedVat, invoice.currency || "PHP")} • Difference {formatMoney(vat.difference || 0, invoice.currency || "PHP")}</p>}</div><div className="bg-white/70 rounded-xl p-3"><p className="text-[9px] uppercase font-black text-slate-500">PH Invoice Completeness</p><p className="text-xs font-black mt-1">{completeness?.status?.replaceAll("_", " ") || "Not applicable"}</p><p className="text-[9px] text-slate-600 mt-1">Review aid, not legal certification.</p></div><div className="bg-white/70 rounded-xl p-3"><p className="text-[9px] uppercase font-black text-slate-500">Withholding</p><p className="text-xs font-black mt-1">{invoice.withholdingTaxAmount !== undefined ? formatMoney(invoice.withholdingTaxAmount, invoice.currency || "PHP") : "Not stated"}</p>{invoice.netAmountPayable !== undefined && <p className="text-[9px] text-slate-600 mt-1">Net payable {formatMoney(invoice.netAmountPayable, invoice.currency || "PHP")} • invoice total unchanged</p>}</div></div>}
    {issues.length > 0 && <div className="grid md:grid-cols-2 gap-2 mt-4">{issues.slice(0, 6).map((issue) => <div key={issue.id} className="bg-white/70 rounded-xl p-3 border border-amber-100"><p className="text-[10px] font-bold text-slate-800">{issue.field}</p><p className="text-[10px] text-slate-600 mt-0.5">{issue.message}</p>{issue.expected !== undefined && <p className="text-[9px] text-slate-500 mt-1 font-mono">Expected {String(issue.expected)} • extracted {String(issue.actual)}</p>}</div>)}</div>}
  </div>;
};
