/**
 * Pure payroll calendar projections.
 *
 * This module deliberately does not generate payroll periods from a schedule.
 * A calendar consumes the actual period records that were generated or imported
 * by the payroll domain. That keeps DAILY through CUSTOM schedules, including
 * cross-month and historical periods, visible without re-deriving them here.
 *
 * Date-only arithmetic uses UTC midnight. The only local-time operation is the
 * default "today" value, which uses the host's local calendar date rather than
 * UTC's date.
 */

import type { PayrollEntry, PayrollPeriod, PayrollRun } from "../types.ts";
import type { PayrollImportBatch } from "../lib/payrollImportPersistence.ts";

export type DateOnly = string;
export type PayrollFrequency = "DAILY" | "WEEKLY" | "BIWEEKLY" | "SEMI_MONTHLY" | "MONTHLY" | "CUSTOM";

export type CalendarPeriod = Pick<PayrollPeriod, "id" | "periodStart" | "periodEnd" | "payDate" | "status"> &
  Partial<Pick<PayrollPeriod, "scheduleId" | "scheduleVersionId" | "autoGenerated" | "lockedAt">>;

export type CalendarRun = Pick<PayrollRun, "id" | "periodId" | "status">;
export type CalendarEntry = Pick<PayrollEntry, "id" | "payrollRunId" | "calculationSnapshot">;

export interface PayrollIssue {
  code?: string;
  severity?: string;
  message: string;
  workerId?: string;
  workEntryIds?: string[];
  amount?: number;
  expected?: number;
  actual?: number;
}

export interface AutomaticPayrollDraftRecord {
  periodId?: string;
  runId?: string;
  exceptions?: readonly PayrollIssue[];
  readiness?: string;
  entries?: readonly { periodId?: string; source?: unknown }[];
}

export interface PayrollCalendarLookupInput {
  periods?: readonly CalendarPeriod[];
  runs?: readonly CalendarRun[];
  entries?: readonly CalendarEntry[];
  automaticDrafts?: readonly AutomaticPayrollDraftRecord[];
  /** A single not-yet-persisted draft may be supplied for the selected period. */
  automaticDraft?: AutomaticPayrollDraftRecord;
  importBatches?: readonly PayrollImportBatch[];
}

export interface PayrollPeriodSlice {
  period: CalendarPeriod;
  periodId: string;
  monthStart: DateOnly;
  monthEnd: DateOnly;
  sliceStart: DateOnly;
  sliceEnd: DateOnly;
  startsInMonth: boolean;
  endsInMonth: boolean;
  spansMonth: boolean;
}

export interface PayrollCutoffMarker {
  date: DateOnly;
  periodId: string;
  periodStart: DateOnly;
  periodEnd: DateOnly;
  kind: "PERIOD_END";
}

export interface PayrollPayDateMarker {
  date: DateOnly;
  periodId: string;
  periodStart: DateOnly;
  periodEnd: DateOnly;
  kind: "PAY_DATE";
}

export interface PayrollRunStatusMarker {
  periodId: string;
  runId?: string;
  status?: string;
}

export interface PayrollIssueSummary {
  periodId: string;
  issueCount: number;
  blockingCount: number;
  warningCount: number;
  issues: PayrollIssue[];
  readiness?: string;
}

export interface ImportedPayrollActivity {
  periodId: string;
  batchIds: string[];
  batchCount: number;
  latestBatchId?: string;
  latestCreatedAt?: string;
  statuses: string[];
  hasCommittedImport: boolean;
}

export interface PayrollCalendarDay {
  date: DateOnly;
  dayOfMonth: number;
  weekday: number;
  isCurrentMonth: boolean;
  isToday: boolean;
  periodIds: string[];
  periodSlices: PayrollPeriodSlice[];
  cutoffMarkers: PayrollCutoffMarker[];
  payDateMarkers: PayrollPayDateMarker[];
  runStatuses: PayrollRunStatusMarker[];
  issueSummary?: PayrollIssueSummary;
  importedActivity?: ImportedPayrollActivity;
}

export interface PayrollMonthGridOptions extends PayrollCalendarLookupInput {
  /** Defaults to the host-local calendar date. */
  today?: DateOnly | Date;
  /** Defaults to true for a stable six-row month layout. */
  fixedWeeks?: boolean;
}

export interface PayrollMonthGrid {
  year: number;
  month: number;
  monthStart: DateOnly;
  monthEnd: DateOnly;
  gridStart: DateOnly;
  gridEnd: DateOnly;
  weeks: PayrollCalendarDay[][];
  days: PayrollCalendarDay[];
}

const DATE_ONLY = /^\d{4}-\d{2}-\d{2}$/;

function utcDate(date: DateOnly): Date {
  return new Date(`${date}T00:00:00.000Z`);
}

function localDateOnly(value: Date): DateOnly {
  const year = value.getFullYear();
  const month = String(value.getMonth() + 1).padStart(2, "0");
  const day = String(value.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function assertDateOnly(value: string, label = "date"): asserts value is DateOnly {
  if (!DATE_ONLY.test(value)) throw new Error(`${label} must be a valid YYYY-MM-DD date.`);
  const parsed = utcDate(value);
  if (parsed.getUTCFullYear() !== Number(value.slice(0, 4)) || parsed.getUTCMonth() + 1 !== Number(value.slice(5, 7)) || parsed.getUTCDate() !== Number(value.slice(8, 10))) {
    throw new Error(`${label} must be a valid YYYY-MM-DD date.`);
  }
}

function dateOnly(value: DateOnly | Date | undefined, fallbackToday = true): DateOnly {
  if (value instanceof Date) {
    if (Number.isNaN(value.getTime())) throw new Error("today must be a valid Date.");
    return localDateOnly(value);
  }
  if (value !== undefined) {
    assertDateOnly(value);
    return value;
  }
  if (fallbackToday) return localDateOnly(new Date());
  throw new Error("A date is required.");
}

function compare(left: DateOnly, right: DateOnly) {
  return left < right ? -1 : left > right ? 1 : 0;
}

function addDays(value: DateOnly, amount: number): DateOnly {
  const result = utcDate(value);
  result.setUTCDate(result.getUTCDate() + amount);
  return result.toISOString().slice(0, 10);
}

function daysInMonth(year: number, month: number) {
  return new Date(Date.UTC(year, month, 0)).getUTCDate();
}

function monthValue(year: number, month: number, day: number): DateOnly {
  return `${String(year).padStart(4, "0")}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
}

function monthBounds(year: number, month: number) {
  if (!Number.isInteger(year) || year < 1 || year > 9999 || !Number.isInteger(month) || month < 1 || month > 12) throw new Error("year and month must describe a valid calendar month.");
  return { start: monthValue(year, month, 1), end: monthValue(year, month, daysInMonth(year, month)) };
}

function normalizedPeriod(period: CalendarPeriod): CalendarPeriod {
  assertDateOnly(period.periodStart, "periodStart");
  assertDateOnly(period.periodEnd, "periodEnd");
  if (compare(period.periodStart, period.periodEnd) > 0) throw new Error(`Payroll period ${period.id} ends before it starts.`);
  if (period.payDate) assertDateOnly(period.payDate, "payDate");
  return period;
}

function sortedPeriods(periods: readonly CalendarPeriod[] = []) {
  return periods.map(normalizedPeriod).slice().sort((a, b) => compare(a.periodStart, b.periodStart) || compare(a.periodEnd, b.periodEnd) || a.id.localeCompare(b.id));
}

function periodIdOf(periodOrId: CalendarPeriod | string) {
  return typeof periodOrId === "string" ? periodOrId : periodOrId.id;
}

function periodFor(periodOrId: CalendarPeriod | string, periods: readonly CalendarPeriod[] = []) {
  return typeof periodOrId === "string" ? sortedPeriods(periods).find((period) => period.id === periodOrId) : normalizedPeriod(periodOrId);
}

function periodMatches(period: CalendarPeriod, periodOrId: CalendarPeriod | string) {
  return typeof periodOrId === "string" ? period.id === periodOrId : period.id === periodOrId.id || (period.periodStart === periodOrId.periodStart && period.periodEnd === periodOrId.periodEnd);
}

/** Returns the host-local calendar date, intentionally independent of UTC. */
export function getLocalToday(now = new Date()): DateOnly {
  return dateOnly(now);
}

export const todayDateOnly = getLocalToday;

export function formatPayrollPeriodLabel(period: Pick<PayrollPeriod, "periodStart" | "periodEnd">, frequency?: PayrollFrequency): string {
  assertDateOnly(period.periodStart, "periodStart");
  assertDateOnly(period.periodEnd, "periodEnd");
  const startDate = utcDate(period.periodStart);
  const endDate = utcDate(period.periodEnd);
  const short = (value: Date) => new Intl.DateTimeFormat("en-PH", { month: "short", day: "numeric", timeZone: "UTC" }).format(value);
  const month = (value: Date) => new Intl.DateTimeFormat("en-PH", { month: "long", year: "numeric", timeZone: "UTC" }).format(value);
  const sameDay = period.periodStart === period.periodEnd;
  const monthEnd = new Date(Date.UTC(endDate.getUTCFullYear(), endDate.getUTCMonth() + 1, 0)).getUTCDate();
  if (frequency === "MONTHLY" || (startDate.getUTCDate() === 1 && endDate.getUTCDate() === monthEnd)) return month(startDate);
  if (sameDay || frequency === "DAILY") return short(startDate);
  const sameMonth = startDate.getUTCFullYear() === endDate.getUTCFullYear() && startDate.getUTCMonth() === endDate.getUTCMonth();
  const endLabel = sameMonth ? String(endDate.getUTCDate()) : short(endDate);
  const startLabel = short(startDate);
  return `${startLabel}–${endLabel}${startDate.getUTCFullYear() === endDate.getUTCFullYear() ? `, ${endDate.getUTCFullYear()}` : ` ${endDate.getUTCFullYear()}`}`;
}

/**
 * Active calendar semantics: VOID periods are retired history. They must not
 * drive day counts, slices, markers, conflicts, or selection on the active
 * calendar, while explicit history surfaces may still list them.
 */
export function isActiveCalendarPeriod(period: CalendarPeriod): boolean {
  return period.status !== "VOID";
}

export interface PayrollCalendarConflict {
  periodIds: string[];
  overlapStart: DateOnly;
  overlapEnd: DateOnly;
}

export function findPayrollCalendarConflicts(periods: readonly CalendarPeriod[]): PayrollCalendarConflict[] {
  const active = sortedPeriods(periods).filter(isActiveCalendarPeriod);
  const conflicts: PayrollCalendarConflict[] = [];
  for (let leftIndex = 0; leftIndex < active.length; leftIndex += 1) {
    for (let rightIndex = leftIndex + 1; rightIndex < active.length; rightIndex += 1) {
      const left = active[leftIndex]!;
      const right = active[rightIndex]!;
      if (right.periodStart > left.periodEnd) break;
      if (left.id === right.id || left.periodStart === right.periodStart && left.periodEnd === right.periodEnd) continue;
      const overlapStart = left.periodStart > right.periodStart ? left.periodStart : right.periodStart;
      const overlapEnd = left.periodEnd < right.periodEnd ? left.periodEnd : right.periodEnd;
      if (overlapStart <= overlapEnd) conflicts.push({ periodIds: [left.id, right.id], overlapStart, overlapEnd });
    }
  }
  return conflicts;
}

/** Monday is column zero; Sunday is column six. */
export function mondayFirstWeekday(date: DateOnly): number {
  assertDateOnly(date);
  const sundayFirst = utcDate(date).getUTCDay();
  return sundayFirst === 0 ? 6 : sundayFirst - 1;
}

export function getPeriodIntersection(period: CalendarPeriod, month: { year: number; month: number } | DateOnly): PayrollPeriodSlice | undefined {
  const normalized = normalizedPeriod(period);
  const bounds = typeof month === "string"
    ? (() => {
      assertDateOnly(month);
      const year = Number(month.slice(0, 4));
      const monthNumber = Number(month.slice(5, 7));
      return monthBounds(year, monthNumber);
    })()
    : monthBounds(month.year, month.month);
  const sliceStart = compare(normalized.periodStart, bounds.start) > 0 ? normalized.periodStart : bounds.start;
  const sliceEnd = compare(normalized.periodEnd, bounds.end) < 0 ? normalized.periodEnd : bounds.end;
  if (compare(sliceStart, sliceEnd) > 0) return undefined;
  return { period: normalized, periodId: normalized.id, monthStart: bounds.start, monthEnd: bounds.end, sliceStart, sliceEnd, startsInMonth: normalized.periodStart >= bounds.start && normalized.periodStart <= bounds.end, endsInMonth: normalized.periodEnd >= bounds.start && normalized.periodEnd <= bounds.end, spansMonth: normalized.periodStart < bounds.start || normalized.periodEnd > bounds.end };
}

export function getPayrollPeriodSlices(periods: readonly CalendarPeriod[], year: number, month: number): PayrollPeriodSlice[] {
  return sortedPeriods(periods).filter(isActiveCalendarPeriod).flatMap((period) => { const slice = getPeriodIntersection(period, { year, month }); return slice ? [slice] : []; });
}

export const periodSlicesForMonth = getPayrollPeriodSlices;
export const intersectPayrollPeriod = getPeriodIntersection;

export function getCutoffMarkers(periods: readonly CalendarPeriod[], month?: { year: number; month: number }): PayrollCutoffMarker[] {
  const bounds = month ? monthBounds(month.year, month.month) : undefined;
  return sortedPeriods(periods).filter(isActiveCalendarPeriod).flatMap((period) => {
    const markers: PayrollCutoffMarker[] = [{ date: period.periodEnd, periodId: period.id, periodStart: period.periodStart, periodEnd: period.periodEnd, kind: "PERIOD_END" }];
    return bounds ? markers.filter((marker) => marker.date >= bounds.start && marker.date <= bounds.end) : markers;
  });
}

export const getPayrollCutoffMarkers = getCutoffMarkers;

export function getPayDateMarkers(periods: readonly CalendarPeriod[], month?: { year: number; month: number }): PayrollPayDateMarker[] {
  const bounds = month ? monthBounds(month.year, month.month) : undefined;
  return sortedPeriods(periods).filter(isActiveCalendarPeriod).flatMap((period) => period.payDate ? [{ date: period.payDate, periodId: period.id, periodStart: period.periodStart, periodEnd: period.periodEnd, kind: "PAY_DATE" as const }] : []).filter((marker) => !bounds || (marker.date >= bounds.start && marker.date <= bounds.end));
}

export const getPayrollPayDateMarkers = getPayDateMarkers;

function runsFor(periodId: string, runs: readonly CalendarRun[] = []): PayrollRunStatusMarker[] {
  return runs.filter((run) => run.periodId === periodId).sort((a, b) => a.id.localeCompare(b.id)).map((run) => ({ periodId, runId: run.id, status: run.status }));
}

export function getRunStatus(periodOrId: CalendarPeriod | string, runs: readonly CalendarRun[] = []): string | undefined {
  const matches = runsFor(periodIdOf(periodOrId), runs);
  return matches[0]?.status;
}

export const lookupPayrollRunStatus = getRunStatus;

function snapshotIssues(entry: CalendarEntry): PayrollIssue[] {
  const snapshot = entry.calculationSnapshot;
  if (!snapshot || typeof snapshot !== "object") return [];
  const issues = (snapshot as Record<string, unknown>).exceptions;
  return Array.isArray(issues) ? issues.filter((issue): issue is PayrollIssue => Boolean(issue && typeof issue === "object" && typeof (issue as Record<string, unknown>).message === "string")).map((issue) => ({ ...issue })) : [];
}

function draftIssues(draft: AutomaticPayrollDraftRecord | undefined): PayrollIssue[] {
  return Array.isArray(draft?.exceptions) ? draft.exceptions.map((issue) => ({ ...issue })) : [];
}

function periodDrafts(periodId: string, drafts: readonly AutomaticPayrollDraftRecord[] = [], single?: AutomaticPayrollDraftRecord) {
  return [...drafts, ...(single ? [single] : [])].filter((draft) => draft.periodId === periodId || draft.entries?.some((entry) => entry.periodId === periodId));
}

/**
 * Collects automatic-draft exceptions and persisted entry snapshot exceptions.
 * It is intentionally empty when no source records were supplied.
 */
export function getIssueSummary(periodOrId: CalendarPeriod | string, input: PayrollCalendarLookupInput = {}): PayrollIssueSummary {
  const periodId = periodIdOf(periodOrId);
  const issues = [
    ...periodDrafts(periodId, input.automaticDrafts, input.automaticDraft).flatMap(draftIssues),
    ...(input.entries || []).filter((entry) => {
      const run = (input.runs || []).find((candidate) => candidate.id === entry.payrollRunId);
      return run?.periodId === periodId;
    }).flatMap(snapshotIssues),
  ];
  const unique = new Map<string, PayrollIssue>();
  issues.forEach((issue, index) => unique.set(`${issue.code || "ISSUE"}:${issue.workerId || ""}:${issue.message}`, issue));
  const stableIssues = [...unique.values()];
  return { periodId, issueCount: stableIssues.length, blockingCount: stableIssues.filter((issue) => String(issue.severity).toUpperCase() === "BLOCKING" || String(issue.severity).toUpperCase() === "ERROR").length, warningCount: stableIssues.filter((issue) => String(issue.severity).toUpperCase() === "WARNING" || String(issue.severity).toUpperCase() === "WARN").length, issues: stableIssues, readiness: periodDrafts(periodId, input.automaticDrafts, input.automaticDraft)[0]?.readiness };
}

export const lookupPayrollIssueSummary = getIssueSummary;

function metadataPeriodId(batch: PayrollImportBatch): string | undefined {
  const metadata = batch.rawMetadata && typeof batch.rawMetadata === "object" ? batch.rawMetadata as Record<string, unknown> : {};
  const mapping = batch.mappingSnapshot && typeof batch.mappingSnapshot === "object" ? batch.mappingSnapshot as Record<string, unknown> : {};
  const direct = metadata.periodId ?? metadata.period_id ?? mapping.periodId ?? mapping.period_id;
  return typeof direct === "string" && direct ? direct : undefined;
}

function importedBatchMatches(batch: PayrollImportBatch, period: CalendarPeriod): boolean {
  if (batch.committedPayrollPeriodId === period.id || metadataPeriodId(batch) === period.id) return true;
  const metadata = batch.rawMetadata && typeof batch.rawMetadata === "object" ? batch.rawMetadata as Record<string, unknown> : {};
  const start = metadata.periodStart ?? metadata.period_start;
  const end = metadata.periodEnd ?? metadata.period_end;
  return typeof start === "string" && typeof end === "string" && start === period.periodStart && end === period.periodEnd;
}

export function getImportedActivity(periodOrId: CalendarPeriod | string, batches: readonly PayrollImportBatch[] = [], periods: readonly CalendarPeriod[] = []): ImportedPayrollActivity | undefined {
  const requestedPeriodId = periodIdOf(periodOrId);
  const period = periodFor(periodOrId, periods);
  const matching = batches.filter((batch) => batch.status !== "VOIDED" && (batch.committedPayrollPeriodId === requestedPeriodId || metadataPeriodId(batch) === requestedPeriodId || (period ? importedBatchMatches(batch, period) : false))).slice().sort((a, b) => b.createdAt.localeCompare(a.createdAt) || b.id.localeCompare(a.id));
  if (!matching.length) return undefined;
  return { periodId: requestedPeriodId, batchIds: matching.map((batch) => batch.id), batchCount: matching.length, latestBatchId: matching[0]?.id, latestCreatedAt: matching[0]?.createdAt, statuses: [...new Set(matching.map((batch) => batch.status))], hasCommittedImport: matching.some((batch) => batch.status === "COMMITTED" || batch.committedPayrollPeriodId === requestedPeriodId) };
}

export const lookupImportedPayrollActivity = getImportedActivity;

function dayRecord(date: DateOnly, monthStart: DateOnly, monthEnd: DateOnly, periods: readonly CalendarPeriod[], options: PayrollMonthGridOptions): PayrollCalendarDay {
  const slices = periods.filter((period) => period.periodStart <= date && period.periodEnd >= date).flatMap((period) => { const slice = getPeriodIntersection(period, date); return slice ? [{ ...slice, sliceStart: date, sliceEnd: date }] : []; });
  const periodIds = [...new Set(slices.map((slice) => slice.periodId))];
  const cutoffMarkers = getCutoffMarkers(periods).filter((marker) => marker.date === date);
  const payDateMarkers = getPayDateMarkers(periods).filter((marker) => marker.date === date);
  const runStatuses = periodIds.flatMap((periodId) => runsFor(periodId, options.runs));
  const issueSummary = periodIds.map((periodId) => getIssueSummary(periodId, options)).find((summary) => summary.issueCount > 0);
  const importedActivity = periodIds.map((periodId) => getImportedActivity(periodId, options.importBatches, periods)).find(Boolean);
  return { date, dayOfMonth: Number(date.slice(8, 10)), weekday: mondayFirstWeekday(date), isCurrentMonth: date >= monthStart && date <= monthEnd, isToday: date === dateOnly(options.today), periodIds, periodSlices: slices, cutoffMarkers, payDateMarkers, runStatuses, issueSummary, importedActivity };
}

/** Generates a Monday-first grid from actual payroll period records. */
export function buildPayrollMonthGrid(year: number, month: number, options: PayrollMonthGridOptions = {}): PayrollMonthGrid {
  const bounds = monthBounds(year, month);
  const periods = sortedPeriods(options.periods || []).filter(isActiveCalendarPeriod);
  const today = dateOnly(options.today);
  const leading = mondayFirstWeekday(bounds.start);
  const trailing = 6 - mondayFirstWeekday(bounds.end);
  const naturalDays = leading + Number(bounds.end.slice(8, 10)) + trailing;
  const count = options.fixedWeeks === false ? naturalDays : Math.max(42, naturalDays);
  const gridStart = addDays(bounds.start, -leading);
  const internal = { ...options, today, __monthEnd: bounds.end } as PayrollMonthGridOptions & { __monthEnd: DateOnly };
  const days = Array.from({ length: count }, (_, index) => dayRecord(addDays(gridStart, index), bounds.start, bounds.end, periods, internal));
  return { year, month, monthStart: bounds.start, monthEnd: bounds.end, gridStart, gridEnd: days[days.length - 1]!.date, weeks: Array.from({ length: days.length / 7 }, (_, index) => days.slice(index * 7, index * 7 + 7)), days };
}

export const generatePayrollMonthGrid = buildPayrollMonthGrid;
export const buildMonthGrid = buildPayrollMonthGrid;

/** Selects a period without changing it merely because an input array was reordered. */
export function selectStablePayrollPeriod(periods: readonly CalendarPeriod[], selectedPeriodId?: string, today?: DateOnly | Date): CalendarPeriod | undefined {
  const eligible = sortedPeriods(periods).filter((period) => period.status !== "VOID");
  const selected = selectedPeriodId ? eligible.find((period) => period.id === selectedPeriodId) : undefined;
  if (selected) return selected;
  const currentDate = dateOnly(today);
  const current = eligible.filter((period) => period.periodStart <= currentDate && period.periodEnd >= currentDate)[0];
  if (current) return current;
  return eligible.filter((period) => period.periodStart > currentDate)[0] || eligible.filter((period) => period.periodEnd < currentDate).at(-1);
}

export function selectStablePayrollPeriodId(periods: readonly CalendarPeriod[], selectedPeriodId?: string, today?: DateOnly | Date) {
  return selectStablePayrollPeriod(periods, selectedPeriodId, today)?.id;
}

export const getStableSelectedPeriod = selectStablePayrollPeriod;
export const getStableSelectedPeriodId = selectStablePayrollPeriodId;
