import type { InvoiceData, InvoiceProjectAllocation, Project, ProjectStatus } from "../types.ts";

export type ProjectMatchField = "projectReference" | "code" | "name" | "client" | "location" | "manager";
export interface ProjectMatchInput { projectReference?: unknown; projectCode?: unknown; projectName?: unknown; client?: unknown; customerName?: unknown; customer?: { name?: unknown; companyName?: unknown; registeredName?: unknown; address?: unknown; city?: unknown; province?: unknown }; vendor?: { name?: unknown; companyName?: unknown; registeredName?: unknown }; location?: unknown; manager?: unknown; projectManager?: unknown; purchaseOrderNumber?: unknown; notes?: unknown; category?: unknown; costCenter?: unknown; }
export interface ProjectMatchResult { project: Project; score: number; matchedFields: ProjectMatchField[]; confidence: "EXACT" | "LIKELY" | "POSSIBLE"; }
export interface ProjectSearchFilters { query?: string; status?: ProjectStatus | string | "ALL"; includeArchived?: boolean; }
export interface ProjectInvoiceAllocationPresentation { invoiceId: string; invoiceLabel: string; vendorLabel: string; dateLabel: string; invoiceAmount: number | null; allocatedAmount: number | null; amountLabel: string; currencyLabel: string; allocationLabel: string; allocationStatus: "ALLOCATED" | "PARTIAL" | "UNALLOCATED"; sourceLabel: string; paymentLabel: string; }

function asText(value: unknown) { return value === null || value === undefined ? "" : String(value).trim(); }
export function normalizeProjectText(value: unknown) { return asText(value).normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").replace(/\s+/g, " ").trim(); }
export function getProjectSearchText(project: Project) { return normalizeProjectText([project.projectCode, project.projectName, project.clientName, project.location, project.siteAddress, project.projectManager, project.description, project.status].filter(Boolean).join(" ")); }
export function getProjectInvoiceSearchText(invoice: InvoiceData) { return normalizeProjectText([invoice.invoiceNumber, invoice.invoiceDate, invoice.projectReference, invoice.currency, invoice.vendor?.name, invoice.vendor?.registeredName, invoice.customer?.name, invoice.status, invoice.reviewStatus].filter(Boolean).join(" ")); }
export function projectSearchMatches(project: Project, query: string) { const tokens = normalizeProjectText(query).split(" ").filter(Boolean); const haystack = getProjectSearchText(project); return tokens.every((token) => haystack.includes(token)); }
export function filterProjects(projects: readonly Project[], filters: ProjectSearchFilters = {}) { return projects.filter((project) => { const archived = Boolean(project.archivedAt) || project.status === "ARCHIVED"; if (archived && !filters.includeArchived) return false; if (filters.status && filters.status !== "ALL" && project.status !== filters.status) return false; return projectSearchMatches(project, filters.query || ""); }); }
export function sortProjects(projects: readonly Project[]) { return [...projects].sort((left, right) => (right.updatedAt || right.createdAt).localeCompare(left.updatedAt || left.createdAt) || normalizeProjectText(left.projectName).localeCompare(normalizeProjectText(right.projectName)) || left.projectCode.localeCompare(right.projectCode)); }

function sourceValues(invoice: ProjectMatchInput): Array<{ field: ProjectMatchField; values: string[] }> { return [
  { field: "projectReference", values: [invoice.projectReference].map(asText).filter(Boolean) },
  { field: "code", values: [invoice.projectCode, invoice.projectReference, invoice.purchaseOrderNumber].map(asText).filter(Boolean) },
  { field: "name", values: [invoice.projectName, invoice.projectReference, invoice.notes].map(asText).filter(Boolean) },
  { field: "client", values: [invoice.client, invoice.customerName, invoice.customer?.name, invoice.customer?.companyName, invoice.customer?.registeredName].map(asText).filter(Boolean) },
  { field: "location", values: [invoice.location, invoice.customer?.address, invoice.customer?.city, invoice.customer?.province].map(asText).filter(Boolean) },
  { field: "manager", values: [invoice.manager, invoice.projectManager, invoice.notes, invoice.category, invoice.costCenter].map(asText).filter(Boolean) },
]; }
const weights: Record<ProjectMatchField, number> = { projectReference: 100, code: 96, name: 82, client: 68, location: 44, manager: 40 };
const fieldOrder: ProjectMatchField[] = ["projectReference", "code", "name", "client", "location", "manager"];
function candidateValue(project: Project, field: ProjectMatchField) { if (field === "code" || field === "projectReference") return project.projectCode; if (field === "name") return project.projectName; if (field === "client") return project.clientName || ""; if (field === "location") return project.location || project.siteAddress || ""; return project.projectManager || ""; }
function valueScore(source: string, target: string, weight: number) { const a = normalizeProjectText(source); const b = normalizeProjectText(target); if (!a || !b) return 0; if (a === b) return weight; if (a.includes(b) || b.includes(a)) return weight * 0.78; const sourceTokens = new Set(a.split(" ")); const targetTokens = b.split(" ").filter((token) => token.length > 1); const overlap = targetTokens.filter((token) => sourceTokens.has(token)).length; return overlap ? weight * 0.5 * overlap / targetTokens.length : 0; }

export function rankProjectMatches(invoice: ProjectMatchInput, projects: readonly Project[], options: { minScore?: number; limit?: number; includeArchived?: boolean } = {}): ProjectMatchResult[] { const sources = sourceValues(invoice); return projects.flatMap((project) => { if (!options.includeArchived && (project.status === "ARCHIVED" || project.archivedAt)) return []; const matchedFields: ProjectMatchField[] = []; let score = 0; for (const field of fieldOrder) { const source = sources.find((item) => item.field === field); const best = source?.values.reduce((highest, item) => Math.max(highest, valueScore(item, candidateValue(project, field), weights[field])), 0) || 0; if (best > 0) { matchedFields.push(field); score += best; } } const normalizedScore = Math.min(100, Math.round(score * 100) / 100); return normalizedScore >= (options.minScore ?? 18) ? [{ project, score: normalizedScore, matchedFields, confidence: normalizedScore >= 90 ? "EXACT" as const : normalizedScore >= 50 ? "LIKELY" as const : "POSSIBLE" as const }] : []; }).sort((left, right) => right.score - left.score || right.matchedFields.length - left.matchedFields.length || left.project.projectCode.localeCompare(right.project.projectCode) || left.project.id.localeCompare(right.project.id)).slice(0, options.limit || Number.POSITIVE_INFINITY); }
export function findBestProjectMatch(invoice: ProjectMatchInput, projects: readonly Project[], options?: { minScore?: number; includeArchived?: boolean }) { return rankProjectMatches(invoice, projects, { ...options, limit: 1 })[0] || null; }
export function suggestProjectMatches(invoice: ProjectMatchInput, projects: readonly Project[], limit = 3) { return rankProjectMatches(invoice, projects, { limit }).map((match) => ({ ...match, reasons: match.matchedFields.map((field) => field === "projectReference" ? "project reference" : field === "code" ? "project code" : field === "name" ? "project name" : field) })); }

function money(value: number | null, currency: string) { if (value === null) return "Amount unclear"; try { return new Intl.NumberFormat(currency === "PHP" ? "en-PH" : "en-US", { style: "currency", currency, maximumFractionDigits: 2 }).format(value); } catch { return `${currency} ${value.toFixed(2)}`; } }
export function getProjectInvoiceAllocationPresentation(invoice: InvoiceData, allocation?: InvoiceProjectAllocation, source?: "ALLOCATION" | "PROJECT_REFERENCE" | "MANUAL_MATCH"): ProjectInvoiceAllocationPresentation { const total = Number.isFinite(Number(invoice.grandTotal)) ? Number(invoice.grandTotal) : null; const amount = allocation ? allocation.allocationType === "PERCENTAGE" ? total === null ? null : Math.round(total * (allocation.allocationPercentage || 0)) / 100 : allocation.allocationAmount : null; const ratio = total && amount !== null ? amount / total : 0; const status = amount === null ? "UNALLOCATED" : ratio >= 0.9999 ? "ALLOCATED" : "PARTIAL"; return { invoiceId: invoice.id, invoiceLabel: invoice.invoiceNumber || "Invoice number missing", vendorLabel: invoice.vendor?.name || invoice.vendor?.registeredName || "Vendor unknown", dateLabel: invoice.invoiceDate || "Date missing", invoiceAmount: total, allocatedAmount: amount, amountLabel: amount === null ? "Unallocated" : money(amount, invoice.currency || "PHP"), currencyLabel: invoice.currency || "Currency unclear", allocationLabel: amount === null ? "Unallocated" : status === "ALLOCATED" ? "Fully allocated" : `${total ? Math.round(ratio * 100) : 0}% allocated`, allocationStatus: status, sourceLabel: source === "PROJECT_REFERENCE" ? "Suggested from reference" : source === "MANUAL_MATCH" ? "Manual match" : allocation ? "Confirmed allocation" : "No project assignment", paymentLabel: invoice.status ? invoice.status.replaceAll("_", " ") : "Payment unknown" }; }

