-- Phase 1A hardening.  This migration is additive and intentionally leaves the
-- foundation migration immutable.  Revision source objects are uploaded once,
-- then linked by an atomic metadata transaction; historical rows and files are
-- never replaced by normal application users.

-- A document's current revision is a same-company, same-document relationship.
-- The original foundation migration supplied only a single-column foreign key,
-- so keep the stronger invariant in a trigger that also covers malformed API
-- requests and direct SQL updates.
create or replace function private.validate_engineering_current_revision()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_revision public.engineering_document_revisions;
begin
  if new.current_revision_id is null then
    return new;
  end if;

  select * into v_revision
  from public.engineering_document_revisions r
  where r.id = new.current_revision_id;

  if not found
     or v_revision.company_id is distinct from new.company_id
     or v_revision.document_id is distinct from new.id then
    raise exception 'Current engineering revision must belong to the same company and document'
      using errcode = '23514';
  end if;

  return new;
end;
$$;

drop trigger if exists engineering_documents_current_revision on public.engineering_documents;
create trigger engineering_documents_current_revision
  before insert or update on public.engineering_documents
  for each row execute function private.validate_engineering_current_revision();

-- Revision source/provenance rows are append-only.  Soft-deleting an annotation
-- remains supported, but a committed revision row cannot be edited or removed.
create or replace function private.prevent_engineering_revision_mutation()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  raise exception 'Engineering document revisions are append-only historical records'
    using errcode = '55000';
end;
$$;

drop trigger if exists engineering_document_revisions_append_only on public.engineering_document_revisions;
create trigger engineering_document_revisions_append_only
  before update or delete on public.engineering_document_revisions
  for each row execute function private.prevent_engineering_revision_mutation();

-- Every new revision must point at the exact immutable object generated by the
-- client upload flow and carry a real normalized SHA-256 digest.  Existing
-- legacy rows are not rewritten by this migration; new inserts are fail-closed.
create or replace function private.validate_engineering_revision_source()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if lower(btrim(new.file_type)) <> 'application/pdf' then
    raise exception 'Engineering revision sources must be PDF files' using errcode = '22023';
  end if;

  if new.file_fingerprint !~ '^sha256:[0-9a-f]{64}$' then
    raise exception 'Engineering revision source fingerprint must be sha256:<64 lowercase hex characters>'
      using errcode = '22023';
  end if;

  if new.file_path !~ format(
    '^companies/%s/documents/%s/revisions/%s/[^/]+$',
    new.company_id,
    new.document_id,
    new.id
  ) then
    raise exception 'Engineering revision source path is not bound to its company, document, and revision'
      using errcode = '22023';
  end if;

  return new;
end;
$$;

drop trigger if exists engineering_document_revisions_source on public.engineering_document_revisions;
create trigger engineering_document_revisions_source
  before insert on public.engineering_document_revisions
  for each row execute function private.validate_engineering_revision_source();

-- Remove normal application mutation capability for committed revision source
-- files.  No update or delete policy is recreated here; Storage RLS therefore
-- denies those operations even to managers.  Exceptional retention deletion is
-- deliberately outside this milestone.
drop policy if exists "company engineering documents update" on storage.objects;
drop policy if exists "company engineering documents delete" on storage.objects;
revoke update, delete on table public.engineering_document_revisions from authenticated;

-- The Storage upload and the metadata link cannot share a transaction.  These
-- two narrowly-scoped, audited RPCs make the database portion atomic and are
-- explicit about the create permission.  SECURITY DEFINER is required because
-- the initial document insert and current-revision update are one create
-- operation; the functions authenticate the caller, check the company
-- capability, use an empty search path, and are callable only by authenticated.
create or replace function public.create_engineering_document_with_revision(
  p_company_id uuid,
  p_document_id uuid,
  p_revision_id uuid,
  p_project_id uuid,
  p_document_number text,
  p_title text,
  p_description text,
  p_discipline text,
  p_document_type text,
  p_tags text[],
  p_metadata jsonb,
  p_revision_number text,
  p_revision_label text,
  p_file_name text,
  p_file_path text,
  p_file_size_bytes bigint,
  p_file_type text,
  p_file_fingerprint text,
  p_page_count integer,
  p_sheet_size text,
  p_scale text,
  p_change_summary text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_doc public.engineering_documents;
  v_revision public.engineering_document_revisions;
begin
  if v_user_id is null
     or not (
       (select public.has_company_permission(p_company_id, 'engineering.documents.create'))
       or (select public.has_company_permission(p_company_id, 'engineering.documents.manage'))
     ) then
    raise exception 'Engineering document create permission is required' using errcode = '42501';
  end if;

  if not exists (
    select 1 from storage.objects o
    where o.bucket_id = 'engineering-documents' and o.name = p_file_path
  ) then
    raise exception 'The uploaded engineering PDF object was not found in private Storage' using errcode = '22023';
  end if;

  insert into public.engineering_documents (
    id, company_id, project_id, document_number, title, description, discipline,
    document_type, status, current_revision_number, tags, metadata, created_by_user_id
  ) values (
    p_document_id, p_company_id, p_project_id, btrim(p_document_number), btrim(p_title),
    nullif(btrim(p_description), ''), p_discipline, p_document_type, 'DRAFT', '0',
    coalesce(p_tags, '{}'::text[]), coalesce(p_metadata, '{}'::jsonb), v_user_id
  );

  insert into public.engineering_document_revisions (
    id, company_id, document_id, revision_number, revision_label, file_name, file_path,
    file_size_bytes, file_type, file_fingerprint, page_count, sheet_size, scale,
    change_summary, status, created_by_user_id
  ) values (
    p_revision_id, p_company_id, p_document_id, btrim(p_revision_number),
    nullif(btrim(p_revision_label), ''), btrim(p_file_name), btrim(p_file_path),
    p_file_size_bytes, lower(btrim(p_file_type)), lower(btrim(p_file_fingerprint)),
    p_page_count, nullif(btrim(p_sheet_size), ''), nullif(btrim(p_scale), ''),
    nullif(btrim(p_change_summary), ''), 'PENDING_REVIEW', v_user_id
  );

  update public.engineering_documents
  set current_revision_id = p_revision_id,
      current_revision_number = btrim(p_revision_number),
      updated_at = now()
  where id = p_document_id and company_id = p_company_id
  returning * into v_doc;

  select * into v_revision
  from public.engineering_document_revisions
  where id = p_revision_id and company_id = p_company_id;

  return jsonb_build_object('document', to_jsonb(v_doc), 'revision', to_jsonb(v_revision));
end;
$$;

create or replace function public.create_engineering_revision(
  p_company_id uuid,
  p_document_id uuid,
  p_revision_id uuid,
  p_revision_number text,
  p_revision_label text,
  p_file_name text,
  p_file_path text,
  p_file_size_bytes bigint,
  p_file_type text,
  p_file_fingerprint text,
  p_page_count integer,
  p_sheet_size text,
  p_scale text,
  p_change_summary text,
  p_document_status text,
  p_revision_status text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_doc public.engineering_documents;
  v_revision public.engineering_document_revisions;
begin
  if v_user_id is null
     or not (
       (select public.has_company_permission(p_company_id, 'engineering.documents.create'))
       or (select public.has_company_permission(p_company_id, 'engineering.documents.manage'))
     ) then
    raise exception 'Engineering revision create permission is required' using errcode = '42501';
  end if;

  if not exists (
    select 1 from storage.objects o
    where o.bucket_id = 'engineering-documents' and o.name = p_file_path
  ) then
    raise exception 'The uploaded engineering PDF object was not found in private Storage' using errcode = '22023';
  end if;

  select * into v_doc
  from public.engineering_documents d
  where d.id = p_document_id and d.company_id = p_company_id
  for update;

  if not found or v_doc.status = 'ARCHIVED' then
    raise exception 'Engineering document is unavailable for this revision' using errcode = '42501';
  end if;

  insert into public.engineering_document_revisions (
    id, company_id, document_id, revision_number, revision_label, file_name, file_path,
    file_size_bytes, file_type, file_fingerprint, page_count, sheet_size, scale,
    change_summary, status, created_by_user_id
  ) values (
    p_revision_id, p_company_id, p_document_id, btrim(p_revision_number),
    nullif(btrim(p_revision_label), ''), btrim(p_file_name), btrim(p_file_path),
    p_file_size_bytes, lower(btrim(p_file_type)), lower(btrim(p_file_fingerprint)),
    p_page_count, nullif(btrim(p_sheet_size), ''), nullif(btrim(p_scale), ''),
    nullif(btrim(p_change_summary), ''), coalesce(nullif(btrim(p_revision_status), ''), 'PENDING_REVIEW'), v_user_id
  );

  update public.engineering_documents
  set current_revision_id = p_revision_id,
      current_revision_number = btrim(p_revision_number),
      status = coalesce(nullif(btrim(p_document_status), ''), 'UNDER_REVIEW'),
      updated_at = now()
  where id = p_document_id and company_id = p_company_id
  returning * into v_doc;

  select * into v_revision
  from public.engineering_document_revisions
  where id = p_revision_id and company_id = p_company_id;

  return jsonb_build_object('document', to_jsonb(v_doc), 'revision', to_jsonb(v_revision));
end;
$$;

revoke execute on function public.create_engineering_document_with_revision(uuid, uuid, uuid, uuid, text, text, text, text, text, text[], jsonb, text, text, text, text, bigint, text, text, integer, text, text, text) from public, anon;
revoke execute on function public.create_engineering_revision(uuid, uuid, uuid, text, text, text, text, bigint, text, text, integer, text, text, text, text, text) from public, anon;
grant execute on function public.create_engineering_document_with_revision(uuid, uuid, uuid, uuid, text, text, text, text, text, text[], jsonb, text, text, text, text, bigint, text, text, integer, text, text, text) to authenticated;
grant execute on function public.create_engineering_revision(uuid, uuid, uuid, text, text, text, text, bigint, text, text, integer, text, text, text, text, text) to authenticated;

revoke execute on function private.validate_engineering_current_revision() from public, anon, authenticated;
revoke execute on function private.prevent_engineering_revision_mutation() from public, anon, authenticated;
revoke execute on function private.validate_engineering_revision_source() from public, anon, authenticated;
